before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: 'Refactors'
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: 'Other'
      order: 999

release:
  github:
    owner: proxmox
    name: pve-apiclient-go
  name_template: "{{.ProjectName}}-v{{.Version}}"
  draft: false
  prerelease: auto

announce:
  skip: true