// Code generated by cmd/pvegen. DO NOT EDIT.

// Package nodes exposes typed bindings for the PVE /nodes endpoint family.
package nodes

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
)

var _ = strings.TrimPrefix
var _ = json.RawMessage(nil)
var _ = url.PathEscape
var _ = sort.Ints
var _ = strconv.Itoa

// Service exposes typed operations on the /nodes endpoint family.
type Service interface {
	// ListNodes GET /nodes
	// List Nodes (only for compatibility)
	ListNodes(ctx context.Context) (*ListNodesResponse, error)
	// GetNodes GET /nodes/{node}
	// Directory index.
	GetNodes(ctx context.Context, node string) error
	// ListApt GET /nodes/{node}/apt
	// Directory index.
	ListApt(ctx context.Context, node string) error
	// ListAptChangelog GET /nodes/{node}/apt/changelog
	// Retrieve the changelog of the specified package.
	ListAptChangelog(ctx context.Context, node string, params *ListAptChangelogParams) (*ListAptChangelogResponse, error)
	// ListAptRepositories GET /nodes/{node}/apt/repositories
	// Get APT repository information.
	ListAptRepositories(ctx context.Context, node string) (*ListAptRepositoriesResponse, error)
	// CreateAptRepositories POST /nodes/{node}/apt/repositories
	// Change the properties of the specified repository.  The `digest` parameter asserts that the configuration has not been modified.
	CreateAptRepositories(ctx context.Context, node string, params *CreateAptRepositoriesParams) error
	// UpdateAptRepositories PUT /nodes/{node}/apt/repositories
	// Add the repository identified by the `handle`. If the repository is already configured, it will be set to enabled.  The `digest` parameter asserts that the configuration has not been modified.
	UpdateAptRepositories(ctx context.Context, node string, params *UpdateAptRepositoriesParams) error
	// ListAptUpdate GET /nodes/{node}/apt/update
	// List available APT updates
	ListAptUpdate(ctx context.Context, node string) (*ListAptUpdateResponse, error)
	// CreateAptUpdate POST /nodes/{node}/apt/update
	// Update the APT database
	CreateAptUpdate(ctx context.Context, node string, params *CreateAptUpdateParams) (*CreateAptUpdateResponse, error)
	// ListAptVersions GET /nodes/{node}/apt/versions
	// Get package information for important Proxmox Backup Server packages.
	ListAptVersions(ctx context.Context, node string) (*ListAptVersionsResponse, error)
	// ListCertificates GET /nodes/{node}/certificates
	// Directory index.
	ListCertificates(ctx context.Context, node string) error
	// ListCertificatesAcme GET /nodes/{node}/certificates/acme
	// Directory index.
	ListCertificatesAcme(ctx context.Context, node string) error
	// CreateCertificatesAcmeCertificate POST /nodes/{node}/certificates/acme/certificate
	// Order a new ACME certificate.
	CreateCertificatesAcmeCertificate(ctx context.Context, node string, params *CreateCertificatesAcmeCertificateParams) (*CreateCertificatesAcmeCertificateResponse, error)
	// UpdateCertificatesAcmeCertificate PUT /nodes/{node}/certificates/acme/certificate
	// Renew the current ACME certificate if it expires within 30 days (or always if the `force` parameter is set).
	UpdateCertificatesAcmeCertificate(ctx context.Context, node string, params *UpdateCertificatesAcmeCertificateParams) (*UpdateCertificatesAcmeCertificateResponse, error)
	// DeleteCertificatesCustom DELETE /nodes/{node}/certificates/custom
	// Delete the current certificate and regenerate a self signed one.
	DeleteCertificatesCustom(ctx context.Context, node string, params *DeleteCertificatesCustomParams) error
	// CreateCertificatesCustom POST /nodes/{node}/certificates/custom
	// Upload a custom certificate.
	CreateCertificatesCustom(ctx context.Context, node string, params *CreateCertificatesCustomParams) (*CreateCertificatesCustomResponse, error)
	// ListCertificatesInfo GET /nodes/{node}/certificates/info
	// Get certificate info.
	ListCertificatesInfo(ctx context.Context, node string) (*ListCertificatesInfoResponse, error)
	// ListConfig GET /nodes/{node}/config
	// Get the node configuration
	ListConfig(ctx context.Context, node string) (*ListConfigResponse, error)
	// UpdateConfig PUT /nodes/{node}/config
	// Update the node configuration
	UpdateConfig(ctx context.Context, node string, params *UpdateConfigParams) error
	// ListDns GET /nodes/{node}/dns
	// Read DNS settings.
	ListDns(ctx context.Context, node string) (*ListDnsResponse, error)
	// UpdateDns PUT /nodes/{node}/dns
	// Update DNS settings.
	UpdateDns(ctx context.Context, node string, params *UpdateDnsParams) error
	// ListJournal GET /nodes/{node}/journal
	// Read syslog entries.
	ListJournal(ctx context.Context, node string, params *ListJournalParams) (*ListJournalResponse, error)
	// DeleteNetwork DELETE /nodes/{node}/network
	// Revert network configuration (rm /etc/network/interfaces.new).
	DeleteNetwork(ctx context.Context, node string) error
	// ListNetwork GET /nodes/{node}/network
	// List all network devices
	ListNetwork(ctx context.Context, node string) (*ListNetworkResponse, error)
	// CreateNetwork POST /nodes/{node}/network
	// Create network interface configuration.
	CreateNetwork(ctx context.Context, node string, params *CreateNetworkParams) error
	// UpdateNetwork PUT /nodes/{node}/network
	// Reload network configuration (requires ifupdown2).
	UpdateNetwork(ctx context.Context, node string) (*UpdateNetworkResponse, error)
	// DeleteNetwork2 DELETE /nodes/{node}/network/{iface}
	// Remove network interface configuration.
	DeleteNetwork2(ctx context.Context, node string, iface string, params *DeleteNetwork2Params) error
	// GetNetwork GET /nodes/{node}/network/{iface}
	// Read a network interface configuration.
	GetNetwork(ctx context.Context, node string, iface string) (*GetNetworkResponse, error)
	// UpdateNetwork2 PUT /nodes/{node}/network/{iface}
	// Update network interface config.
	UpdateNetwork2(ctx context.Context, node string, iface string, params *UpdateNetwork2Params) error
	// ListReport GET /nodes/{node}/report
	// Get the system report for this node.
	ListReport(ctx context.Context, node string) (*ListReportResponse, error)
	// ListRrddata GET /nodes/{node}/rrddata
	// Read RRD data for this PDM node.
	ListRrddata(ctx context.Context, node string, params *ListRrddataParams) (*ListRrddataResponse, error)
	// ListSdn GET /nodes/{node}/sdn
	// Directory index.
	ListSdn(ctx context.Context, node string) error
	// GetSdnVnets GET /nodes/{node}/sdn/vnets/{vnet}
	// Directory index.
	GetSdnVnets(ctx context.Context, node string, vnet string) error
	// ListSdnVnetsMacVrf GET /nodes/{node}/sdn/vnets/{vnet}/mac-vrf
	// Get the MAC-VRF for an EVPN vnet for a node on a given remote
	ListSdnVnetsMacVrf(ctx context.Context, node string, vnet string, params *ListSdnVnetsMacVrfParams) (*ListSdnVnetsMacVrfResponse, error)
	// GetSdnZones GET /nodes/{node}/sdn/zones/{zone}
	// Directory index.
	GetSdnZones(ctx context.Context, node string, zone string) error
	// ListSdnZonesIpVrf GET /nodes/{node}/sdn/zones/{zone}/ip-vrf
	// Get the IP-VRF for an EVPN zone for a node on a given remote
	ListSdnZonesIpVrf(ctx context.Context, node string, zone string, params *ListSdnZonesIpVrfParams) (*ListSdnZonesIpVrfResponse, error)
	// ListStatus GET /nodes/{node}/status
	// Read node memory, CPU and (root) disk usage
	ListStatus(ctx context.Context, node string) (*ListStatusResponse, error)
	// CreateStatus POST /nodes/{node}/status
	// Reboot or shutdown the node.
	CreateStatus(ctx context.Context, node string, params *CreateStatusParams) error
	// ListSubscription GET /nodes/{node}/subscription
	// Return subscription status
	ListSubscription(ctx context.Context, node string) (*ListSubscriptionResponse, error)
	// CreateSubscription POST /nodes/{node}/subscription
	// Update subscription information
	CreateSubscription(ctx context.Context, node string) error
	// ListSyslog GET /nodes/{node}/syslog
	// Read syslog entries.
	ListSyslog(ctx context.Context, node string, params *ListSyslogParams) (*ListSyslogResponse, error)
	// ListTasks GET /nodes/{node}/tasks
	// List tasks.
	ListTasks(ctx context.Context, node string, params *ListTasksParams) (*ListTasksResponse, error)
	// DeleteTasks DELETE /nodes/{node}/tasks/{upid}
	// Try to stop a task.
	DeleteTasks(ctx context.Context, node string, upid string) error
	// GetTasks GET /nodes/{node}/tasks/{upid}
	// Directory index.
	GetTasks(ctx context.Context, node string, upid string) error
	// ListTasksLog GET /nodes/{node}/tasks/{upid}/log
	// Read the task log
	ListTasksLog(ctx context.Context, node string, upid string, params *ListTasksLogParams) (*ListTasksLogResponse, error)
	// ListTasksStatus GET /nodes/{node}/tasks/{upid}/status
	// Get task status.
	ListTasksStatus(ctx context.Context, node string, upid string) (*ListTasksStatusResponse, error)
	// CreateTermproxy POST /nodes/{node}/termproxy
	// Call termproxy and return shell ticket
	CreateTermproxy(ctx context.Context, node string, params *CreateTermproxyParams) (*CreateTermproxyResponse, error)
	// ListTime GET /nodes/{node}/time
	// Read server time and time zone settings.
	ListTime(ctx context.Context, node string) (*ListTimeResponse, error)
	// UpdateTime PUT /nodes/{node}/time
	// Set time zone
	UpdateTime(ctx context.Context, node string, params *UpdateTimeParams) error
	// ListVncwebsocket GET /nodes/{node}/vncwebsocket
	// Upgraded to websocket
	ListVncwebsocket(ctx context.Context, node string, params *ListVncwebsocketParams) error
}

// New constructs a Service backed by the given pkg/client.Client.
// The client owns authentication, TLS, retries, and logging; this
// service only translates between typed Go shapes and the raw client.
func New(c client.Client) Service {
	if c == nil {
		panic("nodes: New called with nil client")
	}
	return &service{c: c}
}

type service struct {
	c client.Client
}

// ListNodesResponse mirrors the shape returned by GET /nodes.
type ListNodesResponse []json.RawMessage

// ListNodes implements Service.ListNodes. GET /nodes.
func (s *service) ListNodes(ctx context.Context) (*ListNodesResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListNodes: ctx must not be nil")
	}
	path := "/nodes"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListNodes: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListNodes: nil response from client")
	}
	if resp.Data == nil {
		out := ListNodesResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListNodes: re-marshal data: %w", err)
	}
	out := &ListNodesResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListNodes: unmarshal data: %w", err)
	}
	return out, nil
}

// GetNodes implements Service.GetNodes. GET /nodes/{node}.
func (s *service) GetNodes(ctx context.Context, node string) error {
	if ctx == nil {
		return fmt.Errorf("nodes.GetNodes: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.GetNodes: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.GetNodes: nil response from client")
	}
	_ = resp
	return nil
}

// ListApt implements Service.ListApt. GET /nodes/{node}/apt.
func (s *service) ListApt(ctx context.Context, node string) error {
	if ctx == nil {
		return fmt.Errorf("nodes.ListApt: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/apt", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.ListApt: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.ListApt: nil response from client")
	}
	_ = resp
	return nil
}

// ListAptChangelogParams is the request payload for ListAptChangelog.
type ListAptChangelogParams struct {
	// Name Package name to get changelog of.
	Name string `json:"name"`
	// Version Package version to get changelog of. Omit to use candidate version.
	Version *string `json:"version,omitempty"`
}

// ListAptChangelogResponse is the raw JSON returned by GET /nodes/{node}/apt/changelog.
type ListAptChangelogResponse = json.RawMessage

// ListAptChangelog implements Service.ListAptChangelog. GET /nodes/{node}/apt/changelog.
func (s *service) ListAptChangelog(ctx context.Context, node string, params *ListAptChangelogParams) (*ListAptChangelogResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListAptChangelog: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/apt/changelog", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListAptChangelog: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListAptChangelog: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListAptChangelog: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListAptChangelog: nil response from client")
	}
	if resp.Data == nil {
		out := ListAptChangelogResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListAptChangelog: re-marshal data: %w", err)
	}
	out := &ListAptChangelogResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListAptChangelog: unmarshal data: %w", err)
	}
	return out, nil
}

// ListAptRepositoriesResponse mirrors the shape returned by GET /nodes/{node}/apt/repositories.
type ListAptRepositoriesResponse struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest string `json:"digest"`
	// Errors List of problematic files.
	Errors []json.RawMessage `json:"errors"`
	// Files List of parsed repository files.
	Files []json.RawMessage `json:"files"`
	// Infos List of additional information/warnings about the repositories
	Infos []json.RawMessage `json:"infos"`
	// StandardRepos List of standard repositories and their configuration status.
	StandardRepos []json.RawMessage `json:"standard-repos"`
}

// ListAptRepositories implements Service.ListAptRepositories. GET /nodes/{node}/apt/repositories.
func (s *service) ListAptRepositories(ctx context.Context, node string) (*ListAptRepositoriesResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListAptRepositories: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/apt/repositories", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListAptRepositories: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListAptRepositories: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("nodes.ListAptRepositories: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListAptRepositories: re-marshal data: %w", err)
	}
	out := &ListAptRepositoriesResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListAptRepositories: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateAptRepositoriesParams is the request payload for CreateAptRepositories.
type CreateAptRepositoriesParams struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Enabled Whether the repository should be enabled or not.
	Enabled *bool `json:"enabled,omitempty"`
	// Index Index within the file (starting from 0).
	Index int64 `json:"index"`
	// Path Path to the containing file.
	Path string `json:"path"`
}

// CreateAptRepositories implements Service.CreateAptRepositories. POST /nodes/{node}/apt/repositories.
func (s *service) CreateAptRepositories(ctx context.Context, node string, params *CreateAptRepositoriesParams) error {
	if ctx == nil {
		return fmt.Errorf("nodes.CreateAptRepositories: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/apt/repositories", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("nodes.CreateAptRepositories: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("nodes.CreateAptRepositories: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.CreateAptRepositories: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.CreateAptRepositories: nil response from client")
	}
	_ = resp
	return nil
}

// UpdateAptRepositoriesParams is the request payload for UpdateAptRepositories.
type UpdateAptRepositoriesParams struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Handle Handle referencing a standard APT repository.
	Handle string `json:"handle"`
}

// UpdateAptRepositories implements Service.UpdateAptRepositories. PUT /nodes/{node}/apt/repositories.
func (s *service) UpdateAptRepositories(ctx context.Context, node string, params *UpdateAptRepositoriesParams) error {
	if ctx == nil {
		return fmt.Errorf("nodes.UpdateAptRepositories: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/apt/repositories", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("nodes.UpdateAptRepositories: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("nodes.UpdateAptRepositories: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.UpdateAptRepositories: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.UpdateAptRepositories: nil response from client")
	}
	_ = resp
	return nil
}

// ListAptUpdateResponse mirrors the shape returned by GET /nodes/{node}/apt/update.
type ListAptUpdateResponse []json.RawMessage

// ListAptUpdate implements Service.ListAptUpdate. GET /nodes/{node}/apt/update.
func (s *service) ListAptUpdate(ctx context.Context, node string) (*ListAptUpdateResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListAptUpdate: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/apt/update", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListAptUpdate: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListAptUpdate: nil response from client")
	}
	if resp.Data == nil {
		out := ListAptUpdateResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListAptUpdate: re-marshal data: %w", err)
	}
	out := &ListAptUpdateResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListAptUpdate: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateAptUpdateParams is the request payload for CreateAptUpdate.
type CreateAptUpdateParams struct {
	// Notify Send notification mail about new package updates available to the email address configured for 'root@pam').
	Notify *bool `json:"notify,omitempty"`
	// Quiet Only produces output suitable for logging, omitting progress indicators.
	Quiet *bool `json:"quiet,omitempty"`
}

// CreateAptUpdateResponse is the raw JSON returned by POST /nodes/{node}/apt/update.
type CreateAptUpdateResponse = json.RawMessage

// CreateAptUpdate implements Service.CreateAptUpdate. POST /nodes/{node}/apt/update.
func (s *service) CreateAptUpdate(ctx context.Context, node string, params *CreateAptUpdateParams) (*CreateAptUpdateResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.CreateAptUpdate: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/apt/update", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("nodes.CreateAptUpdate: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("nodes.CreateAptUpdate: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.CreateAptUpdate: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.CreateAptUpdate: nil response from client")
	}
	if resp.Data == nil {
		out := CreateAptUpdateResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.CreateAptUpdate: re-marshal data: %w", err)
	}
	out := &CreateAptUpdateResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.CreateAptUpdate: unmarshal data: %w", err)
	}
	return out, nil
}

// ListAptVersionsResponse mirrors the shape returned by GET /nodes/{node}/apt/versions.
type ListAptVersionsResponse []json.RawMessage

// ListAptVersions implements Service.ListAptVersions. GET /nodes/{node}/apt/versions.
func (s *service) ListAptVersions(ctx context.Context, node string) (*ListAptVersionsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListAptVersions: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/apt/versions", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListAptVersions: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListAptVersions: nil response from client")
	}
	if resp.Data == nil {
		out := ListAptVersionsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListAptVersions: re-marshal data: %w", err)
	}
	out := &ListAptVersionsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListAptVersions: unmarshal data: %w", err)
	}
	return out, nil
}

// ListCertificates implements Service.ListCertificates. GET /nodes/{node}/certificates.
func (s *service) ListCertificates(ctx context.Context, node string) error {
	if ctx == nil {
		return fmt.Errorf("nodes.ListCertificates: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/certificates", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.ListCertificates: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.ListCertificates: nil response from client")
	}
	_ = resp
	return nil
}

// ListCertificatesAcme implements Service.ListCertificatesAcme. GET /nodes/{node}/certificates/acme.
func (s *service) ListCertificatesAcme(ctx context.Context, node string) error {
	if ctx == nil {
		return fmt.Errorf("nodes.ListCertificatesAcme: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/certificates/acme", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.ListCertificatesAcme: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.ListCertificatesAcme: nil response from client")
	}
	_ = resp
	return nil
}

// CreateCertificatesAcmeCertificateParams is the request payload for CreateCertificatesAcmeCertificate.
type CreateCertificatesAcmeCertificateParams struct {
	// Force Force replacement of existing files.
	Force *bool `json:"force,omitempty"`
}

// CreateCertificatesAcmeCertificateResponse is the raw JSON returned by POST /nodes/{node}/certificates/acme/certificate.
type CreateCertificatesAcmeCertificateResponse = json.RawMessage

// CreateCertificatesAcmeCertificate implements Service.CreateCertificatesAcmeCertificate. POST /nodes/{node}/certificates/acme/certificate.
func (s *service) CreateCertificatesAcmeCertificate(ctx context.Context, node string, params *CreateCertificatesAcmeCertificateParams) (*CreateCertificatesAcmeCertificateResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.CreateCertificatesAcmeCertificate: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/certificates/acme/certificate", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("nodes.CreateCertificatesAcmeCertificate: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("nodes.CreateCertificatesAcmeCertificate: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.CreateCertificatesAcmeCertificate: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.CreateCertificatesAcmeCertificate: nil response from client")
	}
	if resp.Data == nil {
		out := CreateCertificatesAcmeCertificateResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.CreateCertificatesAcmeCertificate: re-marshal data: %w", err)
	}
	out := &CreateCertificatesAcmeCertificateResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.CreateCertificatesAcmeCertificate: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateCertificatesAcmeCertificateParams is the request payload for UpdateCertificatesAcmeCertificate.
type UpdateCertificatesAcmeCertificateParams struct {
	// Force Force replacement of existing files.
	Force *bool `json:"force,omitempty"`
}

// UpdateCertificatesAcmeCertificateResponse is the raw JSON returned by PUT /nodes/{node}/certificates/acme/certificate.
type UpdateCertificatesAcmeCertificateResponse = json.RawMessage

// UpdateCertificatesAcmeCertificate implements Service.UpdateCertificatesAcmeCertificate. PUT /nodes/{node}/certificates/acme/certificate.
func (s *service) UpdateCertificatesAcmeCertificate(ctx context.Context, node string, params *UpdateCertificatesAcmeCertificateParams) (*UpdateCertificatesAcmeCertificateResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.UpdateCertificatesAcmeCertificate: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/certificates/acme/certificate", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("nodes.UpdateCertificatesAcmeCertificate: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("nodes.UpdateCertificatesAcmeCertificate: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.UpdateCertificatesAcmeCertificate: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.UpdateCertificatesAcmeCertificate: nil response from client")
	}
	if resp.Data == nil {
		out := UpdateCertificatesAcmeCertificateResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.UpdateCertificatesAcmeCertificate: re-marshal data: %w", err)
	}
	out := &UpdateCertificatesAcmeCertificateResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.UpdateCertificatesAcmeCertificate: unmarshal data: %w", err)
	}
	return out, nil
}

// DeleteCertificatesCustomParams is the request payload for DeleteCertificatesCustom.
type DeleteCertificatesCustomParams struct {
	// Restart UI compatibility parameter, ignored
	Restart *bool `json:"restart,omitempty"`
}

// DeleteCertificatesCustom implements Service.DeleteCertificatesCustom. DELETE /nodes/{node}/certificates/custom.
func (s *service) DeleteCertificatesCustom(ctx context.Context, node string, params *DeleteCertificatesCustomParams) error {
	if ctx == nil {
		return fmt.Errorf("nodes.DeleteCertificatesCustom: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/certificates/custom", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("nodes.DeleteCertificatesCustom: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("nodes.DeleteCertificatesCustom: decode params: %w", err)
		}
	}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.DeleteCertificatesCustom: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.DeleteCertificatesCustom: nil response from client")
	}
	_ = resp
	return nil
}

// CreateCertificatesCustomParams is the request payload for CreateCertificatesCustom.
type CreateCertificatesCustomParams struct {
	// Certificates PEM encoded certificate (chain).
	Certificates string `json:"certificates"`
	// Force Force replacement of existing files.
	Force *bool `json:"force,omitempty"`
	// Key PEM encoded private key.
	Key *string `json:"key,omitempty"`
	// Restart UI compatibility parameter, ignored
	Restart *bool `json:"restart,omitempty"`
}

// CreateCertificatesCustomResponse mirrors the shape returned by POST /nodes/{node}/certificates/custom.
type CreateCertificatesCustomResponse []json.RawMessage

// CreateCertificatesCustom implements Service.CreateCertificatesCustom. POST /nodes/{node}/certificates/custom.
func (s *service) CreateCertificatesCustom(ctx context.Context, node string, params *CreateCertificatesCustomParams) (*CreateCertificatesCustomResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.CreateCertificatesCustom: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/certificates/custom", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("nodes.CreateCertificatesCustom: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("nodes.CreateCertificatesCustom: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.CreateCertificatesCustom: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.CreateCertificatesCustom: nil response from client")
	}
	if resp.Data == nil {
		out := CreateCertificatesCustomResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.CreateCertificatesCustom: re-marshal data: %w", err)
	}
	out := &CreateCertificatesCustomResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.CreateCertificatesCustom: unmarshal data: %w", err)
	}
	return out, nil
}

// ListCertificatesInfoResponse mirrors the shape returned by GET /nodes/{node}/certificates/info.
type ListCertificatesInfoResponse []json.RawMessage

// ListCertificatesInfo implements Service.ListCertificatesInfo. GET /nodes/{node}/certificates/info.
func (s *service) ListCertificatesInfo(ctx context.Context, node string) (*ListCertificatesInfoResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListCertificatesInfo: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/certificates/info", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListCertificatesInfo: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListCertificatesInfo: nil response from client")
	}
	if resp.Data == nil {
		out := ListCertificatesInfoResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListCertificatesInfo: re-marshal data: %w", err)
	}
	out := &ListCertificatesInfoResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListCertificatesInfo: unmarshal data: %w", err)
	}
	return out, nil
}

// ListConfigResponse mirrors the shape returned by GET /nodes/{node}/config.
type ListConfigResponse struct {
	// CiphersTls12 OpenSSL cipher list used by the api server for TLS <= 1.2
	CiphersTls12 *string `json:"ciphers-tls-1.2,omitempty"`
	// CiphersTls13 OpenSSL ciphersuites list used by the api server for TLS 1.3
	CiphersTls13 *string `json:"ciphers-tls-1.3,omitempty"`
	// DefaultLang All available languages in Proxmox. Taken from proxmox-i18n repository. pt_BR, zh_CN, and zh_TW use the same case in the translation files.
	DefaultLang *string `json:"default-lang,omitempty"`
	// EmailFrom E-Mail Address.
	EmailFrom *string `json:"email-from,omitempty"`
	// HttpProxy HTTP proxy configuration [http://]<host>[:port]
	HttpProxy *string `json:"http-proxy,omitempty"`
}

// ListConfig implements Service.ListConfig. GET /nodes/{node}/config.
func (s *service) ListConfig(ctx context.Context, node string) (*ListConfigResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListConfig: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/config", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListConfig: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListConfig: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("nodes.ListConfig: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListConfig: re-marshal data: %w", err)
	}
	out := &ListConfigResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListConfig: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateConfigParams is the request payload for UpdateConfig.
type UpdateConfigParams struct {
	// CiphersTls12 OpenSSL cipher list used by the api server for TLS <= 1.2
	CiphersTls12 *string `json:"ciphers-tls-1.2,omitempty"`
	// CiphersTls13 OpenSSL ciphersuites list used by the api server for TLS 1.3
	CiphersTls13 *string `json:"ciphers-tls-1.3,omitempty"`
	// DefaultLang All available languages in Proxmox. Taken from proxmox-i18n repository. pt_BR, zh_CN, and zh_TW use the same case in the translation files.
	DefaultLang *string `json:"default-lang,omitempty"`
	// Delete List of properties to delete.
	Delete []string `json:"delete,omitempty"`
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// EmailFrom E-Mail Address.
	EmailFrom *string `json:"email-from,omitempty"`
	// HttpProxy HTTP proxy configuration [http://]<host>[:port]
	HttpProxy *string `json:"http-proxy,omitempty"`
}

// UpdateConfig implements Service.UpdateConfig. PUT /nodes/{node}/config.
func (s *service) UpdateConfig(ctx context.Context, node string, params *UpdateConfigParams) error {
	if ctx == nil {
		return fmt.Errorf("nodes.UpdateConfig: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/config", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("nodes.UpdateConfig: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("nodes.UpdateConfig: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.UpdateConfig: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.UpdateConfig: nil response from client")
	}
	_ = resp
	return nil
}

// ListDnsResponse mirrors the shape returned by GET /nodes/{node}/dns.
type ListDnsResponse struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest string `json:"digest"`
	// Dns1 First name server IP address.
	Dns1 *string `json:"dns1,omitempty"`
	// Dns2 Second name server IP address.
	Dns2 *string `json:"dns2,omitempty"`
	// Dns3 Third name server IP address.
	Dns3 *string `json:"dns3,omitempty"`
	// Options Other data found in the configuration file (resolv.conf).
	Options *string `json:"options,omitempty"`
	// Search Search domain for host-name lookup.
	Search *string `json:"search,omitempty"`
}

// ListDns implements Service.ListDns. GET /nodes/{node}/dns.
func (s *service) ListDns(ctx context.Context, node string) (*ListDnsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListDns: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/dns", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListDns: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListDns: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("nodes.ListDns: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListDns: re-marshal data: %w", err)
	}
	out := &ListDnsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListDns: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateDnsParams is the request payload for UpdateDns.
type UpdateDnsParams struct {
	// Delete List of properties to delete.
	Delete []string `json:"delete,omitempty"`
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Dns1 First name server IP address.
	Dns1 *string `json:"dns1,omitempty"`
	// Dns2 Second name server IP address.
	Dns2 *string `json:"dns2,omitempty"`
	// Dns3 Third name server IP address.
	Dns3 *string `json:"dns3,omitempty"`
	// Options Other data found in the configuration file (resolv.conf).
	Options *string `json:"options,omitempty"`
	// Search Search domain for host-name lookup.
	Search *string `json:"search,omitempty"`
}

// UpdateDns implements Service.UpdateDns. PUT /nodes/{node}/dns.
func (s *service) UpdateDns(ctx context.Context, node string, params *UpdateDnsParams) error {
	if ctx == nil {
		return fmt.Errorf("nodes.UpdateDns: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/dns", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("nodes.UpdateDns: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("nodes.UpdateDns: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.UpdateDns: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.UpdateDns: nil response from client")
	}
	_ = resp
	return nil
}

// ListJournalParams is the request payload for ListJournal.
type ListJournalParams struct {
	// Endcursor End before the given Cursor. Conflicts with 'until'
	Endcursor *string `json:"endcursor,omitempty"`
	// Identifiers Also list the distinct syslog identifiers present. Requires 'structured'.
	Identifiers *bool `json:"identifiers,omitempty"`
	// Kernel Only print kernel messages.
	Kernel *bool `json:"kernel,omitempty"`
	// Lastentries Limit to the last X lines. Conflicts with a range.
	Lastentries *int64 `json:"lastentries,omitempty"`
	// Priority Only print messages of this syslog priority: a single level from 0 (emerg) to 7 (debug), selecting that level and everything more severe, or a 'LOW..HIGH' range. Empty means no filter.
	Priority *string `json:"priority,omitempty"`
	// Service Only print messages whose syslog identifier matches this glob.
	Service *string `json:"service,omitempty"`
	// Since Display all log since this UNIX epoch. Conflicts with 'startcursor'.
	Since *int64 `json:"since,omitempty"`
	// Startcursor Start after the given Cursor. Conflicts with 'since'.
	Startcursor *string `json:"startcursor,omitempty"`
	// Structured Emit structured JSON with separate entry fields instead of plain text.
	Structured *bool `json:"structured,omitempty"`
	// Unit Only print messages of this systemd unit (the .service suffix is implied).
	Unit *string `json:"unit,omitempty"`
	// Units Also list the distinct systemd units present. Requires 'structured'.
	Units *bool `json:"units,omitempty"`
	// Until Display all log until this UNIX epoch. Conflicts with 'endcursor'.
	Until *int64 `json:"until,omitempty"`
}

// ListJournalResponse mirrors the shape returned by GET /nodes/{node}/journal.
type ListJournalResponse []string

// ListJournal implements Service.ListJournal. GET /nodes/{node}/journal.
func (s *service) ListJournal(ctx context.Context, node string, params *ListJournalParams) (*ListJournalResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListJournal: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/journal", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListJournal: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListJournal: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListJournal: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListJournal: nil response from client")
	}
	if resp.Data == nil {
		out := ListJournalResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListJournal: re-marshal data: %w", err)
	}
	out := &ListJournalResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListJournal: unmarshal data: %w", err)
	}
	return out, nil
}

// DeleteNetwork implements Service.DeleteNetwork. DELETE /nodes/{node}/network.
func (s *service) DeleteNetwork(ctx context.Context, node string) error {
	if ctx == nil {
		return fmt.Errorf("nodes.DeleteNetwork: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/network", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.DeleteNetwork: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.DeleteNetwork: nil response from client")
	}
	_ = resp
	return nil
}

// ListNetworkResponse mirrors the shape returned by GET /nodes/{node}/network.
type ListNetworkResponse []json.RawMessage

// ListNetwork implements Service.ListNetwork. GET /nodes/{node}/network.
func (s *service) ListNetwork(ctx context.Context, node string) (*ListNetworkResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListNetwork: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/network", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListNetwork: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListNetwork: nil response from client")
	}
	if resp.Data == nil {
		out := ListNetworkResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListNetwork: re-marshal data: %w", err)
	}
	out := &ListNetworkResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListNetwork: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateNetworkParams is the request payload for CreateNetwork.
type CreateNetworkParams struct {
	// Autostart Autostart interface.
	Autostart *bool `json:"autostart,omitempty"`
	// BondPrimary Network interface name.
	BondPrimary *string `json:"bond-primary,omitempty"`
	// BondMode Linux Bond Mode
	BondMode *string `json:"bond_mode,omitempty"`
	// BondXmitHashPolicy Bond Transmit Hash Policy for LACP (802.3ad)
	BondXmitHashPolicy *string `json:"bond_xmit_hash_policy,omitempty"`
	// BridgePorts A list of network devices, comma separated.
	BridgePorts *string `json:"bridge_ports,omitempty"`
	// BridgeVlanAware Enable bridge vlan support.
	BridgeVlanAware *bool `json:"bridge_vlan_aware,omitempty"`
	// Cidr IPv4 address with netmask (CIDR notation).
	Cidr *string `json:"cidr,omitempty"`
	// Cidr6 IPv6 address with netmask (CIDR notation).
	Cidr6 *string `json:"cidr6,omitempty"`
	// Comments Comments (inet, may span multiple lines)
	Comments *string `json:"comments,omitempty"`
	// Comments6 Comments (inet5, may span multiple lines)
	Comments6 *string `json:"comments6,omitempty"`
	// Gateway IPv4 address.
	Gateway *string `json:"gateway,omitempty"`
	// Gateway6 IPv6 address.
	Gateway6 *string `json:"gateway6,omitempty"`
	// Iface Network interface name.
	Iface string `json:"iface"`
	// Method Interface configuration method
	Method *string `json:"method,omitempty"`
	// Method6 Interface configuration method
	Method6 *string `json:"method6,omitempty"`
	// Mtu Maximum Transmission Unit.
	Mtu *int64 `json:"mtu,omitempty"`
	// Slaves A list of network devices, comma separated.
	Slaves *string `json:"slaves,omitempty"`
	// Type Network interface type
	Type *string `json:"type,omitempty"`
	// VlanId VLAN ID.
	VlanId *int64 `json:"vlan-id,omitempty"`
	// VlanRawDevice Network interface name.
	VlanRawDevice *string `json:"vlan-raw-device,omitempty"`
}

// CreateNetwork implements Service.CreateNetwork. POST /nodes/{node}/network.
func (s *service) CreateNetwork(ctx context.Context, node string, params *CreateNetworkParams) error {
	if ctx == nil {
		return fmt.Errorf("nodes.CreateNetwork: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/network", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("nodes.CreateNetwork: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("nodes.CreateNetwork: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.CreateNetwork: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.CreateNetwork: nil response from client")
	}
	_ = resp
	return nil
}

// UpdateNetworkResponse is the raw JSON returned by PUT /nodes/{node}/network.
type UpdateNetworkResponse = json.RawMessage

// UpdateNetwork implements Service.UpdateNetwork. PUT /nodes/{node}/network.
func (s *service) UpdateNetwork(ctx context.Context, node string) (*UpdateNetworkResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.UpdateNetwork: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/network", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.UpdateNetwork: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.UpdateNetwork: nil response from client")
	}
	if resp.Data == nil {
		out := UpdateNetworkResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.UpdateNetwork: re-marshal data: %w", err)
	}
	out := &UpdateNetworkResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.UpdateNetwork: unmarshal data: %w", err)
	}
	return out, nil
}

// DeleteNetwork2Params is the request payload for DeleteNetwork2.
type DeleteNetwork2Params struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
}

// DeleteNetwork2 implements Service.DeleteNetwork2. DELETE /nodes/{node}/network/{iface}.
func (s *service) DeleteNetwork2(ctx context.Context, node string, iface string, params *DeleteNetwork2Params) error {
	if ctx == nil {
		return fmt.Errorf("nodes.DeleteNetwork2: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/network/%s", url.PathEscape(node), url.PathEscape(iface))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("nodes.DeleteNetwork2: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("nodes.DeleteNetwork2: decode params: %w", err)
		}
	}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.DeleteNetwork2: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.DeleteNetwork2: nil response from client")
	}
	_ = resp
	return nil
}

// GetNetworkResponse mirrors the shape returned by GET /nodes/{node}/network/{iface}.
type GetNetworkResponse struct {
	// Active Interface is active (UP)
	Active client.PVEBool `json:"active"`
	// Altnames List of altnames for this interface
	Altnames []string `json:"altnames"`
	// Autostart Autostart interface
	Autostart client.PVEBool `json:"autostart"`
	// BondPrimary Network interface name.
	BondPrimary *string `json:"bond-primary,omitempty"`
	// BondMode Linux Bond Mode
	BondMode *string `json:"bond_mode,omitempty"`
	// BondXmitHashPolicy Bond Transmit Hash Policy for LACP (802.3ad)
	BondXmitHashPolicy *string `json:"bond_xmit_hash_policy,omitempty"`
	// BridgePorts Network interface list.
	BridgePorts []string `json:"bridge_ports,omitempty"`
	// BridgeVlanAware Enable bridge vlan support.
	BridgeVlanAware *client.PVEBool `json:"bridge_vlan_aware,omitempty"`
	// Cidr IPv4 address with netmask (CIDR notation).
	Cidr *string `json:"cidr,omitempty"`
	// Cidr6 IPv6 address with netmask (CIDR notation).
	Cidr6 *string `json:"cidr6,omitempty"`
	// Comments Comments (inet, may span multiple lines)
	Comments *string `json:"comments,omitempty"`
	// Comments6 Comments (inet6, may span multiple lines)
	Comments6 *string `json:"comments6,omitempty"`
	// Gateway IPv4 address.
	Gateway *string `json:"gateway,omitempty"`
	// Gateway6 IPv6 address.
	Gateway6 *string `json:"gateway6,omitempty"`
	// Method Interface configuration method
	Method *string `json:"method,omitempty"`
	// Method6 Interface configuration method
	Method6 *string `json:"method6,omitempty"`
	// Mtu Maximum Transmission Unit
	Mtu *client.PVEInt `json:"mtu,omitempty"`
	// Name Network interface name.
	Name string `json:"name"`
	// Options Option list (inet)
	Options []string `json:"options"`
	// Options6 Option list (inet6)
	Options6 []string `json:"options6"`
	// Slaves Network interface list.
	Slaves []string `json:"slaves,omitempty"`
	// Type Network interface type
	Type string `json:"type"`
	// VlanId VLAN ID.
	VlanId *client.PVEInt `json:"vlan-id,omitempty"`
	// VlanRawDevice Network interface name.
	VlanRawDevice *string `json:"vlan-raw-device,omitempty"`
}

// GetNetwork implements Service.GetNetwork. GET /nodes/{node}/network/{iface}.
func (s *service) GetNetwork(ctx context.Context, node string, iface string) (*GetNetworkResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.GetNetwork: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/network/%s", url.PathEscape(node), url.PathEscape(iface))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.GetNetwork: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.GetNetwork: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("nodes.GetNetwork: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.GetNetwork: re-marshal data: %w", err)
	}
	out := &GetNetworkResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.GetNetwork: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateNetwork2Params is the request payload for UpdateNetwork2.
type UpdateNetwork2Params struct {
	// Autostart Autostart interface.
	Autostart *bool `json:"autostart,omitempty"`
	// BondPrimary Network interface name.
	BondPrimary *string `json:"bond-primary,omitempty"`
	// BondMode Linux Bond Mode
	BondMode *string `json:"bond_mode,omitempty"`
	// BondXmitHashPolicy Bond Transmit Hash Policy for LACP (802.3ad)
	BondXmitHashPolicy *string `json:"bond_xmit_hash_policy,omitempty"`
	// BridgePorts A list of network devices, comma separated.
	BridgePorts *string `json:"bridge_ports,omitempty"`
	// BridgeVlanAware Enable bridge vlan support.
	BridgeVlanAware *bool `json:"bridge_vlan_aware,omitempty"`
	// Cidr IPv4 address with netmask (CIDR notation).
	Cidr *string `json:"cidr,omitempty"`
	// Cidr6 IPv6 address with netmask (CIDR notation).
	Cidr6 *string `json:"cidr6,omitempty"`
	// Comments Comments (inet, may span multiple lines)
	Comments *string `json:"comments,omitempty"`
	// Comments6 Comments (inet5, may span multiple lines)
	Comments6 *string `json:"comments6,omitempty"`
	// Delete List of properties to delete.
	Delete []string `json:"delete,omitempty"`
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Gateway IPv4 address.
	Gateway *string `json:"gateway,omitempty"`
	// Gateway6 IPv6 address.
	Gateway6 *string `json:"gateway6,omitempty"`
	// Method Interface configuration method
	Method *string `json:"method,omitempty"`
	// Method6 Interface configuration method
	Method6 *string `json:"method6,omitempty"`
	// Mtu Maximum Transmission Unit.
	Mtu *int64 `json:"mtu,omitempty"`
	// Slaves A list of network devices, comma separated.
	Slaves *string `json:"slaves,omitempty"`
	// Type Network interface type
	Type *string `json:"type,omitempty"`
	// VlanId VLAN ID.
	VlanId *int64 `json:"vlan-id,omitempty"`
	// VlanRawDevice Network interface name.
	VlanRawDevice *string `json:"vlan-raw-device,omitempty"`
}

// UpdateNetwork2 implements Service.UpdateNetwork2. PUT /nodes/{node}/network/{iface}.
func (s *service) UpdateNetwork2(ctx context.Context, node string, iface string, params *UpdateNetwork2Params) error {
	if ctx == nil {
		return fmt.Errorf("nodes.UpdateNetwork2: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/network/%s", url.PathEscape(node), url.PathEscape(iface))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("nodes.UpdateNetwork2: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("nodes.UpdateNetwork2: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.UpdateNetwork2: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.UpdateNetwork2: nil response from client")
	}
	_ = resp
	return nil
}

// ListReportResponse is the raw JSON returned by GET /nodes/{node}/report.
type ListReportResponse = json.RawMessage

// ListReport implements Service.ListReport. GET /nodes/{node}/report.
func (s *service) ListReport(ctx context.Context, node string) (*ListReportResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListReport: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/report", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListReport: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListReport: nil response from client")
	}
	if resp.Data == nil {
		out := ListReportResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListReport: re-marshal data: %w", err)
	}
	out := &ListReportResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListReport: unmarshal data: %w", err)
	}
	return out, nil
}

// ListRrddataParams is the request payload for ListRrddata.
type ListRrddataParams struct {
	// Cf RRD consolidation mode
	Cf string `json:"cf"`
	// Timeframe RRD time frame
	Timeframe string `json:"timeframe"`
}

// ListRrddataResponse mirrors the shape returned by GET /nodes/{node}/rrddata.
type ListRrddataResponse []json.RawMessage

// ListRrddata implements Service.ListRrddata. GET /nodes/{node}/rrddata.
func (s *service) ListRrddata(ctx context.Context, node string, params *ListRrddataParams) (*ListRrddataResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListRrddata: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/rrddata", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListRrddata: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListRrddata: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListRrddata: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListRrddata: nil response from client")
	}
	if resp.Data == nil {
		out := ListRrddataResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListRrddata: re-marshal data: %w", err)
	}
	out := &ListRrddataResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListRrddata: unmarshal data: %w", err)
	}
	return out, nil
}

// ListSdn implements Service.ListSdn. GET /nodes/{node}/sdn.
func (s *service) ListSdn(ctx context.Context, node string) error {
	if ctx == nil {
		return fmt.Errorf("nodes.ListSdn: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/sdn", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.ListSdn: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.ListSdn: nil response from client")
	}
	_ = resp
	return nil
}

// GetSdnVnets implements Service.GetSdnVnets. GET /nodes/{node}/sdn/vnets/{vnet}.
func (s *service) GetSdnVnets(ctx context.Context, node string, vnet string) error {
	if ctx == nil {
		return fmt.Errorf("nodes.GetSdnVnets: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/sdn/vnets/%s", url.PathEscape(node), url.PathEscape(vnet))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.GetSdnVnets: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.GetSdnVnets: nil response from client")
	}
	_ = resp
	return nil
}

// ListSdnVnetsMacVrfParams is the request payload for ListSdnVnetsMacVrf.
type ListSdnVnetsMacVrfParams struct {
	// Remote Remote ID.
	Remote string `json:"remote"`
}

// ListSdnVnetsMacVrfResponse mirrors the shape returned by GET /nodes/{node}/sdn/vnets/{vnet}/mac-vrf.
type ListSdnVnetsMacVrfResponse struct {
	// Ip The IP address of the MAC VRF entry.
	Ip string `json:"ip"`
	// Mac The MAC address of the MAC VRF entry.
	Mac string `json:"mac"`
	// Nexthop The IP address of the nexthop.
	Nexthop string `json:"nexthop"`
}

// ListSdnVnetsMacVrf implements Service.ListSdnVnetsMacVrf. GET /nodes/{node}/sdn/vnets/{vnet}/mac-vrf.
func (s *service) ListSdnVnetsMacVrf(ctx context.Context, node string, vnet string, params *ListSdnVnetsMacVrfParams) (*ListSdnVnetsMacVrfResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListSdnVnetsMacVrf: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/sdn/vnets/%s/mac-vrf", url.PathEscape(node), url.PathEscape(vnet))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListSdnVnetsMacVrf: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListSdnVnetsMacVrf: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListSdnVnetsMacVrf: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListSdnVnetsMacVrf: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("nodes.ListSdnVnetsMacVrf: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListSdnVnetsMacVrf: re-marshal data: %w", err)
	}
	out := &ListSdnVnetsMacVrfResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListSdnVnetsMacVrf: unmarshal data: %w", err)
	}
	return out, nil
}

// GetSdnZones implements Service.GetSdnZones. GET /nodes/{node}/sdn/zones/{zone}.
func (s *service) GetSdnZones(ctx context.Context, node string, zone string) error {
	if ctx == nil {
		return fmt.Errorf("nodes.GetSdnZones: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/sdn/zones/%s", url.PathEscape(node), url.PathEscape(zone))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.GetSdnZones: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.GetSdnZones: nil response from client")
	}
	_ = resp
	return nil
}

// ListSdnZonesIpVrfParams is the request payload for ListSdnZonesIpVrf.
type ListSdnZonesIpVrfParams struct {
	// Remote Remote ID.
	Remote string `json:"remote"`
}

// ListSdnZonesIpVrfResponse mirrors the shape returned by GET /nodes/{node}/sdn/zones/{zone}/ip-vrf.
type ListSdnZonesIpVrfResponse struct {
	// Ip The CIDR of the route table entry.
	Ip string `json:"ip"`
	// Metric This route's metric.
	Metric client.PVEInt `json:"metric"`
	// Nexthops A list of nexthops for the route table entry.
	Nexthops []string `json:"nexthops"`
	// Protocol The protocol where this route was learned from (e.g. BGP).
	Protocol string `json:"protocol"`
}

// ListSdnZonesIpVrf implements Service.ListSdnZonesIpVrf. GET /nodes/{node}/sdn/zones/{zone}/ip-vrf.
func (s *service) ListSdnZonesIpVrf(ctx context.Context, node string, zone string, params *ListSdnZonesIpVrfParams) (*ListSdnZonesIpVrfResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListSdnZonesIpVrf: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/sdn/zones/%s/ip-vrf", url.PathEscape(node), url.PathEscape(zone))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListSdnZonesIpVrf: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListSdnZonesIpVrf: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListSdnZonesIpVrf: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListSdnZonesIpVrf: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("nodes.ListSdnZonesIpVrf: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListSdnZonesIpVrf: re-marshal data: %w", err)
	}
	out := &ListSdnZonesIpVrfResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListSdnZonesIpVrf: unmarshal data: %w", err)
	}
	return out, nil
}

// ListStatusResponse mirrors the shape returned by GET /nodes/{node}/status.
type ListStatusResponse struct {
	// BootInfo Holds the Bootmodes
	BootInfo json.RawMessage `json:"boot-info"`
	// Cpu Total CPU usage since last query.
	Cpu client.PVEFloat `json:"cpu"`
	// Cpuinfo Information about the CPU
	Cpuinfo json.RawMessage `json:"cpuinfo"`
	// CurrentKernel The current kernel version (output of `uname`)
	CurrentKernel json.RawMessage `json:"current-kernel"`
	// Info Contains general node information such as the fingerprint`
	Info json.RawMessage `json:"info"`
	// Kversion The current kernel version (LEGACY string type).
	Kversion string `json:"kversion"`
	// Loadavg Load for 1, 5 and 15 minutes.
	Loadavg []client.PVEFloat `json:"loadavg"`
	// Memory Node memory usage counters
	Memory json.RawMessage `json:"memory"`
	// Root Storage space usage information.
	Root json.RawMessage `json:"root"`
	// Swap Node swap usage counters
	Swap json.RawMessage `json:"swap"`
	// Uptime The current uptime of the server.
	Uptime client.PVEInt `json:"uptime"`
	// Wait Total IO wait since last query.
	Wait client.PVEFloat `json:"wait"`
}

// ListStatus implements Service.ListStatus. GET /nodes/{node}/status.
func (s *service) ListStatus(ctx context.Context, node string) (*ListStatusResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListStatus: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/status", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListStatus: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListStatus: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("nodes.ListStatus: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListStatus: re-marshal data: %w", err)
	}
	out := &ListStatusResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListStatus: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateStatusParams is the request payload for CreateStatus.
type CreateStatusParams struct {
	// Command Node Power command type.
	Command string `json:"command"`
}

// CreateStatus implements Service.CreateStatus. POST /nodes/{node}/status.
func (s *service) CreateStatus(ctx context.Context, node string, params *CreateStatusParams) error {
	if ctx == nil {
		return fmt.Errorf("nodes.CreateStatus: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/status", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("nodes.CreateStatus: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("nodes.CreateStatus: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.CreateStatus: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.CreateStatus: nil response from client")
	}
	_ = resp
	return nil
}

// ListSubscriptionResponse mirrors the shape returned by GET /nodes/{node}/subscription.
type ListSubscriptionResponse struct {
	// Checktime timestamp of the last check done
	Checktime *client.PVEInt `json:"checktime,omitempty"`
	// Key the subscription key, if set and permitted to access
	Key *string `json:"key,omitempty"`
	// Message a more human readable status message
	Message *string `json:"message,omitempty"`
	// Nextduedate next due date of the set subscription
	Nextduedate *string `json:"nextduedate,omitempty"`
	// Productname human readable productname of the set subscription
	Productname *string `json:"productname,omitempty"`
	// Regdate register date of the set subscription
	Regdate *string `json:"regdate,omitempty"`
	// Serverid the server ID, if permitted to access
	Serverid *string `json:"serverid,omitempty"`
	// Signature Signature for offline keys
	Signature *string `json:"signature,omitempty"`
	// Status Subscription status
	Status string `json:"status"`
	// Url URL to the web shop
	Url *string `json:"url,omitempty"`
}

// ListSubscription implements Service.ListSubscription. GET /nodes/{node}/subscription.
func (s *service) ListSubscription(ctx context.Context, node string) (*ListSubscriptionResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListSubscription: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/subscription", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListSubscription: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListSubscription: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("nodes.ListSubscription: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListSubscription: re-marshal data: %w", err)
	}
	out := &ListSubscriptionResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListSubscription: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateSubscription implements Service.CreateSubscription. POST /nodes/{node}/subscription.
func (s *service) CreateSubscription(ctx context.Context, node string) error {
	if ctx == nil {
		return fmt.Errorf("nodes.CreateSubscription: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/subscription", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.CreateSubscription: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.CreateSubscription: nil response from client")
	}
	_ = resp
	return nil
}

// ListSyslogParams is the request payload for ListSyslog.
type ListSyslogParams struct {
	// Limit Max. number of lines.
	Limit *int64 `json:"limit,omitempty"`
	// Service Service ID.
	Service *string `json:"service,omitempty"`
	// Since Display all log since this date-time string.
	Since *string `json:"since,omitempty"`
	// Start Start line number.
	Start *int64 `json:"start,omitempty"`
	// Until Display all log until this date-time string.
	Until *string `json:"until,omitempty"`
}

// ListSyslogResponse mirrors the shape returned by GET /nodes/{node}/syslog.
type ListSyslogResponse []json.RawMessage

// ListSyslog implements Service.ListSyslog. GET /nodes/{node}/syslog.
func (s *service) ListSyslog(ctx context.Context, node string, params *ListSyslogParams) (*ListSyslogResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListSyslog: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/syslog", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListSyslog: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListSyslog: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListSyslog: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListSyslog: nil response from client")
	}
	if resp.Data == nil {
		out := ListSyslogResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListSyslog: re-marshal data: %w", err)
	}
	out := &ListSyslogResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListSyslog: unmarshal data: %w", err)
	}
	return out, nil
}

// ListTasksParams is the request payload for ListTasks.
type ListTasksParams struct {
	// Errors Only list erroneous tasks.
	Errors *bool `json:"errors,omitempty"`
	// Limit Only list this amount of tasks. (0 means no limit)
	Limit *int64 `json:"limit,omitempty"`
	// Running Only list running tasks.
	Running *bool `json:"running,omitempty"`
	// Since Only list tasks since this UNIX epoch.
	Since *int64 `json:"since,omitempty"`
	// Start List tasks beginning from this offset.
	Start *int64 `json:"start,omitempty"`
	// Statusfilter Only list tasks which have any one of the listed status.
	Statusfilter []string `json:"statusfilter,omitempty"`
	// Typefilter Only list tasks whose type contains this.
	Typefilter *string `json:"typefilter,omitempty"`
	// Until Only list tasks until this UNIX epoch.
	Until *int64 `json:"until,omitempty"`
	// Userfilter Only list tasks from this user.
	Userfilter *string `json:"userfilter,omitempty"`
}

// ListTasksResponse mirrors the shape returned by GET /nodes/{node}/tasks.
type ListTasksResponse []json.RawMessage

// ListTasks implements Service.ListTasks. GET /nodes/{node}/tasks.
func (s *service) ListTasks(ctx context.Context, node string, params *ListTasksParams) (*ListTasksResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListTasks: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/tasks", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListTasks: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListTasks: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListTasks: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListTasks: nil response from client")
	}
	if resp.Data == nil {
		out := ListTasksResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListTasks: re-marshal data: %w", err)
	}
	out := &ListTasksResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListTasks: unmarshal data: %w", err)
	}
	return out, nil
}

// DeleteTasks implements Service.DeleteTasks. DELETE /nodes/{node}/tasks/{upid}.
func (s *service) DeleteTasks(ctx context.Context, node string, upid string) error {
	if ctx == nil {
		return fmt.Errorf("nodes.DeleteTasks: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/tasks/%s", url.PathEscape(node), url.PathEscape(upid))
	var body map[string]interface{}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.DeleteTasks: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.DeleteTasks: nil response from client")
	}
	_ = resp
	return nil
}

// GetTasks implements Service.GetTasks. GET /nodes/{node}/tasks/{upid}.
func (s *service) GetTasks(ctx context.Context, node string, upid string) error {
	if ctx == nil {
		return fmt.Errorf("nodes.GetTasks: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/tasks/%s", url.PathEscape(node), url.PathEscape(upid))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.GetTasks: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.GetTasks: nil response from client")
	}
	_ = resp
	return nil
}

// ListTasksLogParams is the request payload for ListTasksLog.
type ListTasksLogParams struct {
	// Download Whether the tasklog file should be downloaded. This parameter can't be used in conjunction with other parameters
	Download *bool `json:"download,omitempty"`
	// Limit The amount of lines to read from the tasklog. Setting this parameter to 0 will return all lines until the end of the file.
	Limit *int64 `json:"limit,omitempty"`
	// Start Start at this line when reading the tasklog
	Start *int64 `json:"start,omitempty"`
	// TestStatus Test task status, and set result attribute "active" accordingly.
	TestStatus *bool `json:"test-status,omitempty"`
}

// ListTasksLogResponse mirrors the shape returned by GET /nodes/{node}/tasks/{upid}/log.
type ListTasksLogResponse []json.RawMessage

// ListTasksLog implements Service.ListTasksLog. GET /nodes/{node}/tasks/{upid}/log.
func (s *service) ListTasksLog(ctx context.Context, node string, upid string, params *ListTasksLogParams) (*ListTasksLogResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListTasksLog: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/tasks/%s/log", url.PathEscape(node), url.PathEscape(upid))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListTasksLog: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("nodes.ListTasksLog: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListTasksLog: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListTasksLog: nil response from client")
	}
	if resp.Data == nil {
		out := ListTasksLogResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListTasksLog: re-marshal data: %w", err)
	}
	out := &ListTasksLogResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListTasksLog: unmarshal data: %w", err)
	}
	return out, nil
}

// ListTasksStatusResponse mirrors the shape returned by GET /nodes/{node}/tasks/{upid}/status.
type ListTasksStatusResponse struct {
	// Exitstatus 'OK', 'Error: <msg>', or 'unknown'.
	Exitstatus *string `json:"exitstatus,omitempty"`
	// Id Worker ID (arbitrary ASCII string)
	Id *string `json:"id,omitempty"`
	// Node Node name (or 'localhost')
	Node string `json:"node"`
	// Pid The Unix PID.
	Pid client.PVEInt `json:"pid"`
	// Pstart The Unix process start time from `/proc/pid/stat`
	Pstart client.PVEInt `json:"pstart"`
	// Starttime The task start time (Epoch)
	Starttime client.PVEInt `json:"starttime"`
	// Status 'running' or 'stopped'
	Status string `json:"status"`
	// Tokenid The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full `Authid` for such use cases.
	Tokenid *string `json:"tokenid,omitempty"`
	// Type Worker type (arbitrary ASCII string)
	Type string `json:"type"`
	// Upid Unique Process/Task Identifier
	Upid string `json:"upid"`
	// User User ID
	User string `json:"user"`
}

// ListTasksStatus implements Service.ListTasksStatus. GET /nodes/{node}/tasks/{upid}/status.
func (s *service) ListTasksStatus(ctx context.Context, node string, upid string) (*ListTasksStatusResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListTasksStatus: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/tasks/%s/status", url.PathEscape(node), url.PathEscape(upid))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListTasksStatus: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListTasksStatus: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("nodes.ListTasksStatus: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListTasksStatus: re-marshal data: %w", err)
	}
	out := &ListTasksStatusResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListTasksStatus: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateTermproxyParams is the request payload for CreateTermproxy.
type CreateTermproxyParams struct {
	// Cmd The command to run.
	Cmd *string `json:"cmd,omitempty"`
}

// CreateTermproxyResponse mirrors the shape returned by POST /nodes/{node}/termproxy.
type CreateTermproxyResponse struct {
	Port   string `json:"port"`
	Ticket string `json:"ticket"`
	Upid   string `json:"upid"`
	User   string `json:"user"`
}

// CreateTermproxy implements Service.CreateTermproxy. POST /nodes/{node}/termproxy.
func (s *service) CreateTermproxy(ctx context.Context, node string, params *CreateTermproxyParams) (*CreateTermproxyResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.CreateTermproxy: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/termproxy", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("nodes.CreateTermproxy: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("nodes.CreateTermproxy: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.CreateTermproxy: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.CreateTermproxy: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("nodes.CreateTermproxy: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.CreateTermproxy: re-marshal data: %w", err)
	}
	out := &CreateTermproxyResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.CreateTermproxy: unmarshal data: %w", err)
	}
	return out, nil
}

// ListTimeResponse mirrors the shape returned by GET /nodes/{node}/time.
type ListTimeResponse struct {
	// Localtime Seconds since 1970-01-01 00:00:00 UTC. (local time)
	Localtime client.PVEInt `json:"localtime"`
	// Time Seconds since 1970-01-01 00:00:00 UTC.
	Time client.PVEInt `json:"time"`
	// Timezone Time zone. The file '/usr/share/zoneinfo/zone.tab' contains the list of valid names.
	Timezone string `json:"timezone"`
}

// ListTime implements Service.ListTime. GET /nodes/{node}/time.
func (s *service) ListTime(ctx context.Context, node string) (*ListTimeResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("nodes.ListTime: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/time", url.PathEscape(node))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListTime: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("nodes.ListTime: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("nodes.ListTime: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListTime: re-marshal data: %w", err)
	}
	out := &ListTimeResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("nodes.ListTime: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateTimeParams is the request payload for UpdateTime.
type UpdateTimeParams struct {
	// Timezone Time zone. The file '/usr/share/zoneinfo/zone.tab' contains the list of valid names.
	Timezone string `json:"timezone"`
}

// UpdateTime implements Service.UpdateTime. PUT /nodes/{node}/time.
func (s *service) UpdateTime(ctx context.Context, node string, params *UpdateTimeParams) error {
	if ctx == nil {
		return fmt.Errorf("nodes.UpdateTime: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/time", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("nodes.UpdateTime: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("nodes.UpdateTime: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.UpdateTime: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.UpdateTime: nil response from client")
	}
	_ = resp
	return nil
}

// ListVncwebsocketParams is the request payload for ListVncwebsocket.
type ListVncwebsocketParams struct {
	// Port Terminal port
	Port int64 `json:"port"`
	// Vncticket Terminal ticket
	Vncticket string `json:"vncticket"`
}

// ListVncwebsocket implements Service.ListVncwebsocket. GET /nodes/{node}/vncwebsocket.
func (s *service) ListVncwebsocket(ctx context.Context, node string, params *ListVncwebsocketParams) error {
	if ctx == nil {
		return fmt.Errorf("nodes.ListVncwebsocket: ctx must not be nil")
	}
	path := fmt.Sprintf("/nodes/%s/vncwebsocket", url.PathEscape(node))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("nodes.ListVncwebsocket: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("nodes.ListVncwebsocket: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("nodes.ListVncwebsocket: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("nodes.ListVncwebsocket: nil response from client")
	}
	_ = resp
	return nil
}
