// Code generated by cmd/pvegen. DO NOT EDIT.

package access_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"testing"

	"github.com/fivetwenty-io/pve-apiclient-go/v3/pkg/api/access"
	pveclient "github.com/fivetwenty-io/pve-apiclient-go/v3/pkg/client"
)

func smokeOptsFromServerURL(u string) pveclient.Options {
	parsed, err := url.Parse(u)
	if err != nil {
		panic("test setup: invalid server URL: " + err.Error())
	}

	host := parsed.Hostname()

	port := 0
	if p := parsed.Port(); p != "" {
		port, _ = strconv.Atoi(p)
	}

	return pveclient.Options{
		Host:     host,
		Port:     port,
		Protocol: "http",
		APIToken: "user@pam!tok=sec",
	}
}

func TestSmoke_Access_GeneratedMethods(t *testing.T) {
	t.Parallel()

	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		_ = json.NewEncoder(w).Encode(map[string]any{
			"data":    map[string]any{},
			"success": 1,
		})
	})

	srv := httptest.NewServer(mux)
	defer srv.Close()

	c, err := pveclient.NewClient(smokeOptsFromServerURL(srv.URL))
	if err != nil {
		t.Fatalf("NewClient: %v", err)
	}

	svc := access.New(c)
	ctx := context.Background()

	t.Run("ListAccess", func(t *testing.T) {
		_, err := svc.ListAccess(ctx)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListAcl", func(t *testing.T) {
		_, err := svc.ListAcl(ctx)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListDomains", func(t *testing.T) {
		_, err := svc.ListDomains(ctx)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetDomains", func(t *testing.T) {
		_, err := svc.GetDomains(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListGroups", func(t *testing.T) {
		_, err := svc.ListGroups(ctx)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetGroups", func(t *testing.T) {
		_, err := svc.GetGroups(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListOpenid", func(t *testing.T) {
		_, err := svc.ListOpenid(ctx)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListPermissions", func(t *testing.T) {
		_, err := svc.ListPermissions(ctx, nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListRoles", func(t *testing.T) {
		_, err := svc.ListRoles(ctx)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetRoles", func(t *testing.T) {
		_, err := svc.GetRoles(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListTfa", func(t *testing.T) {
		_, err := svc.ListTfa(ctx)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetTfa", func(t *testing.T) {
		_, err := svc.GetTfa(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetTfa2", func(t *testing.T) {
		_, err := svc.GetTfa2(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListTicket", func(t *testing.T) {
		err := svc.ListTicket(ctx)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListUsers", func(t *testing.T) {
		_, err := svc.ListUsers(ctx, nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetUsers", func(t *testing.T) {
		_, err := svc.GetUsers(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListUsersTfa", func(t *testing.T) {
		_, err := svc.ListUsersTfa(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListUsersToken", func(t *testing.T) {
		_, err := svc.ListUsersToken(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetUsersToken", func(t *testing.T) {
		_, err := svc.GetUsersToken(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
}
