// Code generated by cmd/pvegen. DO NOT EDIT.

// Package access exposes typed bindings for the PVE /access endpoint family.
package access

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/fivetwenty-io/pve-apiclient-go/v3/pkg/client"
)

var _ = strings.TrimPrefix
var _ = json.RawMessage(nil)
var _ = url.PathEscape
var _ = sort.Ints
var _ = strconv.Itoa

// Service exposes typed operations on the /access endpoint family.
type Service interface {
	// ListAccess GET /access
	// Directory index.
	ListAccess(ctx context.Context) (*ListAccessResponse, error)
	// ListAcl GET /access/acl
	// Get Access Control List (ACLs).
	ListAcl(ctx context.Context) (*ListAclResponse, error)
	// UpdateAcl PUT /access/acl
	// Update Access Control List (add or remove permissions).
	UpdateAcl(ctx context.Context, params *UpdateAclParams) error
	// ListDomains GET /access/domains
	// Authentication domain index.
	ListDomains(ctx context.Context) (*ListDomainsResponse, error)
	// CreateDomains POST /access/domains
	// Add an authentication server.
	CreateDomains(ctx context.Context, params *CreateDomainsParams) error
	// DeleteDomains DELETE /access/domains/{realm}
	// Delete an authentication server.
	DeleteDomains(ctx context.Context, realm string) error
	// GetDomains GET /access/domains/{realm}
	// Get auth server configuration.
	GetDomains(ctx context.Context, realm string) (*GetDomainsResponse, error)
	// UpdateDomains PUT /access/domains/{realm}
	// Update authentication server settings.
	UpdateDomains(ctx context.Context, realm string, params *UpdateDomainsParams) error
	// CreateDomainsSync POST /access/domains/{realm}/sync
	// Syncs users and/or groups from the configured LDAP to user.cfg. NOTE: Synced groups will have the name 'name-$realm', so make sure those groups do not exist to prevent overwriting.
	CreateDomainsSync(ctx context.Context, realm string, params *CreateDomainsSyncParams) (*CreateDomainsSyncResponse, error)
	// ListGroups GET /access/groups
	// Group index.
	ListGroups(ctx context.Context) (*ListGroupsResponse, error)
	// CreateGroups POST /access/groups
	// Create new group.
	CreateGroups(ctx context.Context, params *CreateGroupsParams) error
	// DeleteGroups DELETE /access/groups/{groupid}
	// Delete group.
	DeleteGroups(ctx context.Context, groupid string) error
	// GetGroups GET /access/groups/{groupid}
	// Get group configuration.
	GetGroups(ctx context.Context, groupid string) (*GetGroupsResponse, error)
	// UpdateGroups PUT /access/groups/{groupid}
	// Update group data.
	UpdateGroups(ctx context.Context, groupid string, params *UpdateGroupsParams) error
	// ListOpenid GET /access/openid
	// Directory index.
	ListOpenid(ctx context.Context) (*ListOpenidResponse, error)
	// CreateOpenidAuthUrl POST /access/openid/auth-url
	// Get the OpenId Authorization Url for the specified realm.
	CreateOpenidAuthUrl(ctx context.Context, params *CreateOpenidAuthUrlParams) (*CreateOpenidAuthUrlResponse, error)
	// CreateOpenidLogin POST /access/openid/login
	// Verify OpenID authorization code and create a ticket.
	CreateOpenidLogin(ctx context.Context, params *CreateOpenidLoginParams) (*CreateOpenidLoginResponse, error)
	// UpdatePassword PUT /access/password
	// Change user password.
	UpdatePassword(ctx context.Context, params *UpdatePasswordParams) error
	// ListPermissions GET /access/permissions
	// Retrieve effective permissions of given user/token.
	ListPermissions(ctx context.Context, params *ListPermissionsParams) (*ListPermissionsResponse, error)
	// ListRoles GET /access/roles
	// Role index.
	ListRoles(ctx context.Context) (*ListRolesResponse, error)
	// CreateRoles POST /access/roles
	// Create new role.
	CreateRoles(ctx context.Context, params *CreateRolesParams) error
	// DeleteRoles DELETE /access/roles/{roleid}
	// Delete role.
	DeleteRoles(ctx context.Context, roleid string) error
	// GetRoles GET /access/roles/{roleid}
	// Get role configuration.
	GetRoles(ctx context.Context, roleid string) (*GetRolesResponse, error)
	// UpdateRoles PUT /access/roles/{roleid}
	// Update an existing role.
	UpdateRoles(ctx context.Context, roleid string, params *UpdateRolesParams) error
	// ListTfa GET /access/tfa
	// List TFA configurations of users.
	ListTfa(ctx context.Context) (*ListTfaResponse, error)
	// GetTfa GET /access/tfa/{userid}
	// List TFA configurations of users.
	GetTfa(ctx context.Context, userid string) (*GetTfaResponse, error)
	// CreateTfa POST /access/tfa/{userid}
	// Add a TFA entry for a user.
	CreateTfa(ctx context.Context, userid string, params *CreateTfaParams) (*CreateTfaResponse, error)
	// DeleteTfa DELETE /access/tfa/{userid}/{id}
	// Delete a TFA entry by ID.
	DeleteTfa(ctx context.Context, userid string, id string, params *DeleteTfaParams) error
	// GetTfa2 GET /access/tfa/{userid}/{id}
	// Fetch a requested TFA entry if present.
	GetTfa2(ctx context.Context, userid string, id string) (*GetTfa2Response, error)
	// UpdateTfa PUT /access/tfa/{userid}/{id}
	// Add a TFA entry for a user.
	UpdateTfa(ctx context.Context, userid string, id string, params *UpdateTfaParams) error
	// ListTicket GET /access/ticket
	// Dummy. Useful for formatters which want to provide a login page.
	ListTicket(ctx context.Context) error
	// CreateTicket POST /access/ticket
	// Create or verify authentication ticket.
	CreateTicket(ctx context.Context, params *CreateTicketParams) (*CreateTicketResponse, error)
	// ListUsers GET /access/users
	// User index.
	ListUsers(ctx context.Context, params *ListUsersParams) (*ListUsersResponse, error)
	// CreateUsers POST /access/users
	// Create new user.
	CreateUsers(ctx context.Context, params *CreateUsersParams) error
	// DeleteUsers DELETE /access/users/{userid}
	// Delete user.
	DeleteUsers(ctx context.Context, userid string) error
	// GetUsers GET /access/users/{userid}
	// Get user configuration.
	GetUsers(ctx context.Context, userid string) (*GetUsersResponse, error)
	// UpdateUsers PUT /access/users/{userid}
	// Update user configuration.
	UpdateUsers(ctx context.Context, userid string, params *UpdateUsersParams) error
	// ListUsersTfa GET /access/users/{userid}/tfa
	// Get user TFA types (Personal and Realm).
	ListUsersTfa(ctx context.Context, userid string, params *ListUsersTfaParams) (*ListUsersTfaResponse, error)
	// ListUsersToken GET /access/users/{userid}/token
	// Get user API tokens.
	ListUsersToken(ctx context.Context, userid string) (*ListUsersTokenResponse, error)
	// DeleteUsersToken DELETE /access/users/{userid}/token/{tokenid}
	// Remove API token for a specific user.
	DeleteUsersToken(ctx context.Context, userid string, tokenid string) error
	// GetUsersToken GET /access/users/{userid}/token/{tokenid}
	// Get specific API token information.
	GetUsersToken(ctx context.Context, userid string, tokenid string) (*GetUsersTokenResponse, error)
	// CreateUsersToken POST /access/users/{userid}/token/{tokenid}
	// Generate a new API token for a specific user. NOTE: returns API token value, which needs to be stored as it cannot be retrieved afterwards!
	CreateUsersToken(ctx context.Context, userid string, tokenid string, params *CreateUsersTokenParams) (*CreateUsersTokenResponse, error)
	// UpdateUsersToken PUT /access/users/{userid}/token/{tokenid}
	// Update API token for a specific user. NOTE: when 'regenerate' is set, the returned token value needs to be stored as it cannot be retrieved afterwards!
	UpdateUsersToken(ctx context.Context, userid string, tokenid string, params *UpdateUsersTokenParams) (*UpdateUsersTokenResponse, error)
	// UpdateUsersUnlockTfa PUT /access/users/{userid}/unlock-tfa
	// Unlock a user's TFA authentication.
	UpdateUsersUnlockTfa(ctx context.Context, userid string) (*UpdateUsersUnlockTfaResponse, error)
	// CreateVncticket POST /access/vncticket
	// verify VNC authentication ticket.
	CreateVncticket(ctx context.Context, params *CreateVncticketParams) error
}

// New constructs a Service backed by the given pkg/client.Client.
// The client owns authentication, TLS, retries, and logging; this
// service only translates between typed Go shapes and the raw client.
func New(c client.Client) Service {
	if c == nil {
		panic("access: New called with nil client")
	}
	return &service{c: c}
}

type service struct {
	c client.Client
}

// ListAccessResponse mirrors the shape returned by GET /access.
type ListAccessResponse []json.RawMessage

// ListAccess implements Service.ListAccess. GET /access.
func (s *service) ListAccess(ctx context.Context) (*ListAccessResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListAccess: ctx must not be nil")
	}
	path := "/access"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListAccess: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListAccess: nil response from client")
	}
	if resp.Data == nil {
		out := ListAccessResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListAccess: re-marshal data: %w", err)
	}
	out := &ListAccessResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListAccess: unmarshal data: %w", err)
	}
	return out, nil
}

// ListAclResponse mirrors the shape returned by GET /access/acl.
type ListAclResponse []json.RawMessage

// ListAcl implements Service.ListAcl. GET /access/acl.
func (s *service) ListAcl(ctx context.Context) (*ListAclResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListAcl: ctx must not be nil")
	}
	path := "/access/acl"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListAcl: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListAcl: nil response from client")
	}
	if resp.Data == nil {
		out := ListAclResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListAcl: re-marshal data: %w", err)
	}
	out := &ListAclResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListAcl: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateAclParams is the request payload for UpdateAcl.
type UpdateAclParams struct {
	// Delete Remove permissions (instead of adding it).
	Delete *bool `json:"delete,omitempty"`
	// Groups List of groups.
	Groups *string `json:"groups,omitempty"`
	// Path Access control path
	Path string `json:"path"`
	// Propagate Allow to propagate (inherit) permissions.
	Propagate *bool `json:"propagate,omitempty"`
	// Roles List of roles.
	Roles string `json:"roles"`
	// Tokens List of API tokens.
	Tokens *string `json:"tokens,omitempty"`
	// Users List of users.
	Users *string `json:"users,omitempty"`
}

// UpdateAcl implements Service.UpdateAcl. PUT /access/acl.
func (s *service) UpdateAcl(ctx context.Context, params *UpdateAclParams) error {
	if ctx == nil {
		return fmt.Errorf("access.UpdateAcl: ctx must not be nil")
	}
	path := "/access/acl"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.UpdateAcl: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return fmt.Errorf("access.UpdateAcl: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.UpdateAcl: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.UpdateAcl: nil response from client")
	}
	_ = resp
	return nil
}

// ListDomainsResponse mirrors the shape returned by GET /access/domains.
type ListDomainsResponse []json.RawMessage

// ListDomains implements Service.ListDomains. GET /access/domains.
func (s *service) ListDomains(ctx context.Context) (*ListDomainsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListDomains: ctx must not be nil")
	}
	path := "/access/domains"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListDomains: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListDomains: nil response from client")
	}
	if resp.Data == nil {
		out := ListDomainsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListDomains: re-marshal data: %w", err)
	}
	out := &ListDomainsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListDomains: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDomainsParams is the request payload for CreateDomains.
type CreateDomainsParams struct {
	// AcrValues Specifies the Authentication Context Class Reference values that theAuthorization Server is being requested to use for the Auth Request.
	AcrValues *string `json:"acr-values,omitempty"`
	// Autocreate Automatically create users if they do not exist.
	Autocreate *bool `json:"autocreate,omitempty"`
	// BaseDn LDAP base domain name
	BaseDn *string `json:"base_dn,omitempty"`
	// BindDn LDAP bind domain name
	BindDn *string `json:"bind_dn,omitempty"`
	// Capath Path to the CA certificate store
	Capath *string `json:"capath,omitempty"`
	// CaseSensitive username is case-sensitive
	CaseSensitive *bool `json:"case-sensitive,omitempty"`
	// Cert Path to the client certificate
	Cert *string `json:"cert,omitempty"`
	// Certkey Path to the client certificate key
	Certkey *string `json:"certkey,omitempty"`
	// CheckConnection Check bind connection to the server.
	CheckConnection *bool `json:"check-connection,omitempty"`
	// ClientId OpenID Client ID
	ClientId *string `json:"client-id,omitempty"`
	// ClientKey OpenID Client Key
	ClientKey *string `json:"client-key,omitempty"`
	// Comment Description.
	Comment *string `json:"comment,omitempty"`
	// Default Use this as default realm
	Default *bool `json:"default,omitempty"`
	// Domain AD domain name
	Domain *string `json:"domain,omitempty"`
	// Filter LDAP filter for user sync.
	Filter *string `json:"filter,omitempty"`
	// GroupClasses The objectclasses for groups.
	GroupClasses *string `json:"group_classes,omitempty"`
	// GroupDn LDAP base domain name for group sync. If not set, the base_dn will be used.
	GroupDn *string `json:"group_dn,omitempty"`
	// GroupFilter LDAP filter for group sync.
	GroupFilter *string `json:"group_filter,omitempty"`
	// GroupNameAttr LDAP attribute representing a groups name. If not set or found, the first value of the DN will be used as name.
	GroupNameAttr *string `json:"group_name_attr,omitempty"`
	// GroupsAutocreate Automatically create groups if they do not exist.
	GroupsAutocreate *bool `json:"groups-autocreate,omitempty"`
	// GroupsClaim OpenID claim used to retrieve groups with.
	GroupsClaim *string `json:"groups-claim,omitempty"`
	// GroupsOverwrite All groups will be overwritten for the user on login.
	GroupsOverwrite *bool `json:"groups-overwrite,omitempty"`
	// IssuerUrl OpenID Issuer Url
	IssuerUrl *string `json:"issuer-url,omitempty"`
	// Mode LDAP protocol mode.
	Mode *string `json:"mode,omitempty"`
	// Password LDAP bind password. Will be stored in '/etc/pve/priv/realm/<REALM>.pw'.
	Password *string `json:"password,omitempty"`
	// Port Server port.
	Port *int64 `json:"port,omitempty"`
	// Prompt Specifies whether the Authorization Server prompts the End-User for reauthentication and consent.
	Prompt *string `json:"prompt,omitempty"`
	// QueryUserinfo Enables querying the userinfo endpoint for claims values.
	QueryUserinfo *bool `json:"query-userinfo,omitempty"`
	// Realm Authentication domain ID
	Realm string `json:"realm"`
	// Scopes Specifies the scopes (user details) that should be authorized and returned, for example 'email' or 'profile'.
	Scopes *string `json:"scopes,omitempty"`
	// Secure Use secure LDAPS protocol. DEPRECATED: use 'mode' instead.
	Secure *bool `json:"secure,omitempty"`
	// Server1 Server IP address (or DNS name)
	Server1 *string `json:"server1,omitempty"`
	// Server2 Fallback Server IP address (or DNS name)
	Server2 *string `json:"server2,omitempty"`
	// Sslversion LDAPS TLS/SSL version. It's not recommended to use version older than 1.2!
	Sslversion *string `json:"sslversion,omitempty"`
	// SyncDefaultsOptions The default options for behavior of synchronizations.
	SyncDefaultsOptions *string `json:"sync-defaults-options,omitempty"`
	// SyncAttributes Comma separated list of key=value pairs for specifying which LDAP attributes map to which PVE user field. For example, to map the LDAP attribute 'mail' to PVEs 'email', write  'email=mail'. By default, each PVE user field is represented  by an LDAP attribute of the same name.
	SyncAttributes *string `json:"sync_attributes,omitempty"`
	// Tfa Use Two-factor authentication.
	Tfa *string `json:"tfa,omitempty"`
	// Type Realm type.
	Type string `json:"type"`
	// UserAttr LDAP user attribute name
	UserAttr *string `json:"user_attr,omitempty"`
	// UserClasses The objectclasses for users.
	UserClasses *string `json:"user_classes,omitempty"`
	// UsernameClaim OpenID claim used to generate the unique username.
	UsernameClaim *string `json:"username-claim,omitempty"`
	// Verify Verify the server's SSL certificate
	Verify *bool `json:"verify,omitempty"`
}

// CreateDomains implements Service.CreateDomains. POST /access/domains.
func (s *service) CreateDomains(ctx context.Context, params *CreateDomainsParams) error {
	if ctx == nil {
		return fmt.Errorf("access.CreateDomains: ctx must not be nil")
	}
	path := "/access/domains"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.CreateDomains: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return fmt.Errorf("access.CreateDomains: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.CreateDomains: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.CreateDomains: nil response from client")
	}
	_ = resp
	return nil
}

// DeleteDomains implements Service.DeleteDomains. DELETE /access/domains/{realm}.
func (s *service) DeleteDomains(ctx context.Context, realm string) error {
	if ctx == nil {
		return fmt.Errorf("access.DeleteDomains: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/domains/%s", url.PathEscape(realm))
	var body map[string]interface{}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.DeleteDomains: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.DeleteDomains: nil response from client")
	}
	_ = resp
	return nil
}

// GetDomainsResponse is the raw JSON returned by GET /access/domains/{realm}.
type GetDomainsResponse = json.RawMessage

// GetDomains implements Service.GetDomains. GET /access/domains/{realm}.
func (s *service) GetDomains(ctx context.Context, realm string) (*GetDomainsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.GetDomains: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/domains/%s", url.PathEscape(realm))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.GetDomains: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.GetDomains: nil response from client")
	}
	if resp.Data == nil {
		out := GetDomainsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.GetDomains: re-marshal data: %w", err)
	}
	out := &GetDomainsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.GetDomains: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateDomainsParams is the request payload for UpdateDomains.
type UpdateDomainsParams struct {
	// AcrValues Specifies the Authentication Context Class Reference values that theAuthorization Server is being requested to use for the Auth Request.
	AcrValues *string `json:"acr-values,omitempty"`
	// Autocreate Automatically create users if they do not exist.
	Autocreate *bool `json:"autocreate,omitempty"`
	// BaseDn LDAP base domain name
	BaseDn *string `json:"base_dn,omitempty"`
	// BindDn LDAP bind domain name
	BindDn *string `json:"bind_dn,omitempty"`
	// Capath Path to the CA certificate store
	Capath *string `json:"capath,omitempty"`
	// CaseSensitive username is case-sensitive
	CaseSensitive *bool `json:"case-sensitive,omitempty"`
	// Cert Path to the client certificate
	Cert *string `json:"cert,omitempty"`
	// Certkey Path to the client certificate key
	Certkey *string `json:"certkey,omitempty"`
	// CheckConnection Check bind connection to the server.
	CheckConnection *bool `json:"check-connection,omitempty"`
	// ClientId OpenID Client ID
	ClientId *string `json:"client-id,omitempty"`
	// ClientKey OpenID Client Key
	ClientKey *string `json:"client-key,omitempty"`
	// Comment Description.
	Comment *string `json:"comment,omitempty"`
	// Default Use this as default realm
	Default *bool `json:"default,omitempty"`
	// Delete A list of settings you want to delete.
	Delete *string `json:"delete,omitempty"`
	// Digest Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Domain AD domain name
	Domain *string `json:"domain,omitempty"`
	// Filter LDAP filter for user sync.
	Filter *string `json:"filter,omitempty"`
	// GroupClasses The objectclasses for groups.
	GroupClasses *string `json:"group_classes,omitempty"`
	// GroupDn LDAP base domain name for group sync. If not set, the base_dn will be used.
	GroupDn *string `json:"group_dn,omitempty"`
	// GroupFilter LDAP filter for group sync.
	GroupFilter *string `json:"group_filter,omitempty"`
	// GroupNameAttr LDAP attribute representing a groups name. If not set or found, the first value of the DN will be used as name.
	GroupNameAttr *string `json:"group_name_attr,omitempty"`
	// GroupsAutocreate Automatically create groups if they do not exist.
	GroupsAutocreate *bool `json:"groups-autocreate,omitempty"`
	// GroupsClaim OpenID claim used to retrieve groups with.
	GroupsClaim *string `json:"groups-claim,omitempty"`
	// GroupsOverwrite All groups will be overwritten for the user on login.
	GroupsOverwrite *bool `json:"groups-overwrite,omitempty"`
	// IssuerUrl OpenID Issuer Url
	IssuerUrl *string `json:"issuer-url,omitempty"`
	// Mode LDAP protocol mode.
	Mode *string `json:"mode,omitempty"`
	// Password LDAP bind password. Will be stored in '/etc/pve/priv/realm/<REALM>.pw'.
	Password *string `json:"password,omitempty"`
	// Port Server port.
	Port *int64 `json:"port,omitempty"`
	// Prompt Specifies whether the Authorization Server prompts the End-User for reauthentication and consent.
	Prompt *string `json:"prompt,omitempty"`
	// QueryUserinfo Enables querying the userinfo endpoint for claims values.
	QueryUserinfo *bool `json:"query-userinfo,omitempty"`
	// Scopes Specifies the scopes (user details) that should be authorized and returned, for example 'email' or 'profile'.
	Scopes *string `json:"scopes,omitempty"`
	// Secure Use secure LDAPS protocol. DEPRECATED: use 'mode' instead.
	Secure *bool `json:"secure,omitempty"`
	// Server1 Server IP address (or DNS name)
	Server1 *string `json:"server1,omitempty"`
	// Server2 Fallback Server IP address (or DNS name)
	Server2 *string `json:"server2,omitempty"`
	// Sslversion LDAPS TLS/SSL version. It's not recommended to use version older than 1.2!
	Sslversion *string `json:"sslversion,omitempty"`
	// SyncDefaultsOptions The default options for behavior of synchronizations.
	SyncDefaultsOptions *string `json:"sync-defaults-options,omitempty"`
	// SyncAttributes Comma separated list of key=value pairs for specifying which LDAP attributes map to which PVE user field. For example, to map the LDAP attribute 'mail' to PVEs 'email', write  'email=mail'. By default, each PVE user field is represented  by an LDAP attribute of the same name.
	SyncAttributes *string `json:"sync_attributes,omitempty"`
	// Tfa Use Two-factor authentication.
	Tfa *string `json:"tfa,omitempty"`
	// UserAttr LDAP user attribute name
	UserAttr *string `json:"user_attr,omitempty"`
	// UserClasses The objectclasses for users.
	UserClasses *string `json:"user_classes,omitempty"`
	// Verify Verify the server's SSL certificate
	Verify *bool `json:"verify,omitempty"`
}

// UpdateDomains implements Service.UpdateDomains. PUT /access/domains/{realm}.
func (s *service) UpdateDomains(ctx context.Context, realm string, params *UpdateDomainsParams) error {
	if ctx == nil {
		return fmt.Errorf("access.UpdateDomains: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/domains/%s", url.PathEscape(realm))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.UpdateDomains: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return fmt.Errorf("access.UpdateDomains: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.UpdateDomains: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.UpdateDomains: nil response from client")
	}
	_ = resp
	return nil
}

// CreateDomainsSyncParams is the request payload for CreateDomainsSync.
type CreateDomainsSyncParams struct {
	// DryRun If set, does not write anything.
	DryRun *bool `json:"dry-run,omitempty"`
	// EnableNew Enable newly synced users immediately.
	EnableNew *bool `json:"enable-new,omitempty"`
	// Full DEPRECATED: use 'remove-vanished' instead. If set, uses the LDAP Directory as source of truth, deleting users or groups not returned from the sync and removing all locally modified properties of synced users. If not set, only syncs information which is present in the synced data, and does not delete or modify anything else.
	Full *bool `json:"full,omitempty"`
	// Purge DEPRECATED: use 'remove-vanished' instead. Remove ACLs for users or groups which were removed from the config during a sync.
	Purge *bool `json:"purge,omitempty"`
	// RemoveVanished A semicolon-separated list of things to remove when they or the user vanishes during a sync. The following values are possible: 'entry' removes the user/group when not returned from the sync. 'properties' removes the set properties on existing user/group that do not appear in the source (even custom ones). 'acl' removes acls when the user/group is not returned from the sync. Instead of a list it also can be 'none' (the default).
	RemoveVanished *string `json:"remove-vanished,omitempty"`
	// Scope Select what to sync.
	Scope *string `json:"scope,omitempty"`
}

// CreateDomainsSyncResponse is the raw JSON returned by POST /access/domains/{realm}/sync.
type CreateDomainsSyncResponse = json.RawMessage

// CreateDomainsSync implements Service.CreateDomainsSync. POST /access/domains/{realm}/sync.
func (s *service) CreateDomainsSync(ctx context.Context, realm string, params *CreateDomainsSyncParams) (*CreateDomainsSyncResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.CreateDomainsSync: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/domains/%s/sync", url.PathEscape(realm))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.CreateDomainsSync: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return nil, fmt.Errorf("access.CreateDomainsSync: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.CreateDomainsSync: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.CreateDomainsSync: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDomainsSyncResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.CreateDomainsSync: re-marshal data: %w", err)
	}
	out := &CreateDomainsSyncResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.CreateDomainsSync: unmarshal data: %w", err)
	}
	return out, nil
}

// ListGroupsResponse mirrors the shape returned by GET /access/groups.
type ListGroupsResponse []json.RawMessage

// ListGroups implements Service.ListGroups. GET /access/groups.
func (s *service) ListGroups(ctx context.Context) (*ListGroupsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListGroups: ctx must not be nil")
	}
	path := "/access/groups"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListGroups: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListGroups: nil response from client")
	}
	if resp.Data == nil {
		out := ListGroupsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListGroups: re-marshal data: %w", err)
	}
	out := &ListGroupsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListGroups: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateGroupsParams is the request payload for CreateGroups.
type CreateGroupsParams struct {
	Comment *string `json:"comment,omitempty"`
	Groupid string  `json:"groupid"`
}

// CreateGroups implements Service.CreateGroups. POST /access/groups.
func (s *service) CreateGroups(ctx context.Context, params *CreateGroupsParams) error {
	if ctx == nil {
		return fmt.Errorf("access.CreateGroups: ctx must not be nil")
	}
	path := "/access/groups"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.CreateGroups: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return fmt.Errorf("access.CreateGroups: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.CreateGroups: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.CreateGroups: nil response from client")
	}
	_ = resp
	return nil
}

// DeleteGroups implements Service.DeleteGroups. DELETE /access/groups/{groupid}.
func (s *service) DeleteGroups(ctx context.Context, groupid string) error {
	if ctx == nil {
		return fmt.Errorf("access.DeleteGroups: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/groups/%s", url.PathEscape(groupid))
	var body map[string]interface{}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.DeleteGroups: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.DeleteGroups: nil response from client")
	}
	_ = resp
	return nil
}

// GetGroupsResponse mirrors the shape returned by GET /access/groups/{groupid}.
type GetGroupsResponse struct {
	Comment *string  `json:"comment,omitempty"`
	Members []string `json:"members"`
}

// GetGroups implements Service.GetGroups. GET /access/groups/{groupid}.
func (s *service) GetGroups(ctx context.Context, groupid string) (*GetGroupsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.GetGroups: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/groups/%s", url.PathEscape(groupid))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.GetGroups: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.GetGroups: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.GetGroups: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.GetGroups: re-marshal data: %w", err)
	}
	out := &GetGroupsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.GetGroups: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateGroupsParams is the request payload for UpdateGroups.
type UpdateGroupsParams struct {
	Comment *string `json:"comment,omitempty"`
}

// UpdateGroups implements Service.UpdateGroups. PUT /access/groups/{groupid}.
func (s *service) UpdateGroups(ctx context.Context, groupid string, params *UpdateGroupsParams) error {
	if ctx == nil {
		return fmt.Errorf("access.UpdateGroups: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/groups/%s", url.PathEscape(groupid))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.UpdateGroups: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return fmt.Errorf("access.UpdateGroups: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.UpdateGroups: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.UpdateGroups: nil response from client")
	}
	_ = resp
	return nil
}

// ListOpenidResponse mirrors the shape returned by GET /access/openid.
type ListOpenidResponse []json.RawMessage

// ListOpenid implements Service.ListOpenid. GET /access/openid.
func (s *service) ListOpenid(ctx context.Context) (*ListOpenidResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListOpenid: ctx must not be nil")
	}
	path := "/access/openid"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListOpenid: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListOpenid: nil response from client")
	}
	if resp.Data == nil {
		out := ListOpenidResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListOpenid: re-marshal data: %w", err)
	}
	out := &ListOpenidResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListOpenid: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateOpenidAuthUrlParams is the request payload for CreateOpenidAuthUrl.
type CreateOpenidAuthUrlParams struct {
	// Realm Authentication domain ID
	Realm string `json:"realm"`
	// RedirectUrl Redirection Url. The client should set this to the used server url (location.origin).
	RedirectUrl string `json:"redirect-url"`
}

// CreateOpenidAuthUrlResponse is the raw JSON returned by POST /access/openid/auth-url.
type CreateOpenidAuthUrlResponse = json.RawMessage

// CreateOpenidAuthUrl implements Service.CreateOpenidAuthUrl. POST /access/openid/auth-url.
func (s *service) CreateOpenidAuthUrl(ctx context.Context, params *CreateOpenidAuthUrlParams) (*CreateOpenidAuthUrlResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.CreateOpenidAuthUrl: ctx must not be nil")
	}
	path := "/access/openid/auth-url"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.CreateOpenidAuthUrl: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return nil, fmt.Errorf("access.CreateOpenidAuthUrl: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.CreateOpenidAuthUrl: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.CreateOpenidAuthUrl: nil response from client")
	}
	if resp.Data == nil {
		out := CreateOpenidAuthUrlResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.CreateOpenidAuthUrl: re-marshal data: %w", err)
	}
	out := &CreateOpenidAuthUrlResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.CreateOpenidAuthUrl: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateOpenidLoginParams is the request payload for CreateOpenidLogin.
type CreateOpenidLoginParams struct {
	// Code OpenId authorization code.
	Code string `json:"code"`
	// RedirectUrl Redirection Url. The client should set this to the used server url (location.origin).
	RedirectUrl string `json:"redirect-url"`
	// State OpenId state.
	State string `json:"state"`
}

// CreateOpenidLoginResponse is the raw JSON returned by POST /access/openid/login.
type CreateOpenidLoginResponse = json.RawMessage

// CreateOpenidLogin implements Service.CreateOpenidLogin. POST /access/openid/login.
func (s *service) CreateOpenidLogin(ctx context.Context, params *CreateOpenidLoginParams) (*CreateOpenidLoginResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.CreateOpenidLogin: ctx must not be nil")
	}
	path := "/access/openid/login"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.CreateOpenidLogin: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return nil, fmt.Errorf("access.CreateOpenidLogin: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.CreateOpenidLogin: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.CreateOpenidLogin: nil response from client")
	}
	if resp.Data == nil {
		out := CreateOpenidLoginResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.CreateOpenidLogin: re-marshal data: %w", err)
	}
	out := &CreateOpenidLoginResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.CreateOpenidLogin: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdatePasswordParams is the request payload for UpdatePassword.
type UpdatePasswordParams struct {
	// ConfirmationPassword The current password of the user performing the change.
	ConfirmationPassword *string `json:"confirmation-password,omitempty"`
	// Password The new password.
	Password string `json:"password"`
	// Userid Full User ID, in the `name@realm` format.
	Userid string `json:"userid"`
}

// UpdatePassword implements Service.UpdatePassword. PUT /access/password.
func (s *service) UpdatePassword(ctx context.Context, params *UpdatePasswordParams) error {
	if ctx == nil {
		return fmt.Errorf("access.UpdatePassword: ctx must not be nil")
	}
	path := "/access/password"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.UpdatePassword: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return fmt.Errorf("access.UpdatePassword: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.UpdatePassword: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.UpdatePassword: nil response from client")
	}
	_ = resp
	return nil
}

// ListPermissionsParams is the request payload for ListPermissions.
type ListPermissionsParams struct {
	// Path Only dump this specific path, not the whole tree.
	Path *string `json:"path,omitempty"`
	// Userid User ID or full API token ID
	Userid *string `json:"userid,omitempty"`
}

// ListPermissionsResponse is the raw JSON returned by GET /access/permissions.
type ListPermissionsResponse = json.RawMessage

// ListPermissions implements Service.ListPermissions. GET /access/permissions.
func (s *service) ListPermissions(ctx context.Context, params *ListPermissionsParams) (*ListPermissionsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListPermissions: ctx must not be nil")
	}
	path := "/access/permissions"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.ListPermissions: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return nil, fmt.Errorf("access.ListPermissions: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListPermissions: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListPermissions: nil response from client")
	}
	if resp.Data == nil {
		out := ListPermissionsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListPermissions: re-marshal data: %w", err)
	}
	out := &ListPermissionsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListPermissions: unmarshal data: %w", err)
	}
	return out, nil
}

// ListRolesResponse mirrors the shape returned by GET /access/roles.
type ListRolesResponse []json.RawMessage

// ListRoles implements Service.ListRoles. GET /access/roles.
func (s *service) ListRoles(ctx context.Context) (*ListRolesResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListRoles: ctx must not be nil")
	}
	path := "/access/roles"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListRoles: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListRoles: nil response from client")
	}
	if resp.Data == nil {
		out := ListRolesResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListRoles: re-marshal data: %w", err)
	}
	out := &ListRolesResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListRoles: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateRolesParams is the request payload for CreateRoles.
type CreateRolesParams struct {
	Privs  *string `json:"privs,omitempty"`
	Roleid string  `json:"roleid"`
}

// CreateRoles implements Service.CreateRoles. POST /access/roles.
func (s *service) CreateRoles(ctx context.Context, params *CreateRolesParams) error {
	if ctx == nil {
		return fmt.Errorf("access.CreateRoles: ctx must not be nil")
	}
	path := "/access/roles"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.CreateRoles: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return fmt.Errorf("access.CreateRoles: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.CreateRoles: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.CreateRoles: nil response from client")
	}
	_ = resp
	return nil
}

// DeleteRoles implements Service.DeleteRoles. DELETE /access/roles/{roleid}.
func (s *service) DeleteRoles(ctx context.Context, roleid string) error {
	if ctx == nil {
		return fmt.Errorf("access.DeleteRoles: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/roles/%s", url.PathEscape(roleid))
	var body map[string]interface{}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.DeleteRoles: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.DeleteRoles: nil response from client")
	}
	_ = resp
	return nil
}

// GetRolesResponse mirrors the shape returned by GET /access/roles/{roleid}.
type GetRolesResponse struct {
	DatastoreAllocate          *bool `json:"Datastore.Allocate,omitempty"`
	DatastoreAllocateSpace     *bool `json:"Datastore.AllocateSpace,omitempty"`
	DatastoreAllocateTemplate  *bool `json:"Datastore.AllocateTemplate,omitempty"`
	DatastoreAudit             *bool `json:"Datastore.Audit,omitempty"`
	GroupAllocate              *bool `json:"Group.Allocate,omitempty"`
	MappingAudit               *bool `json:"Mapping.Audit,omitempty"`
	MappingModify              *bool `json:"Mapping.Modify,omitempty"`
	MappingUse                 *bool `json:"Mapping.Use,omitempty"`
	PermissionsModify          *bool `json:"Permissions.Modify,omitempty"`
	PoolAllocate               *bool `json:"Pool.Allocate,omitempty"`
	PoolAudit                  *bool `json:"Pool.Audit,omitempty"`
	RealmAllocate              *bool `json:"Realm.Allocate,omitempty"`
	RealmAllocateUser          *bool `json:"Realm.AllocateUser,omitempty"`
	SDNAllocate                *bool `json:"SDN.Allocate,omitempty"`
	SDNAudit                   *bool `json:"SDN.Audit,omitempty"`
	SDNUse                     *bool `json:"SDN.Use,omitempty"`
	SysAccessNetwork           *bool `json:"Sys.AccessNetwork,omitempty"`
	SysAudit                   *bool `json:"Sys.Audit,omitempty"`
	SysConsole                 *bool `json:"Sys.Console,omitempty"`
	SysIncoming                *bool `json:"Sys.Incoming,omitempty"`
	SysModify                  *bool `json:"Sys.Modify,omitempty"`
	SysPowerMgmt               *bool `json:"Sys.PowerMgmt,omitempty"`
	SysSyslog                  *bool `json:"Sys.Syslog,omitempty"`
	UserModify                 *bool `json:"User.Modify,omitempty"`
	VMAllocate                 *bool `json:"VM.Allocate,omitempty"`
	VMAudit                    *bool `json:"VM.Audit,omitempty"`
	VMBackup                   *bool `json:"VM.Backup,omitempty"`
	VMClone                    *bool `json:"VM.Clone,omitempty"`
	VMConfigCDROM              *bool `json:"VM.Config.CDROM,omitempty"`
	VMConfigCPU                *bool `json:"VM.Config.CPU,omitempty"`
	VMConfigCloudinit          *bool `json:"VM.Config.Cloudinit,omitempty"`
	VMConfigDisk               *bool `json:"VM.Config.Disk,omitempty"`
	VMConfigHWType             *bool `json:"VM.Config.HWType,omitempty"`
	VMConfigMemory             *bool `json:"VM.Config.Memory,omitempty"`
	VMConfigNetwork            *bool `json:"VM.Config.Network,omitempty"`
	VMConfigOptions            *bool `json:"VM.Config.Options,omitempty"`
	VMConsole                  *bool `json:"VM.Console,omitempty"`
	VMGuestAgentAudit          *bool `json:"VM.GuestAgent.Audit,omitempty"`
	VMGuestAgentFileRead       *bool `json:"VM.GuestAgent.FileRead,omitempty"`
	VMGuestAgentFileSystemMgmt *bool `json:"VM.GuestAgent.FileSystemMgmt,omitempty"`
	VMGuestAgentFileWrite      *bool `json:"VM.GuestAgent.FileWrite,omitempty"`
	VMGuestAgentUnrestricted   *bool `json:"VM.GuestAgent.Unrestricted,omitempty"`
	VMMigrate                  *bool `json:"VM.Migrate,omitempty"`
	VMPowerMgmt                *bool `json:"VM.PowerMgmt,omitempty"`
	VMReplicate                *bool `json:"VM.Replicate,omitempty"`
	VMSnapshot                 *bool `json:"VM.Snapshot,omitempty"`
	VMSnapshotRollback         *bool `json:"VM.Snapshot.Rollback,omitempty"`
}

// GetRoles implements Service.GetRoles. GET /access/roles/{roleid}.
func (s *service) GetRoles(ctx context.Context, roleid string) (*GetRolesResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.GetRoles: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/roles/%s", url.PathEscape(roleid))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.GetRoles: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.GetRoles: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.GetRoles: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.GetRoles: re-marshal data: %w", err)
	}
	out := &GetRolesResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.GetRoles: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateRolesParams is the request payload for UpdateRoles.
type UpdateRolesParams struct {
	Append *bool   `json:"append,omitempty"`
	Privs  *string `json:"privs,omitempty"`
}

// UpdateRoles implements Service.UpdateRoles. PUT /access/roles/{roleid}.
func (s *service) UpdateRoles(ctx context.Context, roleid string, params *UpdateRolesParams) error {
	if ctx == nil {
		return fmt.Errorf("access.UpdateRoles: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/roles/%s", url.PathEscape(roleid))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.UpdateRoles: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return fmt.Errorf("access.UpdateRoles: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.UpdateRoles: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.UpdateRoles: nil response from client")
	}
	_ = resp
	return nil
}

// ListTfaResponse mirrors the shape returned by GET /access/tfa.
type ListTfaResponse []json.RawMessage

// ListTfa implements Service.ListTfa. GET /access/tfa.
func (s *service) ListTfa(ctx context.Context) (*ListTfaResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListTfa: ctx must not be nil")
	}
	path := "/access/tfa"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListTfa: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListTfa: nil response from client")
	}
	if resp.Data == nil {
		out := ListTfaResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListTfa: re-marshal data: %w", err)
	}
	out := &ListTfaResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListTfa: unmarshal data: %w", err)
	}
	return out, nil
}

// GetTfaResponse mirrors the shape returned by GET /access/tfa/{userid}.
type GetTfaResponse []json.RawMessage

// GetTfa implements Service.GetTfa. GET /access/tfa/{userid}.
func (s *service) GetTfa(ctx context.Context, userid string) (*GetTfaResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.GetTfa: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/tfa/%s", url.PathEscape(userid))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.GetTfa: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.GetTfa: nil response from client")
	}
	if resp.Data == nil {
		out := GetTfaResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.GetTfa: re-marshal data: %w", err)
	}
	out := &GetTfaResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.GetTfa: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateTfaParams is the request payload for CreateTfa.
type CreateTfaParams struct {
	// Challenge When responding to a u2f challenge: the original challenge string
	Challenge *string `json:"challenge,omitempty"`
	// Description A description to distinguish multiple entries from one another
	Description *string `json:"description,omitempty"`
	// Password The current password of the user performing the change.
	Password *string `json:"password,omitempty"`
	// Totp A totp URI.
	Totp *string `json:"totp,omitempty"`
	// Type TFA Entry Type.
	Type string `json:"type"`
	// Value The current value for the provided totp URI, or a Webauthn/U2F challenge response
	Value *string `json:"value,omitempty"`
}

// CreateTfaResponse mirrors the shape returned by POST /access/tfa/{userid}.
type CreateTfaResponse struct {
	// Challenge When adding u2f entries, this contains a challenge the user must respond to in order to finish the registration.
	Challenge *string `json:"challenge,omitempty"`
	// Id The id of a newly added TFA entry.
	Id string `json:"id"`
	// Recovery When adding recovery codes, this contains the list of codes to be displayed to the user
	Recovery []string `json:"recovery,omitempty"`
}

// CreateTfa implements Service.CreateTfa. POST /access/tfa/{userid}.
func (s *service) CreateTfa(ctx context.Context, userid string, params *CreateTfaParams) (*CreateTfaResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.CreateTfa: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/tfa/%s", url.PathEscape(userid))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.CreateTfa: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return nil, fmt.Errorf("access.CreateTfa: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.CreateTfa: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.CreateTfa: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.CreateTfa: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.CreateTfa: re-marshal data: %w", err)
	}
	out := &CreateTfaResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.CreateTfa: unmarshal data: %w", err)
	}
	return out, nil
}

// DeleteTfaParams is the request payload for DeleteTfa.
type DeleteTfaParams struct {
	// Password The current password of the user performing the change.
	Password *string `json:"password,omitempty"`
}

// DeleteTfa implements Service.DeleteTfa. DELETE /access/tfa/{userid}/{id}.
func (s *service) DeleteTfa(ctx context.Context, userid string, id string, params *DeleteTfaParams) error {
	if ctx == nil {
		return fmt.Errorf("access.DeleteTfa: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/tfa/%s/%s", url.PathEscape(userid), url.PathEscape(id))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.DeleteTfa: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return fmt.Errorf("access.DeleteTfa: decode params: %w", err)
		}
	}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.DeleteTfa: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.DeleteTfa: nil response from client")
	}
	_ = resp
	return nil
}

// GetTfa2Response mirrors the shape returned by GET /access/tfa/{userid}/{id}.
type GetTfa2Response struct {
	// Created Creation time of this entry as unix epoch.
	Created int64 `json:"created"`
	// Description User chosen description for this entry.
	Description string `json:"description"`
	// Enable Whether this TFA entry is currently enabled.
	Enable *bool `json:"enable,omitempty"`
	// Id The id used to reference this entry.
	Id string `json:"id"`
	// Type TFA Entry Type.
	Type string `json:"type"`
}

// GetTfa2 implements Service.GetTfa2. GET /access/tfa/{userid}/{id}.
func (s *service) GetTfa2(ctx context.Context, userid string, id string) (*GetTfa2Response, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.GetTfa2: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/tfa/%s/%s", url.PathEscape(userid), url.PathEscape(id))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.GetTfa2: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.GetTfa2: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.GetTfa2: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.GetTfa2: re-marshal data: %w", err)
	}
	out := &GetTfa2Response{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.GetTfa2: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateTfaParams is the request payload for UpdateTfa.
type UpdateTfaParams struct {
	// Description A description to distinguish multiple entries from one another
	Description *string `json:"description,omitempty"`
	// Enable Whether the entry should be enabled for login.
	Enable *bool `json:"enable,omitempty"`
	// Password The current password of the user performing the change.
	Password *string `json:"password,omitempty"`
}

// UpdateTfa implements Service.UpdateTfa. PUT /access/tfa/{userid}/{id}.
func (s *service) UpdateTfa(ctx context.Context, userid string, id string, params *UpdateTfaParams) error {
	if ctx == nil {
		return fmt.Errorf("access.UpdateTfa: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/tfa/%s/%s", url.PathEscape(userid), url.PathEscape(id))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.UpdateTfa: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return fmt.Errorf("access.UpdateTfa: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.UpdateTfa: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.UpdateTfa: nil response from client")
	}
	_ = resp
	return nil
}

// ListTicket implements Service.ListTicket. GET /access/ticket.
func (s *service) ListTicket(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("access.ListTicket: ctx must not be nil")
	}
	path := "/access/ticket"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.ListTicket: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.ListTicket: nil response from client")
	}
	_ = resp
	return nil
}

// CreateTicketParams is the request payload for CreateTicket.
type CreateTicketParams struct {
	// NewFormat This parameter is now ignored and assumed to be 1.
	NewFormat *bool `json:"new-format,omitempty"`
	// Otp One-time password for Two-factor authentication.
	Otp *string `json:"otp,omitempty"`
	// Password The secret password. This can also be a valid ticket.
	Password string `json:"password"`
	// Path Verify ticket, and check if user have access 'privs' on 'path'
	Path *string `json:"path,omitempty"`
	// Privs Verify ticket, and check if user have access 'privs' on 'path'
	Privs *string `json:"privs,omitempty"`
	// Realm You can optionally pass the realm using this parameter. Normally the realm is simply added to the username <username>@<realm>.
	Realm *string `json:"realm,omitempty"`
	// TfaChallenge The signed TFA challenge string the user wants to respond to.
	TfaChallenge *string `json:"tfa-challenge,omitempty"`
	// Username User name
	Username string `json:"username"`
}

// CreateTicketResponse mirrors the shape returned by POST /access/ticket.
type CreateTicketResponse struct {
	CSRFPreventionToken *string `json:"CSRFPreventionToken,omitempty"`
	Clustername         *string `json:"clustername,omitempty"`
	Ticket              *string `json:"ticket,omitempty"`
	Username            string  `json:"username"`
}

// CreateTicket implements Service.CreateTicket. POST /access/ticket.
func (s *service) CreateTicket(ctx context.Context, params *CreateTicketParams) (*CreateTicketResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.CreateTicket: ctx must not be nil")
	}
	path := "/access/ticket"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.CreateTicket: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return nil, fmt.Errorf("access.CreateTicket: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.CreateTicket: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.CreateTicket: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.CreateTicket: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.CreateTicket: re-marshal data: %w", err)
	}
	out := &CreateTicketResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.CreateTicket: unmarshal data: %w", err)
	}
	return out, nil
}

// ListUsersParams is the request payload for ListUsers.
type ListUsersParams struct {
	// Enabled Optional filter for enable property.
	Enabled *bool `json:"enabled,omitempty"`
	// Full Include group and token information.
	Full *bool `json:"full,omitempty"`
}

// ListUsersResponse mirrors the shape returned by GET /access/users.
type ListUsersResponse []json.RawMessage

// ListUsers implements Service.ListUsers. GET /access/users.
func (s *service) ListUsers(ctx context.Context, params *ListUsersParams) (*ListUsersResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListUsers: ctx must not be nil")
	}
	path := "/access/users"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.ListUsers: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return nil, fmt.Errorf("access.ListUsers: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListUsers: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListUsers: nil response from client")
	}
	if resp.Data == nil {
		out := ListUsersResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListUsers: re-marshal data: %w", err)
	}
	out := &ListUsersResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListUsers: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateUsersParams is the request payload for CreateUsers.
type CreateUsersParams struct {
	Comment *string `json:"comment,omitempty"`
	Email   *string `json:"email,omitempty"`
	// Enable Enable the account (default). You can set this to '0' to disable the account
	Enable *bool `json:"enable,omitempty"`
	// Expire Account expiration date (seconds since epoch). '0' means no expiration date.
	Expire    *int64  `json:"expire,omitempty"`
	Firstname *string `json:"firstname,omitempty"`
	Groups    *string `json:"groups,omitempty"`
	// Keys Keys for two factor auth (yubico).
	Keys     *string `json:"keys,omitempty"`
	Lastname *string `json:"lastname,omitempty"`
	// Password Initial password.
	Password *string `json:"password,omitempty"`
	// Userid Full User ID, in the `name@realm` format.
	Userid string `json:"userid"`
}

// CreateUsers implements Service.CreateUsers. POST /access/users.
func (s *service) CreateUsers(ctx context.Context, params *CreateUsersParams) error {
	if ctx == nil {
		return fmt.Errorf("access.CreateUsers: ctx must not be nil")
	}
	path := "/access/users"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.CreateUsers: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return fmt.Errorf("access.CreateUsers: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.CreateUsers: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.CreateUsers: nil response from client")
	}
	_ = resp
	return nil
}

// DeleteUsers implements Service.DeleteUsers. DELETE /access/users/{userid}.
func (s *service) DeleteUsers(ctx context.Context, userid string) error {
	if ctx == nil {
		return fmt.Errorf("access.DeleteUsers: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s", url.PathEscape(userid))
	var body map[string]interface{}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.DeleteUsers: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.DeleteUsers: nil response from client")
	}
	_ = resp
	return nil
}

// GetUsersResponse mirrors the shape returned by GET /access/users/{userid}.
type GetUsersResponse struct {
	Comment *string `json:"comment,omitempty"`
	Email   *string `json:"email,omitempty"`
	// Enable Enable the account (default). You can set this to '0' to disable the account
	Enable *bool `json:"enable,omitempty"`
	// Expire Account expiration date (seconds since epoch). '0' means no expiration date.
	Expire    *int64   `json:"expire,omitempty"`
	Firstname *string  `json:"firstname,omitempty"`
	Groups    []string `json:"groups,omitempty"`
	// Keys Keys for two factor auth (yubico).
	Keys     *string         `json:"keys,omitempty"`
	Lastname *string         `json:"lastname,omitempty"`
	Tokens   json.RawMessage `json:"tokens,omitempty"`
}

// GetUsers implements Service.GetUsers. GET /access/users/{userid}.
func (s *service) GetUsers(ctx context.Context, userid string) (*GetUsersResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.GetUsers: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s", url.PathEscape(userid))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.GetUsers: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.GetUsers: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.GetUsers: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.GetUsers: re-marshal data: %w", err)
	}
	out := &GetUsersResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.GetUsers: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateUsersParams is the request payload for UpdateUsers.
type UpdateUsersParams struct {
	Append  *bool   `json:"append,omitempty"`
	Comment *string `json:"comment,omitempty"`
	Email   *string `json:"email,omitempty"`
	// Enable Enable the account (default). You can set this to '0' to disable the account
	Enable *bool `json:"enable,omitempty"`
	// Expire Account expiration date (seconds since epoch). '0' means no expiration date.
	Expire    *int64  `json:"expire,omitempty"`
	Firstname *string `json:"firstname,omitempty"`
	Groups    *string `json:"groups,omitempty"`
	// Keys Keys for two factor auth (yubico).
	Keys     *string `json:"keys,omitempty"`
	Lastname *string `json:"lastname,omitempty"`
}

// UpdateUsers implements Service.UpdateUsers. PUT /access/users/{userid}.
func (s *service) UpdateUsers(ctx context.Context, userid string, params *UpdateUsersParams) error {
	if ctx == nil {
		return fmt.Errorf("access.UpdateUsers: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s", url.PathEscape(userid))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.UpdateUsers: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return fmt.Errorf("access.UpdateUsers: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.UpdateUsers: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.UpdateUsers: nil response from client")
	}
	_ = resp
	return nil
}

// ListUsersTfaParams is the request payload for ListUsersTfa.
type ListUsersTfaParams struct {
	// Multiple Request all entries as an array.
	Multiple *bool `json:"multiple,omitempty"`
}

// ListUsersTfaResponse mirrors the shape returned by GET /access/users/{userid}/tfa.
type ListUsersTfaResponse struct {
	// Realm The type of TFA the users realm has set, if any.
	Realm *string `json:"realm,omitempty"`
	// Types Array of the user configured TFA types, if any. Only available if 'multiple' was not passed.
	Types []string `json:"types,omitempty"`
	// User The type of TFA the user has set, if any. Only set if 'multiple' was not passed.
	User *string `json:"user,omitempty"`
}

// ListUsersTfa implements Service.ListUsersTfa. GET /access/users/{userid}/tfa.
func (s *service) ListUsersTfa(ctx context.Context, userid string, params *ListUsersTfaParams) (*ListUsersTfaResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListUsersTfa: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s/tfa", url.PathEscape(userid))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.ListUsersTfa: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return nil, fmt.Errorf("access.ListUsersTfa: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListUsersTfa: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListUsersTfa: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.ListUsersTfa: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListUsersTfa: re-marshal data: %w", err)
	}
	out := &ListUsersTfaResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListUsersTfa: unmarshal data: %w", err)
	}
	return out, nil
}

// ListUsersTokenResponse mirrors the shape returned by GET /access/users/{userid}/token.
type ListUsersTokenResponse []json.RawMessage

// ListUsersToken implements Service.ListUsersToken. GET /access/users/{userid}/token.
func (s *service) ListUsersToken(ctx context.Context, userid string) (*ListUsersTokenResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListUsersToken: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s/token", url.PathEscape(userid))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListUsersToken: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListUsersToken: nil response from client")
	}
	if resp.Data == nil {
		out := ListUsersTokenResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListUsersToken: re-marshal data: %w", err)
	}
	out := &ListUsersTokenResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListUsersToken: unmarshal data: %w", err)
	}
	return out, nil
}

// DeleteUsersToken implements Service.DeleteUsersToken. DELETE /access/users/{userid}/token/{tokenid}.
func (s *service) DeleteUsersToken(ctx context.Context, userid string, tokenid string) error {
	if ctx == nil {
		return fmt.Errorf("access.DeleteUsersToken: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s/token/%s", url.PathEscape(userid), url.PathEscape(tokenid))
	var body map[string]interface{}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.DeleteUsersToken: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.DeleteUsersToken: nil response from client")
	}
	_ = resp
	return nil
}

// GetUsersTokenResponse mirrors the shape returned by GET /access/users/{userid}/token/{tokenid}.
type GetUsersTokenResponse struct {
	Comment *string `json:"comment,omitempty"`
	// Expire API token expiration date (seconds since epoch). '0' means no expiration date.
	Expire *int64 `json:"expire,omitempty"`
	// Privsep Restrict API token privileges with separate ACLs (default), or give full privileges of corresponding user.
	Privsep *bool `json:"privsep,omitempty"`
}

// GetUsersToken implements Service.GetUsersToken. GET /access/users/{userid}/token/{tokenid}.
func (s *service) GetUsersToken(ctx context.Context, userid string, tokenid string) (*GetUsersTokenResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.GetUsersToken: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s/token/%s", url.PathEscape(userid), url.PathEscape(tokenid))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.GetUsersToken: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.GetUsersToken: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.GetUsersToken: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.GetUsersToken: re-marshal data: %w", err)
	}
	out := &GetUsersTokenResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.GetUsersToken: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateUsersTokenParams is the request payload for CreateUsersToken.
type CreateUsersTokenParams struct {
	Comment *string `json:"comment,omitempty"`
	// Expire API token expiration date (seconds since epoch). '0' means no expiration date.
	Expire *int64 `json:"expire,omitempty"`
	// Privsep Restrict API token privileges with separate ACLs (default), or give full privileges of corresponding user.
	Privsep *bool `json:"privsep,omitempty"`
}

// CreateUsersTokenResponse mirrors the shape returned by POST /access/users/{userid}/token/{tokenid}.
type CreateUsersTokenResponse struct {
	// FullTokenid The full token id.
	FullTokenid string          `json:"full-tokenid"`
	Info        json.RawMessage `json:"info"`
	// Value API token value used for authentication.
	Value string `json:"value"`
}

// CreateUsersToken implements Service.CreateUsersToken. POST /access/users/{userid}/token/{tokenid}.
func (s *service) CreateUsersToken(ctx context.Context, userid string, tokenid string, params *CreateUsersTokenParams) (*CreateUsersTokenResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.CreateUsersToken: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s/token/%s", url.PathEscape(userid), url.PathEscape(tokenid))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.CreateUsersToken: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return nil, fmt.Errorf("access.CreateUsersToken: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.CreateUsersToken: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.CreateUsersToken: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.CreateUsersToken: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.CreateUsersToken: re-marshal data: %w", err)
	}
	out := &CreateUsersTokenResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.CreateUsersToken: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateUsersTokenParams is the request payload for UpdateUsersToken.
type UpdateUsersTokenParams struct {
	Comment *string `json:"comment,omitempty"`
	// Delete A list of settings you want to delete.
	Delete *string `json:"delete,omitempty"`
	// Expire API token expiration date (seconds since epoch). '0' means no expiration date.
	Expire *int64 `json:"expire,omitempty"`
	// Privsep Restrict API token privileges with separate ACLs (default), or give full privileges of corresponding user.
	Privsep *bool `json:"privsep,omitempty"`
	// Regenerate Regenerate the token's secret value. All users of the previous secret will lose access after this operation.
	Regenerate *bool `json:"regenerate,omitempty"`
}

// UpdateUsersTokenResponse mirrors the shape returned by PUT /access/users/{userid}/token/{tokenid}.
type UpdateUsersTokenResponse struct {
	Comment *string `json:"comment,omitempty"`
	// Expire API token expiration date (seconds since epoch). '0' means no expiration date.
	Expire *int64 `json:"expire,omitempty"`
	// FullTokenid The full token id. Only set when 'regenerate' was set.
	FullTokenid *string `json:"full-tokenid,omitempty"`
	// Privsep Restrict API token privileges with separate ACLs (default), or give full privileges of corresponding user.
	Privsep *bool `json:"privsep,omitempty"`
	// Value API token value used for authentication. Only set when 'regenerate' was set.
	Value *string `json:"value,omitempty"`
}

// UpdateUsersToken implements Service.UpdateUsersToken. PUT /access/users/{userid}/token/{tokenid}.
func (s *service) UpdateUsersToken(ctx context.Context, userid string, tokenid string, params *UpdateUsersTokenParams) (*UpdateUsersTokenResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.UpdateUsersToken: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s/token/%s", url.PathEscape(userid), url.PathEscape(tokenid))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.UpdateUsersToken: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return nil, fmt.Errorf("access.UpdateUsersToken: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.UpdateUsersToken: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.UpdateUsersToken: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.UpdateUsersToken: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.UpdateUsersToken: re-marshal data: %w", err)
	}
	out := &UpdateUsersTokenResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.UpdateUsersToken: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateUsersUnlockTfaResponse is the raw JSON returned by PUT /access/users/{userid}/unlock-tfa.
type UpdateUsersUnlockTfaResponse = json.RawMessage

// UpdateUsersUnlockTfa implements Service.UpdateUsersUnlockTfa. PUT /access/users/{userid}/unlock-tfa.
func (s *service) UpdateUsersUnlockTfa(ctx context.Context, userid string) (*UpdateUsersUnlockTfaResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.UpdateUsersUnlockTfa: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s/unlock-tfa", url.PathEscape(userid))
	var body map[string]interface{}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.UpdateUsersUnlockTfa: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.UpdateUsersUnlockTfa: nil response from client")
	}
	if resp.Data == nil {
		out := UpdateUsersUnlockTfaResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.UpdateUsersUnlockTfa: re-marshal data: %w", err)
	}
	out := &UpdateUsersUnlockTfaResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.UpdateUsersUnlockTfa: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateVncticketParams is the request payload for CreateVncticket.
type CreateVncticketParams struct {
	// Authid UserId or token
	Authid string `json:"authid"`
	// Path Verify ticket, and check if user have access 'privs' on 'path'
	Path string `json:"path"`
	// Port Verify that the ticket is valid for this port.
	Port *int64 `json:"port,omitempty"`
	// Privs Verify ticket, and check if user have access 'privs' on 'path'
	Privs string `json:"privs"`
	// Vncticket The VNC ticket.
	Vncticket string `json:"vncticket"`
}

// CreateVncticket implements Service.CreateVncticket. POST /access/vncticket.
func (s *service) CreateVncticket(ctx context.Context, params *CreateVncticketParams) error {
	if ctx == nil {
		return fmt.Errorf("access.CreateVncticket: ctx must not be nil")
	}
	path := "/access/vncticket"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.CreateVncticket: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return fmt.Errorf("access.CreateVncticket: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.CreateVncticket: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.CreateVncticket: nil response from client")
	}
	_ = resp
	return nil
}
