// Code generated by cmd/pvegen. DO NOT EDIT.

// Package autoinstall exposes typed bindings for the PVE /auto-install endpoint family.
package autoinstall

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
)

var _ = strings.TrimPrefix
var _ = json.RawMessage(nil)
var _ = url.PathEscape
var _ = sort.Ints
var _ = strconv.Itoa

// Service exposes typed operations on the /auto-install endpoint family.
type Service interface {
	// ListAutoInstall GET /auto-install
	// Directory index.
	ListAutoInstall(ctx context.Context) error
	// CreateAnswer POST /auto-install/answer
	// \     Handles the system information of a new machine to install.      See also     <https://pve.proxmox.com/wiki/Automated_Installation#Answer_Fetched_via_HTTP>
	CreateAnswer(ctx context.Context, params *CreateAnswerParams) (*CreateAnswerResponse, error)
	// ListInstallations GET /auto-install/installations
	// GET /auto-install/installations  Get all automated installations.
	ListInstallations(ctx context.Context) (*ListInstallationsResponse, error)
	// DeleteInstallations DELETE /auto-install/installations/{uuid}
	// DELETE /auto-install/installations/{uuid}  Remove an installation entry.
	DeleteInstallations(ctx context.Context, uuid string) error
	// CreateInstallationsPostHook POST /auto-install/installations/{uuid}/post-hook
	// POST /auto-install/installations/{uuid}/post-hook  Handles the post-installation hook for all installations.
	CreateInstallationsPostHook(ctx context.Context, uuid string, params *CreateInstallationsPostHookParams) error
	// ListPrepared GET /auto-install/prepared
	// GET /auto-install/prepared  Get all prepared auto-installer answer configurations.
	ListPrepared(ctx context.Context) (*ListPreparedResponse, error)
	// CreatePrepared POST /auto-install/prepared
	// POST /auto-install/prepared  Creates a new prepared answer file.
	CreatePrepared(ctx context.Context, params *CreatePreparedParams) (*CreatePreparedResponse, error)
	// DeletePrepared DELETE /auto-install/prepared/{id}
	// DELETE /auto-install/prepared/{id}  Deletes a prepared auto-installer answer configuration.
	DeletePrepared(ctx context.Context, id string) error
	// GetPrepared GET /auto-install/prepared/{id}
	// GET /auto-install/prepared/{id}  Retrieves a prepared auto-installer answer configuration.
	GetPrepared(ctx context.Context, id string) (*GetPreparedResponse, error)
	// UpdatePrepared PUT /auto-install/prepared/{id}
	// PUT /auto-install/prepared/{id}  Updates a prepared auto-installer answer configuration.
	UpdatePrepared(ctx context.Context, id string, params *UpdatePreparedParams) (*UpdatePreparedResponse, error)
	// ListTokens GET /auto-install/tokens
	// GET /auto-install/tokens  Get all tokens that can be used for authenticating automated installations requests.
	ListTokens(ctx context.Context) (*ListTokensResponse, error)
	// CreateTokens POST /auto-install/tokens
	// POST /auto-install/tokens  Creates a new token for authenticating automated installations.
	CreateTokens(ctx context.Context, params *CreateTokensParams) (*CreateTokensResponse, error)
	// DeleteTokens DELETE /auto-install/tokens/{id}
	// DELETE /auto-install/tokens/{id}  Deletes a prepared auto-installer answer configuration.  If the token is currently in use by any prepared answer configuration, the deletion will fail.
	DeleteTokens(ctx context.Context, id string) error
	// UpdateTokens PUT /auto-install/tokens/{id}
	// PUT /auto-install/tokens/{id}  Updates an existing access token.
	UpdateTokens(ctx context.Context, id string, params *UpdateTokensParams) (*UpdateTokensResponse, error)
}

// New constructs a Service backed by the given pkg/client.Client.
// The client owns authentication, TLS, retries, and logging; this
// service only translates between typed Go shapes and the raw client.
func New(c client.Client) Service {
	if c == nil {
		panic("autoinstall: New called with nil client")
	}
	return &service{c: c}
}

type service struct {
	c client.Client
}

// ListAutoInstall implements Service.ListAutoInstall. GET /auto-install.
func (s *service) ListAutoInstall(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("autoinstall.ListAutoInstall: ctx must not be nil")
	}
	path := "/auto-install"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("autoinstall.ListAutoInstall: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("autoinstall.ListAutoInstall: nil response from client")
	}
	_ = resp
	return nil
}

// CreateAnswerParams is the request payload for CreateAnswer.
type CreateAnswerParams struct {
	// Schema Metadata of the HTTP POST payload, such as schema version of the document.
	Schema json.RawMessage `json:"$schema"`
	// Dmi Collection of various DMI information categories.
	Dmi json.RawMessage `json:"dmi"`
	// Iso Information about the ISO itself.
	Iso json.RawMessage `json:"iso"`
	// NetworkInterfaces Network devices present on the system.
	NetworkInterfaces []json.RawMessage `json:"network_interfaces"`
	// Product The per-product configuration of the installer.
	Product json.RawMessage `json:"product"`
}

// CreateAnswerResponse mirrors the shape returned by POST /auto-install/answer.
type CreateAnswerResponse struct {
	// DiskSetup Disk configuration for the target installation.
	DiskSetup json.RawMessage `json:"disk-setup"`
	// FirstBoot Describes from where to fetch the first-boot hook script, either being baked into the ISO or from a URL.
	FirstBoot json.RawMessage `json:"first-boot,omitempty"`
	// Global General target system options for setting up the system in an automated installation.
	Global json.RawMessage `json:"global"`
	// Network Network configuration to set up inside the target installation. It can either be given statically or taken from the DHCP lease.
	Network json.RawMessage `json:"network"`
	// PostInstallationWebhook Configuration for the post-installation hook, which runs after an installation has completed successfully.
	PostInstallationWebhook json.RawMessage `json:"post-installation-webhook,omitempty"`
}

// CreateAnswer implements Service.CreateAnswer. POST /auto-install/answer.
func (s *service) CreateAnswer(ctx context.Context, params *CreateAnswerParams) (*CreateAnswerResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("autoinstall.CreateAnswer: ctx must not be nil")
	}
	path := "/auto-install/answer"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("autoinstall.CreateAnswer: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("autoinstall.CreateAnswer: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.CreateAnswer: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("autoinstall.CreateAnswer: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("autoinstall.CreateAnswer: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.CreateAnswer: re-marshal data: %w", err)
	}
	out := &CreateAnswerResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.CreateAnswer: unmarshal data: %w", err)
	}
	return out, nil
}

// ListInstallationsResponse mirrors the shape returned by GET /auto-install/installations.
type ListInstallationsResponse []json.RawMessage

// ListInstallations implements Service.ListInstallations. GET /auto-install/installations.
func (s *service) ListInstallations(ctx context.Context) (*ListInstallationsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("autoinstall.ListInstallations: ctx must not be nil")
	}
	path := "/auto-install/installations"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.ListInstallations: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("autoinstall.ListInstallations: nil response from client")
	}
	if resp.Data == nil {
		out := ListInstallationsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.ListInstallations: re-marshal data: %w", err)
	}
	out := &ListInstallationsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.ListInstallations: unmarshal data: %w", err)
	}
	return out, nil
}

// DeleteInstallations implements Service.DeleteInstallations. DELETE /auto-install/installations/{uuid}.
func (s *service) DeleteInstallations(ctx context.Context, uuid string) error {
	if ctx == nil {
		return fmt.Errorf("autoinstall.DeleteInstallations: ctx must not be nil")
	}
	path := fmt.Sprintf("/auto-install/installations/%s", url.PathEscape(uuid))
	var body map[string]interface{}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("autoinstall.DeleteInstallations: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("autoinstall.DeleteInstallations: nil response from client")
	}
	_ = resp
	return nil
}

// CreateInstallationsPostHookParams is the request payload for CreateInstallationsPostHook.
type CreateInstallationsPostHookParams struct {
	// Schema Metadata of the hook, such as schema version of the document.
	Schema json.RawMessage `json:"$schema"`
	// BootInfo Information about the system boot status.
	BootInfo json.RawMessage `json:"boot-info"`
	// CpuInfo Information about the CPU(s) installed in the system
	CpuInfo json.RawMessage `json:"cpu-info"`
	// DebianVersion major.minor version of Debian as installed, retrieved from /etc/debian_version
	DebianVersion string `json:"debian-version"`
	// Disks All disks detected on the system.
	Disks []json.RawMessage `json:"disks"`
	// Dmi Collection of various DMI information categories.
	Dmi json.RawMessage `json:"dmi"`
	// Filesystem Filesystem used for boot disk(s)
	Filesystem string `json:"filesystem"`
	// Fqdn Fully qualified domain name of the installed system
	Fqdn string `json:"fqdn"`
	// Iso Information about the ISO itself.
	Iso json.RawMessage `json:"iso"`
	// KernelVersion The current kernel version (output of `uname`)
	KernelVersion json.RawMessage `json:"kernel-version"`
	// MachineId Unique systemd-id128 identifier of the installed system (128-bit, 16 bytes)
	MachineId string `json:"machine-id"`
	// NetworkInterfaces All network interfaces detected on the system.
	NetworkInterfaces []json.RawMessage `json:"network-interfaces"`
	// Product Information about the installed product itself.
	Product json.RawMessage `json:"product"`
	// RebootMode Action to take after the installation completed successfully.
	RebootMode string `json:"reboot-mode"`
	// SshPublicHostKeys Holds all the public keys for the different algorithms available.
	SshPublicHostKeys json.RawMessage `json:"ssh-public-host-keys"`
	// Token Per-installation token issued together with the answer.
	Token string `json:"token"`
}

// CreateInstallationsPostHook implements Service.CreateInstallationsPostHook. POST /auto-install/installations/{uuid}/post-hook.
func (s *service) CreateInstallationsPostHook(ctx context.Context, uuid string, params *CreateInstallationsPostHookParams) error {
	if ctx == nil {
		return fmt.Errorf("autoinstall.CreateInstallationsPostHook: ctx must not be nil")
	}
	path := fmt.Sprintf("/auto-install/installations/%s/post-hook", url.PathEscape(uuid))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("autoinstall.CreateInstallationsPostHook: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("autoinstall.CreateInstallationsPostHook: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("autoinstall.CreateInstallationsPostHook: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("autoinstall.CreateInstallationsPostHook: nil response from client")
	}
	_ = resp
	return nil
}

// ListPreparedResponse mirrors the shape returned by GET /auto-install/prepared.
type ListPreparedResponse []json.RawMessage

// ListPrepared implements Service.ListPrepared. GET /auto-install/prepared.
func (s *service) ListPrepared(ctx context.Context) (*ListPreparedResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("autoinstall.ListPrepared: ctx must not be nil")
	}
	path := "/auto-install/prepared"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.ListPrepared: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("autoinstall.ListPrepared: nil response from client")
	}
	if resp.Data == nil {
		out := ListPreparedResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.ListPrepared: re-marshal data: %w", err)
	}
	out := &ListPreparedResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.ListPrepared: unmarshal data: %w", err)
	}
	return out, nil
}

// CreatePreparedParams is the request payload for CreatePrepared.
type CreatePreparedParams struct {
	// AuthorizedTokens List of token IDs that are authorized to retrieve this answer.
	AuthorizedTokens []string `json:"authorized-tokens,omitempty"`
	// Cidr IP address and netmask if not using DHCP.  Supports templating via MiniJinja, so this holds either a literal CIDR or a template that resolves to one; it is parsed and validated at render time.
	Cidr *string `json:"cidr,omitempty"`
	// Country Country to use for apt mirrors.
	Country string `json:"country"`
	// DiskFilter Filter against udev properties to select the disks for the installation, to allow dynamic selection of disks.
	DiskFilter json.RawMessage `json:"disk-filter,omitempty"`
	// DiskFilterMatch Whether the associated filters must all match for a device or if any one is enough.
	DiskFilterMatch *string `json:"disk-filter-match,omitempty"`
	// DiskList List of raw disk identifiers to use for the root filesystem.
	DiskList []string `json:"disk-list,omitempty"`
	// DiskMode Whether to use the fixed disk list or select disks dynamically by udev filters.
	DiskMode string `json:"disk-mode"`
	// Dns DNS server address if not using DHCP.  Supports templating via MiniJinja, so this holds either a literal address or a template that resolves to one; it is parsed and validated at render time.
	Dns *string `json:"dns,omitempty"`
	// Filesystem Filesystem-specific options to set on the root disk.
	Filesystem json.RawMessage `json:"filesystem"`
	// Fqdn FQDN to set for the installed system. Only used if `use_dhcp_fqdn` is true.  Supports templating via MiniJinja. The [`proxmox_network_types::fqdn::Fqdn`] type cannot be used here because of that, as curly brackets are not valid in hostnames.
	Fqdn string `json:"fqdn"`
	// Gateway Gateway if not using DHCP.  Supports templating via MiniJinja, so this holds either a literal address or a template that resolves to one; it is parsed and validated at render time.
	Gateway *string `json:"gateway,omitempty"`
	// Id ID of prepared configuration for automated installations.
	Id string `json:"id"`
	// IsDefault Whether this is the default answer. There can only ever be one default answer. `target_filter` below is ignored if this is `true`.
	IsDefault *bool `json:"is-default,omitempty"`
	// Keyboard Keyboard layout of the system.
	Keyboard string `json:"keyboard"`
	// Mailto E-Mail Address.
	Mailto string `json:"mailto"`
	// NetdevFilter Filter for network devices, to select a specific management interface.
	NetdevFilter json.RawMessage `json:"netdev-filter,omitempty"`
	// NetifNamePinningEnabled Whether to enable network interface name pinning.
	NetifNamePinningEnabled bool `json:"netif-name-pinning-enabled"`
	// PostHookBaseUrl HTTP(s) url with optional port.
	PostHookBaseUrl *string `json:"post-hook-base-url,omitempty"`
	// PostHookCertFp X509 certificate fingerprint (sha256).
	PostHookCertFp *string `json:"post-hook-cert-fp,omitempty"`
	// RebootMode Action to take after the installation completed successfully.
	RebootMode string `json:"reboot-mode"`
	// RebootOnError Whether to reboot the machine if an error occurred during the installation.
	RebootOnError bool `json:"reboot-on-error"`
	// RootPassword Root Password.
	RootPassword *string `json:"root-password,omitempty"`
	// RootPasswordHashed Pre-hashed password to set for the `root` PAM account.
	RootPasswordHashed *string `json:"root-password-hashed,omitempty"`
	// RootSshKeys Newline-separated list of public SSH keys to set up for the `root` PAM account.
	RootSshKeys []string `json:"root-ssh-keys,omitempty"`
	// SubscriptionKey A Proxmox subscription key for the installed product.
	SubscriptionKey *string `json:"subscription-key,omitempty"`
	// TargetFilter Map of filters for matching against a property in [`answer::fetch::AnswerFetchData`]. The keys are JSON Pointers as per [RFC6901], the values globs as accepted by the [glob] crate.  Used to check this configuration against incoming automated installation requests. If this is unset, it will match any installation not matched "narrower" by other prepared configurations, thus being the default.  [RFC6901] https://datatracker.ietf.org/doc/html/rfc6901 [glob crate] https://docs.rs/glob/
	TargetFilter json.RawMessage `json:"target-filter,omitempty"`
	// TemplateCounters Key-value pairs of (auto-incrementing) counters.
	TemplateCounters json.RawMessage `json:"template-counters,omitempty"`
	// Timezone Timezone to set on the new system.
	Timezone string `json:"timezone"`
	// UseDhcpFqdn Whether to use the FQDN from the DHCP lease or the user-provided one.
	UseDhcpFqdn bool `json:"use-dhcp-fqdn"`
	// UseDhcpNetwork Whether to use the network configuration from the DHCP lease or not.
	UseDhcpNetwork bool `json:"use-dhcp-network"`
}

// CreatePreparedResponse mirrors the shape returned by POST /auto-install/prepared.
type CreatePreparedResponse struct {
	// Config Configuration describing an automated installation.  Certain fields support simple templating via [MiniJinja]. Currently, following fields will resolve MiniJinja expressions upon instantiation of an answer:  * `fqdn` * `mailto` * `cidr` * `gateway` * `dns`  [MiniJinja]: https://docs.rs/minijinja/
	Config json.RawMessage `json:"config"`
	// Token Result when creating a new token.
	Token json.RawMessage `json:"token,omitempty"`
}

// CreatePrepared implements Service.CreatePrepared. POST /auto-install/prepared.
func (s *service) CreatePrepared(ctx context.Context, params *CreatePreparedParams) (*CreatePreparedResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("autoinstall.CreatePrepared: ctx must not be nil")
	}
	path := "/auto-install/prepared"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("autoinstall.CreatePrepared: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("autoinstall.CreatePrepared: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.CreatePrepared: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("autoinstall.CreatePrepared: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("autoinstall.CreatePrepared: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.CreatePrepared: re-marshal data: %w", err)
	}
	out := &CreatePreparedResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.CreatePrepared: unmarshal data: %w", err)
	}
	return out, nil
}

// DeletePrepared implements Service.DeletePrepared. DELETE /auto-install/prepared/{id}.
func (s *service) DeletePrepared(ctx context.Context, id string) error {
	if ctx == nil {
		return fmt.Errorf("autoinstall.DeletePrepared: ctx must not be nil")
	}
	path := fmt.Sprintf("/auto-install/prepared/%s", url.PathEscape(id))
	var body map[string]interface{}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("autoinstall.DeletePrepared: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("autoinstall.DeletePrepared: nil response from client")
	}
	_ = resp
	return nil
}

// GetPreparedResponse is the raw JSON returned by GET /auto-install/prepared/{id}.
type GetPreparedResponse = json.RawMessage

// GetPrepared implements Service.GetPrepared. GET /auto-install/prepared/{id}.
func (s *service) GetPrepared(ctx context.Context, id string) (*GetPreparedResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("autoinstall.GetPrepared: ctx must not be nil")
	}
	path := fmt.Sprintf("/auto-install/prepared/%s", url.PathEscape(id))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.GetPrepared: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("autoinstall.GetPrepared: nil response from client")
	}
	if resp.Data == nil {
		out := GetPreparedResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.GetPrepared: re-marshal data: %w", err)
	}
	out := &GetPreparedResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.GetPrepared: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdatePreparedParams is the request payload for UpdatePrepared.
type UpdatePreparedParams struct {
	// AuthorizedTokens List of token IDs that are authorized to retrieve this answer.
	AuthorizedTokens []string `json:"authorized-tokens,omitempty"`
	// Cidr IP address and netmask if not using DHCP.  Supports templating via MiniJinja, so this holds either a literal CIDR or a template that resolves to one; it is parsed and validated at render time.
	Cidr *string `json:"cidr,omitempty"`
	// Country Country to use for apt mirrors.
	Country *string `json:"country,omitempty"`
	// Delete List of properties to delete.
	Delete []string `json:"delete,omitempty"`
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// DiskFilter Filter against udev properties to select the disks for the installation, to allow dynamic selection of disks.
	DiskFilter json.RawMessage `json:"disk-filter,omitempty"`
	// DiskFilterMatch Whether the associated filters must all match for a device or if any one is enough.
	DiskFilterMatch *string `json:"disk-filter-match,omitempty"`
	// DiskList List of raw disk identifiers to use for the root filesystem.
	DiskList []string `json:"disk-list,omitempty"`
	// DiskMode Whether to use the fixed disk list or select disks dynamically by udev filters.
	DiskMode *string `json:"disk-mode,omitempty"`
	// Dns DNS server address if not using DHCP.  Supports templating via MiniJinja, so this holds either a literal address or a template that resolves to one; it is parsed and validated at render time.
	Dns *string `json:"dns,omitempty"`
	// Filesystem Filesystem-specific options to set on the root disk.
	Filesystem json.RawMessage `json:"filesystem,omitempty"`
	// Fqdn FQDN to set for the installed system. Only used if `use_dhcp_fqdn` is true.  Supports templating via MiniJinja. The [`proxmox_network_types::fqdn::Fqdn`] type cannot be used here because of that, as curly brackets are not valid in hostnames.
	Fqdn *string `json:"fqdn,omitempty"`
	// Gateway Gateway if not using DHCP.  Supports templating via MiniJinja, so this holds either a literal address or a template that resolves to one; it is parsed and validated at render time.
	Gateway *string `json:"gateway,omitempty"`
	// IsDefault Whether this is the default answer. There can only ever be one default answer. `target_filter` below is ignored if this is `true`.
	IsDefault *bool `json:"is-default,omitempty"`
	// Keyboard Keyboard layout of the system.
	Keyboard *string `json:"keyboard,omitempty"`
	// Mailto E-Mail Address.
	Mailto *string `json:"mailto,omitempty"`
	// NetdevFilter Filter for network devices, to select a specific management interface.
	NetdevFilter json.RawMessage `json:"netdev-filter,omitempty"`
	// NetifNamePinningEnabled Whether to enable network interface name pinning.
	NetifNamePinningEnabled *bool `json:"netif-name-pinning-enabled,omitempty"`
	// PostHookBaseUrl HTTP(s) url with optional port.
	PostHookBaseUrl *string `json:"post-hook-base-url,omitempty"`
	// PostHookCertFp X509 certificate fingerprint (sha256).
	PostHookCertFp *string `json:"post-hook-cert-fp,omitempty"`
	// RebootMode Action to take after the installation completed successfully.
	RebootMode *string `json:"reboot-mode,omitempty"`
	// RebootOnError Whether to reboot the machine if an error occurred during the installation.
	RebootOnError *bool `json:"reboot-on-error,omitempty"`
	// RootPassword Root Password.
	RootPassword *string `json:"root-password,omitempty"`
	// RootPasswordHashed Pre-hashed password to set for the `root` PAM account.
	RootPasswordHashed *string `json:"root-password-hashed,omitempty"`
	// RootSshKeys Newline-separated list of public SSH keys to set up for the `root` PAM account.
	RootSshKeys []string `json:"root-ssh-keys,omitempty"`
	// SubscriptionKey A Proxmox subscription key for the installed product.
	SubscriptionKey *string `json:"subscription-key,omitempty"`
	// TargetFilter Map of filters for matching against a property in [`answer::fetch::AnswerFetchData`]. The keys are JSON Pointers as per [RFC6901], the values globs as accepted by the [glob] crate.  Used to check this configuration against incoming automated installation requests. If this is unset, it will match any installation not matched "narrower" by other prepared configurations, thus being the default.  [RFC6901] https://datatracker.ietf.org/doc/html/rfc6901 [glob crate] https://docs.rs/glob/
	TargetFilter json.RawMessage `json:"target-filter,omitempty"`
	// TemplateCounters Key-value pairs of (auto-incrementing) counters.
	TemplateCounters json.RawMessage `json:"template-counters,omitempty"`
	// Timezone Timezone to set on the new system.
	Timezone *string `json:"timezone,omitempty"`
	// UseDhcpFqdn Whether to use the FQDN from the DHCP lease or the user-provided one.
	UseDhcpFqdn *bool `json:"use-dhcp-fqdn,omitempty"`
	// UseDhcpNetwork Whether to use the network configuration from the DHCP lease or not.
	UseDhcpNetwork *bool `json:"use-dhcp-network,omitempty"`
}

// UpdatePreparedResponse mirrors the shape returned by PUT /auto-install/prepared/{id}.
type UpdatePreparedResponse struct {
	// Config Configuration describing an automated installation.  Certain fields support simple templating via [MiniJinja]. Currently, following fields will resolve MiniJinja expressions upon instantiation of an answer:  * `fqdn` * `mailto` * `cidr` * `gateway` * `dns`  [MiniJinja]: https://docs.rs/minijinja/
	Config json.RawMessage `json:"config"`
	// Token Result when creating a new token.
	Token json.RawMessage `json:"token,omitempty"`
}

// UpdatePrepared implements Service.UpdatePrepared. PUT /auto-install/prepared/{id}.
func (s *service) UpdatePrepared(ctx context.Context, id string, params *UpdatePreparedParams) (*UpdatePreparedResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("autoinstall.UpdatePrepared: ctx must not be nil")
	}
	path := fmt.Sprintf("/auto-install/prepared/%s", url.PathEscape(id))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("autoinstall.UpdatePrepared: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("autoinstall.UpdatePrepared: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.UpdatePrepared: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("autoinstall.UpdatePrepared: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("autoinstall.UpdatePrepared: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.UpdatePrepared: re-marshal data: %w", err)
	}
	out := &UpdatePreparedResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.UpdatePrepared: unmarshal data: %w", err)
	}
	return out, nil
}

// ListTokensResponse mirrors the shape returned by GET /auto-install/tokens.
type ListTokensResponse []json.RawMessage

// ListTokens implements Service.ListTokens. GET /auto-install/tokens.
func (s *service) ListTokens(ctx context.Context) (*ListTokensResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("autoinstall.ListTokens: ctx must not be nil")
	}
	path := "/auto-install/tokens"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.ListTokens: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("autoinstall.ListTokens: nil response from client")
	}
	if resp.Data == nil {
		out := ListTokensResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.ListTokens: re-marshal data: %w", err)
	}
	out := &ListTokensResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.ListTokens: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateTokensParams is the request payload for CreateTokens.
type CreateTokensParams struct {
	// Comment Comment.
	Comment *string `json:"comment,omitempty"`
	// Enabled Whether the token is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// ExpireAt Token expiration date, in seconds since the epoch. '0' means no expiration.
	ExpireAt *int64 `json:"expire-at,omitempty"`
	// Id API Token name
	Id string `json:"id"`
}

// CreateTokensResponse mirrors the shape returned by POST /auto-install/tokens.
type CreateTokensResponse struct {
	// Secret The secret value itself.
	Secret string `json:"secret"`
	// Token A token for authenticating requests from the automated installer.
	Token json.RawMessage `json:"token"`
}

// CreateTokens implements Service.CreateTokens. POST /auto-install/tokens.
func (s *service) CreateTokens(ctx context.Context, params *CreateTokensParams) (*CreateTokensResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("autoinstall.CreateTokens: ctx must not be nil")
	}
	path := "/auto-install/tokens"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("autoinstall.CreateTokens: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("autoinstall.CreateTokens: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.CreateTokens: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("autoinstall.CreateTokens: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("autoinstall.CreateTokens: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.CreateTokens: re-marshal data: %w", err)
	}
	out := &CreateTokensResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.CreateTokens: unmarshal data: %w", err)
	}
	return out, nil
}

// DeleteTokens implements Service.DeleteTokens. DELETE /auto-install/tokens/{id}.
func (s *service) DeleteTokens(ctx context.Context, id string) error {
	if ctx == nil {
		return fmt.Errorf("autoinstall.DeleteTokens: ctx must not be nil")
	}
	path := fmt.Sprintf("/auto-install/tokens/%s", url.PathEscape(id))
	var body map[string]interface{}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("autoinstall.DeleteTokens: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("autoinstall.DeleteTokens: nil response from client")
	}
	_ = resp
	return nil
}

// UpdateTokensParams is the request payload for UpdateTokens.
type UpdateTokensParams struct {
	// Comment Comment.
	Comment *string `json:"comment,omitempty"`
	// Delete List of properties to delete.
	Delete []string `json:"delete,omitempty"`
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Enabled Whether this token is enabled
	Enabled *bool `json:"enabled,omitempty"`
	// ExpireAt Token expiration date (seconds since epoch). '0' means no expiration date.
	ExpireAt *int64 `json:"expire-at,omitempty"`
	// RegenerateSecret Whether to regenerate the current secret, invalidating the old one.
	RegenerateSecret *bool `json:"regenerate-secret,omitempty"`
}

// UpdateTokensResponse mirrors the shape returned by PUT /auto-install/tokens/{id}.
type UpdateTokensResponse struct {
	// Secret The secret, if a new one was requested to be generated.
	Secret *string `json:"secret,omitempty"`
	// Token A token for authenticating requests from the automated installer.
	Token json.RawMessage `json:"token"`
}

// UpdateTokens implements Service.UpdateTokens. PUT /auto-install/tokens/{id}.
func (s *service) UpdateTokens(ctx context.Context, id string, params *UpdateTokensParams) (*UpdateTokensResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("autoinstall.UpdateTokens: ctx must not be nil")
	}
	path := fmt.Sprintf("/auto-install/tokens/%s", url.PathEscape(id))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("autoinstall.UpdateTokens: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("autoinstall.UpdateTokens: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.UpdateTokens: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("autoinstall.UpdateTokens: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("autoinstall.UpdateTokens: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.UpdateTokens: re-marshal data: %w", err)
	}
	out := &UpdateTokensResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("autoinstall.UpdateTokens: unmarshal data: %w", err)
	}
	return out, nil
}
