// Code generated by cmd/pvegen. DO NOT EDIT.

// Package clusterstorage exposes typed bindings for the PVE /storage endpoint family.
package clusterstorage

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/fivetwenty-io/pve-apiclient-go/v3/pkg/client"
)

var _ = strings.TrimPrefix
var _ = json.RawMessage(nil)
var _ = url.PathEscape
var _ = sort.Ints
var _ = strconv.Itoa

// Service exposes typed operations on the /storage endpoint family.
type Service interface {
	// ListStorage GET /storage
	// Storage index.
	ListStorage(ctx context.Context, params *ListStorageParams) (*ListStorageResponse, error)
	// CreateStorage POST /storage
	// Create a new storage.
	CreateStorage(ctx context.Context, params *CreateStorageParams) (*CreateStorageResponse, error)
	// DeleteStorage DELETE /storage/{storage}
	// Delete storage configuration.
	DeleteStorage(ctx context.Context, storage string) error
	// GetStorage GET /storage/{storage}
	// Read storage configuration.
	GetStorage(ctx context.Context, storage string) (*GetStorageResponse, error)
	// UpdateStorage PUT /storage/{storage}
	// Update storage configuration.
	UpdateStorage(ctx context.Context, storage string, params *UpdateStorageParams) (*UpdateStorageResponse, error)
}

// New constructs a Service backed by the given pkg/client.Client.
// The client owns authentication, TLS, retries, and logging; this
// service only translates between typed Go shapes and the raw client.
func New(c client.Client) Service {
	if c == nil {
		panic("clusterstorage: New called with nil client")
	}
	return &service{c: c}
}

type service struct {
	c client.Client
}

// ListStorageParams is the request payload for ListStorage.
type ListStorageParams struct {
	// Type Only list storage of specific type
	Type *string `json:"type,omitempty"`
}

// ListStorageResponse mirrors the shape returned by GET /storage.
type ListStorageResponse []json.RawMessage

// ListStorage implements Service.ListStorage. GET /storage.
func (s *service) ListStorage(ctx context.Context, params *ListStorageParams) (*ListStorageResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("clusterstorage.ListStorage: ctx must not be nil")
	}
	path := "/storage"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("clusterstorage.ListStorage: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return nil, fmt.Errorf("clusterstorage.ListStorage: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("clusterstorage.ListStorage: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("clusterstorage.ListStorage: nil response from client")
	}
	if resp.Data == nil {
		out := ListStorageResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("clusterstorage.ListStorage: re-marshal data: %w", err)
	}
	out := &ListStorageResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("clusterstorage.ListStorage: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateStorageParams is the request payload for CreateStorage.
type CreateStorageParams struct {
	// Authsupported Authsupported.
	Authsupported *string `json:"authsupported,omitempty"`
	// Base Base volume. This volume is automatically activated.
	Base *string `json:"base,omitempty"`
	// Blocksize block size
	Blocksize *string `json:"blocksize,omitempty"`
	// Bwlimit Set I/O bandwidth limit for various operations (in KiB/s).
	Bwlimit *string `json:"bwlimit,omitempty"`
	// ComstarHg host group for comstar views
	ComstarHg *string `json:"comstar_hg,omitempty"`
	// ComstarTg target group for comstar views
	ComstarTg *string `json:"comstar_tg,omitempty"`
	// Content Allowed content types.  NOTE: the value 'rootdir' is used for Containers, and value 'images' for VMs.
	Content *string `json:"content,omitempty"`
	// ContentDirs Overrides for default content type directories.
	ContentDirs *string `json:"content-dirs,omitempty"`
	// CreateBasePath Create the base directory if it doesn't exist.
	CreateBasePath *bool `json:"create-base-path,omitempty"`
	// CreateSubdirs Populate the directory with the default structure.
	CreateSubdirs *bool `json:"create-subdirs,omitempty"`
	// DataPool Data Pool (for erasure coding only)
	DataPool *string `json:"data-pool,omitempty"`
	// Datastore Proxmox Backup Server datastore name.
	Datastore *string `json:"datastore,omitempty"`
	// Disable Flag to disable the storage.
	Disable *bool `json:"disable,omitempty"`
	// Domain CIFS domain.
	Domain *string `json:"domain,omitempty"`
	// EncryptionKey Encryption key. Use 'autogen' to generate one automatically without passphrase.
	EncryptionKey *string `json:"encryption-key,omitempty"`
	// Export NFS export path.
	Export *string `json:"export,omitempty"`
	// Fingerprint Certificate SHA 256 fingerprint.
	Fingerprint *string `json:"fingerprint,omitempty"`
	// Format Default image format.
	Format *string `json:"format,omitempty"`
	// FsName The Ceph filesystem name.
	FsName *string `json:"fs-name,omitempty"`
	// Fuse Mount CephFS through FUSE.
	Fuse *bool `json:"fuse,omitempty"`
	// IsMountpoint Assume the given path is an externally managed mountpoint and consider the storage offline if it is not mounted. Using a boolean (yes/no) value serves as a shortcut to using the target path in this field.
	IsMountpoint *string `json:"is_mountpoint,omitempty"`
	// Iscsiprovider iscsi provider
	Iscsiprovider *string `json:"iscsiprovider,omitempty"`
	// Keyring Client keyring contents (for external clusters).
	Keyring *string `json:"keyring,omitempty"`
	// Krbd Always access rbd through krbd kernel module.
	Krbd *bool `json:"krbd,omitempty"`
	// LioTpg target portal group for Linux LIO targets
	LioTpg *string `json:"lio_tpg,omitempty"`
	// MasterPubkey Base64-encoded, PEM-formatted public RSA key. Used to encrypt a copy of the encryption-key which will be added to each encrypted backup.
	MasterPubkey *string `json:"master-pubkey,omitempty"`
	// MaxProtectedBackups Maximal number of protected backups per guest. Use '-1' for unlimited.
	MaxProtectedBackups *int64 `json:"max-protected-backups,omitempty"`
	// Mkdir Create the directory if it doesn't exist and populate it with default sub-dirs. NOTE: Deprecated, use the 'create-base-path' and 'create-subdirs' options instead.
	Mkdir *bool `json:"mkdir,omitempty"`
	// Monhost IP addresses of monitors (for external clusters).
	Monhost *string `json:"monhost,omitempty"`
	// Mountpoint mount point
	Mountpoint *string `json:"mountpoint,omitempty"`
	// Namespace Namespace.
	Namespace *string `json:"namespace,omitempty"`
	// Nocow Set the NOCOW flag on files. Disables data checksumming and causes data errors to be unrecoverable from while allowing direct I/O. Only use this if data does not need to be any more safe than on a single ext4 formatted disk with no underlying raid system.
	Nocow *bool `json:"nocow,omitempty"`
	// Nodes List of nodes for which the storage configuration applies.
	Nodes *string `json:"nodes,omitempty"`
	// Nowritecache disable write caching on the target
	Nowritecache *bool `json:"nowritecache,omitempty"`
	// Options NFS/CIFS mount options (see 'man nfs' or 'man mount.cifs')
	Options *string `json:"options,omitempty"`
	// Password Password for accessing the share/datastore.
	Password *string `json:"password,omitempty"`
	// Path File system path.
	Path *string `json:"path,omitempty"`
	// Pool Pool.
	Pool *string `json:"pool,omitempty"`
	// Port Use this port to connect to the storage instead of the default one (for example, with PBS or ESXi). For NFS and CIFS, use the 'options' option to configure the port via the mount options.
	Port *int64 `json:"port,omitempty"`
	// Portal iSCSI portal (IP or DNS name with optional port).
	Portal *string `json:"portal,omitempty"`
	// Preallocation Preallocation mode for raw and qcow2 images. Using 'metadata' on raw images results in preallocation=off.
	Preallocation *string `json:"preallocation,omitempty"`
	// PruneBackups The retention options with shorter intervals are processed first with --keep-last being the very first one. Each option covers a specific period of time. We say that backups within this period are covered by this option. The next option does not take care of already covered backups and only considers older backups.
	PruneBackups *string `json:"prune-backups,omitempty"`
	// Saferemove Zero-out data when removing LVs.
	Saferemove *bool `json:"saferemove,omitempty"`
	// SaferemoveStepsize Wipe step size in MiB. It will be capped to the maximum supported by the storage.
	SaferemoveStepsize *int64 `json:"saferemove-stepsize,omitempty"`
	// SaferemoveThroughput Wipe throughput (cstream -t parameter value).
	SaferemoveThroughput *string `json:"saferemove_throughput,omitempty"`
	// Server Server IP or DNS name.
	Server *string `json:"server,omitempty"`
	// Share CIFS share.
	Share *string `json:"share,omitempty"`
	// Shared Indicate that this is a single storage with the same contents on all nodes (or all listed in the 'nodes' option). It will not make the contents of a local storage automatically accessible to other nodes, it just marks an already shared storage as such!
	Shared *bool `json:"shared,omitempty"`
	// SkipCertVerification Disable TLS certificate verification, only enable on fully trusted networks!
	SkipCertVerification *bool `json:"skip-cert-verification,omitempty"`
	// Smbversion SMB protocol version. 'default' if not set, negotiates the highest SMB2+ version supported by both the client and server.
	Smbversion *string `json:"smbversion,omitempty"`
	// SnapshotAsVolumeChain Enable support for creating storage-vendor agnostic snapshot through volume backing-chains.
	SnapshotAsVolumeChain *bool `json:"snapshot-as-volume-chain,omitempty"`
	// Sparse use sparse volumes
	Sparse *bool `json:"sparse,omitempty"`
	// Storage The storage identifier.
	Storage string `json:"storage"`
	// Subdir Subdir to mount.
	Subdir *string `json:"subdir,omitempty"`
	// TaggedOnly Only use logical volumes tagged with 'pve-vm-ID'.
	TaggedOnly *bool `json:"tagged_only,omitempty"`
	// Target iSCSI target.
	Target *string `json:"target,omitempty"`
	// Thinpool LVM thin pool LV name.
	Thinpool *string `json:"thinpool,omitempty"`
	// Type Storage type.
	Type string `json:"type"`
	// Username RBD Id.
	Username *string `json:"username,omitempty"`
	// Vgname Volume group name.
	Vgname *string `json:"vgname,omitempty"`
	// ZfsBasePath Base path where to look for the created ZFS block devices. Set automatically during creation if not specified. Usually '/dev/zvol'.
	ZfsBasePath *string `json:"zfs-base-path,omitempty"`
}

// CreateStorageResponse mirrors the shape returned by POST /storage.
type CreateStorageResponse struct {
	// Config Partial, possibly server generated, configuration properties.
	Config json.RawMessage `json:"config,omitempty"`
	// Storage The ID of the created storage.
	Storage string `json:"storage"`
	// Type The type of the created storage.
	Type string `json:"type"`
}

// CreateStorage implements Service.CreateStorage. POST /storage.
func (s *service) CreateStorage(ctx context.Context, params *CreateStorageParams) (*CreateStorageResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("clusterstorage.CreateStorage: ctx must not be nil")
	}
	path := "/storage"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("clusterstorage.CreateStorage: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return nil, fmt.Errorf("clusterstorage.CreateStorage: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("clusterstorage.CreateStorage: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("clusterstorage.CreateStorage: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("clusterstorage.CreateStorage: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("clusterstorage.CreateStorage: re-marshal data: %w", err)
	}
	out := &CreateStorageResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("clusterstorage.CreateStorage: unmarshal data: %w", err)
	}
	return out, nil
}

// DeleteStorage implements Service.DeleteStorage. DELETE /storage/{storage}.
func (s *service) DeleteStorage(ctx context.Context, storage string) error {
	if ctx == nil {
		return fmt.Errorf("clusterstorage.DeleteStorage: ctx must not be nil")
	}
	path := fmt.Sprintf("/storage/%s", url.PathEscape(storage))
	var body map[string]interface{}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("clusterstorage.DeleteStorage: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("clusterstorage.DeleteStorage: nil response from client")
	}
	_ = resp
	return nil
}

// GetStorageResponse is the raw JSON returned by GET /storage/{storage}.
type GetStorageResponse = json.RawMessage

// GetStorage implements Service.GetStorage. GET /storage/{storage}.
func (s *service) GetStorage(ctx context.Context, storage string) (*GetStorageResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("clusterstorage.GetStorage: ctx must not be nil")
	}
	path := fmt.Sprintf("/storage/%s", url.PathEscape(storage))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("clusterstorage.GetStorage: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("clusterstorage.GetStorage: nil response from client")
	}
	if resp.Data == nil {
		out := GetStorageResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("clusterstorage.GetStorage: re-marshal data: %w", err)
	}
	out := &GetStorageResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("clusterstorage.GetStorage: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateStorageParams is the request payload for UpdateStorage.
type UpdateStorageParams struct {
	// Blocksize block size
	Blocksize *string `json:"blocksize,omitempty"`
	// Bwlimit Set I/O bandwidth limit for various operations (in KiB/s).
	Bwlimit *string `json:"bwlimit,omitempty"`
	// ComstarHg host group for comstar views
	ComstarHg *string `json:"comstar_hg,omitempty"`
	// ComstarTg target group for comstar views
	ComstarTg *string `json:"comstar_tg,omitempty"`
	// Content Allowed content types.  NOTE: the value 'rootdir' is used for Containers, and value 'images' for VMs.
	Content *string `json:"content,omitempty"`
	// ContentDirs Overrides for default content type directories.
	ContentDirs *string `json:"content-dirs,omitempty"`
	// CreateBasePath Create the base directory if it doesn't exist.
	CreateBasePath *bool `json:"create-base-path,omitempty"`
	// CreateSubdirs Populate the directory with the default structure.
	CreateSubdirs *bool `json:"create-subdirs,omitempty"`
	// DataPool Data Pool (for erasure coding only)
	DataPool *string `json:"data-pool,omitempty"`
	// Delete A list of settings you want to delete.
	Delete *string `json:"delete,omitempty"`
	// Digest Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Disable Flag to disable the storage.
	Disable *bool `json:"disable,omitempty"`
	// Domain CIFS domain.
	Domain *string `json:"domain,omitempty"`
	// EncryptionKey Encryption key. Use 'autogen' to generate one automatically without passphrase.
	EncryptionKey *string `json:"encryption-key,omitempty"`
	// Fingerprint Certificate SHA 256 fingerprint.
	Fingerprint *string `json:"fingerprint,omitempty"`
	// Format Default image format.
	Format *string `json:"format,omitempty"`
	// FsName The Ceph filesystem name.
	FsName *string `json:"fs-name,omitempty"`
	// Fuse Mount CephFS through FUSE.
	Fuse *bool `json:"fuse,omitempty"`
	// IsMountpoint Assume the given path is an externally managed mountpoint and consider the storage offline if it is not mounted. Using a boolean (yes/no) value serves as a shortcut to using the target path in this field.
	IsMountpoint *string `json:"is_mountpoint,omitempty"`
	// Keyring Client keyring contents (for external clusters).
	Keyring *string `json:"keyring,omitempty"`
	// Krbd Always access rbd through krbd kernel module.
	Krbd *bool `json:"krbd,omitempty"`
	// LioTpg target portal group for Linux LIO targets
	LioTpg *string `json:"lio_tpg,omitempty"`
	// MasterPubkey Base64-encoded, PEM-formatted public RSA key. Used to encrypt a copy of the encryption-key which will be added to each encrypted backup.
	MasterPubkey *string `json:"master-pubkey,omitempty"`
	// MaxProtectedBackups Maximal number of protected backups per guest. Use '-1' for unlimited.
	MaxProtectedBackups *int64 `json:"max-protected-backups,omitempty"`
	// Mkdir Create the directory if it doesn't exist and populate it with default sub-dirs. NOTE: Deprecated, use the 'create-base-path' and 'create-subdirs' options instead.
	Mkdir *bool `json:"mkdir,omitempty"`
	// Monhost IP addresses of monitors (for external clusters).
	Monhost *string `json:"monhost,omitempty"`
	// Mountpoint mount point
	Mountpoint *string `json:"mountpoint,omitempty"`
	// Namespace Namespace.
	Namespace *string `json:"namespace,omitempty"`
	// Nocow Set the NOCOW flag on files. Disables data checksumming and causes data errors to be unrecoverable from while allowing direct I/O. Only use this if data does not need to be any more safe than on a single ext4 formatted disk with no underlying raid system.
	Nocow *bool `json:"nocow,omitempty"`
	// Nodes List of nodes for which the storage configuration applies.
	Nodes *string `json:"nodes,omitempty"`
	// Nowritecache disable write caching on the target
	Nowritecache *bool `json:"nowritecache,omitempty"`
	// Options NFS/CIFS mount options (see 'man nfs' or 'man mount.cifs')
	Options *string `json:"options,omitempty"`
	// Password Password for accessing the share/datastore.
	Password *string `json:"password,omitempty"`
	// Pool Pool.
	Pool *string `json:"pool,omitempty"`
	// Port Use this port to connect to the storage instead of the default one (for example, with PBS or ESXi). For NFS and CIFS, use the 'options' option to configure the port via the mount options.
	Port *int64 `json:"port,omitempty"`
	// Preallocation Preallocation mode for raw and qcow2 images. Using 'metadata' on raw images results in preallocation=off.
	Preallocation *string `json:"preallocation,omitempty"`
	// PruneBackups The retention options with shorter intervals are processed first with --keep-last being the very first one. Each option covers a specific period of time. We say that backups within this period are covered by this option. The next option does not take care of already covered backups and only considers older backups.
	PruneBackups *string `json:"prune-backups,omitempty"`
	// Saferemove Zero-out data when removing LVs.
	Saferemove *bool `json:"saferemove,omitempty"`
	// SaferemoveStepsize Wipe step size in MiB. It will be capped to the maximum supported by the storage.
	SaferemoveStepsize *int64 `json:"saferemove-stepsize,omitempty"`
	// SaferemoveThroughput Wipe throughput (cstream -t parameter value).
	SaferemoveThroughput *string `json:"saferemove_throughput,omitempty"`
	// Server Server IP or DNS name.
	Server *string `json:"server,omitempty"`
	// Shared Indicate that this is a single storage with the same contents on all nodes (or all listed in the 'nodes' option). It will not make the contents of a local storage automatically accessible to other nodes, it just marks an already shared storage as such!
	Shared *bool `json:"shared,omitempty"`
	// SkipCertVerification Disable TLS certificate verification, only enable on fully trusted networks!
	SkipCertVerification *bool `json:"skip-cert-verification,omitempty"`
	// Smbversion SMB protocol version. 'default' if not set, negotiates the highest SMB2+ version supported by both the client and server.
	Smbversion *string `json:"smbversion,omitempty"`
	// SnapshotAsVolumeChain Enable support for creating storage-vendor agnostic snapshot through volume backing-chains.
	SnapshotAsVolumeChain *bool `json:"snapshot-as-volume-chain,omitempty"`
	// Sparse use sparse volumes
	Sparse *bool `json:"sparse,omitempty"`
	// Subdir Subdir to mount.
	Subdir *string `json:"subdir,omitempty"`
	// TaggedOnly Only use logical volumes tagged with 'pve-vm-ID'.
	TaggedOnly *bool `json:"tagged_only,omitempty"`
	// Username RBD Id.
	Username *string `json:"username,omitempty"`
	// ZfsBasePath Base path where to look for the created ZFS block devices. Set automatically during creation if not specified. Usually '/dev/zvol'.
	ZfsBasePath *string `json:"zfs-base-path,omitempty"`
}

// UpdateStorageResponse mirrors the shape returned by PUT /storage/{storage}.
type UpdateStorageResponse struct {
	// Config Partial, possibly server generated, configuration properties.
	Config json.RawMessage `json:"config,omitempty"`
	// Storage The ID of the created storage.
	Storage string `json:"storage"`
	// Type The type of the created storage.
	Type string `json:"type"`
}

// UpdateStorage implements Service.UpdateStorage. PUT /storage/{storage}.
func (s *service) UpdateStorage(ctx context.Context, storage string, params *UpdateStorageParams) (*UpdateStorageResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("clusterstorage.UpdateStorage: ctx must not be nil")
	}
	path := fmt.Sprintf("/storage/%s", url.PathEscape(storage))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("clusterstorage.UpdateStorage: marshal params: %w", err)
		}
		err = json.Unmarshal(raw, &body)
		if err != nil {
			return nil, fmt.Errorf("clusterstorage.UpdateStorage: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("clusterstorage.UpdateStorage: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("clusterstorage.UpdateStorage: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("clusterstorage.UpdateStorage: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("clusterstorage.UpdateStorage: re-marshal data: %w", err)
	}
	out := &UpdateStorageResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("clusterstorage.UpdateStorage: unmarshal data: %w", err)
	}
	return out, nil
}
