// Code generated by cmd/pvegen. DO NOT EDIT.

package clusterstorage_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"testing"

	"github.com/fivetwenty-io/pve-apiclient-go/v3/pkg/api/clusterstorage"
	pveclient "github.com/fivetwenty-io/pve-apiclient-go/v3/pkg/client"
)

func smokeOptsFromServerURL(u string) pveclient.Options {
	parsed, err := url.Parse(u)
	if err != nil {
		panic("test setup: invalid server URL: " + err.Error())
	}

	host := parsed.Hostname()

	port := 0
	if p := parsed.Port(); p != "" {
		port, _ = strconv.Atoi(p)
	}

	return pveclient.Options{
		Host:     host,
		Port:     port,
		Protocol: "http",
		APIToken: "user@pam!tok=sec",
	}
}

func TestSmoke_Clusterstorage_GeneratedMethods(t *testing.T) {
	t.Parallel()

	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		_ = json.NewEncoder(w).Encode(map[string]any{
			"data":    map[string]any{},
			"success": 1,
		})
	})

	srv := httptest.NewServer(mux)
	defer srv.Close()

	c, err := pveclient.NewClient(smokeOptsFromServerURL(srv.URL))
	if err != nil {
		t.Fatalf("NewClient: %v", err)
	}

	svc := clusterstorage.New(c)
	ctx := context.Background()

	t.Run("ListStorage", func(t *testing.T) {
		_, err := svc.ListStorage(ctx, nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetStorage", func(t *testing.T) {
		_, err := svc.GetStorage(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
}
