// Code generated by cmd/pvegen. DO NOT EDIT.

// Package subscriptions exposes typed bindings for the PVE /subscriptions endpoint family.
package subscriptions

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
)

var _ = strings.TrimPrefix
var _ = json.RawMessage(nil)
var _ = url.PathEscape
var _ = sort.Ints
var _ = strconv.Itoa

// Service exposes typed operations on the /subscriptions endpoint family.
type Service interface {
	// ListSubscriptions GET /subscriptions
	// Directory index.
	ListSubscriptions(ctx context.Context) error
	// CreateAdoptAll POST /subscriptions/adopt-all
	// Adopt every foreign live subscription in one transaction.  Walks the node-status view (so only remotes the caller can audit are considered), collects every (remote, node) that has a live current key but no pool entry bound to it, and imports each one into the pool with source = `Adopted`. Candidates are skipped (not adopted, not an error) when:  - The caller has no `PRIV_RESOURCE_MODIFY` on the candidate's remote: an audit-only operator should not be able to materialise pool state for a remote they cannot manage. - The live key is already in the pool but bound elsewhere: leaving the rebind as a manual step keeps the bulk action from silently competing with a deliberate prior assignment. - The live key fails schema validation or its prefix is unknown: a buggy or malicious remote should not be able to inject garbage into the pool through a bulk shortcut.  Successfully-adopted entries are returned so the caller (CLI / UI) can summarise the outcome without needing a separate refresh round-trip.
	CreateAdoptAll(ctx context.Context, params *CreateAdoptAllParams) (*CreateAdoptAllResponse, error)
	// CreateAdoptKey POST /subscriptions/adopt-key
	// Adopt the live subscription on a remote node into the pool.  Reads the live current key from `remote`/`node` and brings the pool under management of it without touching the remote (no DELETE / push). Three sub-cases for the live key:  - Not in the pool: a fresh `Adopted` entry is inserted, bound to (remote, node). - In the pool, unbound: rebound to (remote, node); the source is left untouched so a key that was originally added manually keeps its `Manual` label even after a remote re-import. - In the pool, bound elsewhere: refused; the operator has to reconcile the binding first.  Refuses if a pool entry is already bound to (remote, node): adopting a node that is already pool-managed would either be a no-op or a footgun (rebinding the same node to a different key in the pool), so the caller has to pick the right Assign/Clear path explicitly.  Per-remote `PRIV_RESOURCE_MODIFY` is enforced inside the handler so an operator with global system access alone cannot pull subscriptions off remotes they have no other authority on (an adopted key bound to (remote, node) is itself an audit-side surface against that node).
	CreateAdoptKey(ctx context.Context, params *CreateAdoptKeyParams) error
	// CreateApplyPending POST /subscriptions/apply-pending
	// Apply every pending pool change to its remote node.  Pending entries are pool keys whose live `current_key` on the bound node does not match the assigned pool key (either a different live key, no key, or the remote did not respond / the node is gone). Each step is logged from a worker task so the admin can follow progress.  Subscription health (Invalid, Expired, ...) is intentionally not considered pending: the assigned key already reached the node, re-pushing it would not change the shop's verdict.  The worker attempts every pending entry rather than bailing on the first failure: a failed push or clear is collected and its entry stays pending, the worker then exits with an error summarising the failures, and a later apply retries only those.  Returns `None` when nothing is pending so the caller can show a short info message instead of opening a task progress dialog for a no-op worker.  The optional `digest` rejects the call at the API boundary if the pool changed since the caller last loaded it, so a stale browser tab cannot start a worker on a plan the operator no longer sees. The worker itself deliberately re-reads the pool when it fires (a worker can be scheduled with delay), so a parallel admin edit between API return and worker firing is still honoured - the digest only pins the at-API-call-time plan, not the executed plan.
	CreateApplyPending(ctx context.Context, params *CreateApplyPendingParams) (*CreateApplyPendingResponse, error)
	// CreateAutoAssign POST /subscriptions/auto-assign
	// Compute a proposed mapping of unused pool keys to nodes without an active subscription.  Returns the plan plus snapshots of the inputs (pool digest and a hash of the consulted node-status). The plan is committed by `bulk_assign` and rejected there if either snapshot no longer matches the live state, so an operator never silently applies a plan that drifted between preview and commit.  `PRIV_SYS_MODIFY` is required to *preview* the plan; the actual commit performed by `bulk_assign` additionally drops proposals on any remote the caller cannot `PRIV_RESOURCE_MODIFY`, so an audit-only-on-a-remote operator can see the suggestion but the write never lands there.  The response carries nested `AutoAssignProposal` data; clients must submit follow-up `bulk_assign` calls with an `application/json` body, the form-urlencoded path cannot encode the nested structure.
	CreateAutoAssign(ctx context.Context) (*CreateAutoAssignResponse, error)
	// CreateBulkAssign POST /subscriptions/bulk-assign
	// Apply a proposal previously returned by `auto_assign`.  Rejects with 409 if the pool config digest has moved or the live node-status hash differs from what the proposal was computed against; the caller is expected to refresh the proposal and retry. Per-remote `PRIV_RESOURCE_MODIFY` is checked inside the handler so an audit-only caller's previously-rendered preview cannot be applied on their behalf.  The request body is a nested `AutoAssignProposal`; callers must submit it as `application/json`, the form-urlencoded path cannot encode the nested structure.
	CreateBulkAssign(ctx context.Context, params *CreateBulkAssignParams) (*CreateBulkAssignResponse, error)
	// CreateCheck POST /subscriptions/check
	// Trigger a fresh shop-side subscription check on `remote`/`node`.  Mirrors the per-product "Check" button on PVE / PBS: drives the remote's `update_subscription(force=true)` endpoint so a status that went stale at the shop (Invalid, Expired) gets re-verified without waiting for the next periodic check. The cached subscription state for the remote is invalidated so the next node-status read reflects the fresh verdict instead of a 5-minute-stale snapshot.  Per-remote `PRIV_RESOURCE_MODIFY` is enforced inside the handler since the call costs an outbound HTTPS request to the shop.
	CreateCheck(ctx context.Context, params *CreateCheckParams) error
	// CreateClearPending POST /subscriptions/clear-pending
	// Drop every queued change in one bulk transaction.  Two shapes of pending change are discarded: * pool key bound to a remote node whose live `current_key` does not match the assigned pool key (a different live key, no key, or no row returned at all because the remote is unreachable / the node is gone): the binding is dropped, the key returns to the free pool, and the remote is not touched. * queued Clear Keys (`pending_clear = true`): the flag is cleared; the binding and the live key on the remote stay intact.  Only entries the caller has `PRIV_RESOURCE_MODIFY` on are touched; remotes the caller may only audit are skipped. Mirrors `apply-pending` but drops the queue instead of pushing it, so an operator can disown stuck changes without first having to bring the target back online.  The optional `digest` is checked twice: once before the live-state fetch so a stale browser tab is rejected up-front, and again under the config lock so a parallel admin edit between fetch and write does not get silently overwritten.
	CreateClearPending(ctx context.Context, params *CreateClearPendingParams) (*CreateClearPendingResponse, error)
	// ListKeys GET /subscriptions/keys
	// List all subscription keys in the key pool the caller has audit access to.  Unbound pool entries are visible to anyone holding the system-AUDIT bit. Bound entries are additionally gated on per-remote `PRIV_RESOURCE_AUDIT` so that an operator who can audit the pool but not a specific remote does not learn which keys are pinned to it (and through that, the existence and rough size of that remote's deployment).
	ListKeys(ctx context.Context) (*ListKeysResponse, error)
	// CreateKeys POST /subscriptions/keys
	// Add one or more subscription keys to the pool.  The key prefix determines the product type via [`ProductType::from_key`]. The schema regex rejects anything that isn't a PVE or PBS key today; widen [`PRODUCT_KEY_REGEX`] in lockstep with `from_key` and `push_key_to_remote` when PMG/POM remote support lands.  Duplicate keys within the input are silently collapsed to a single entry; the dropped count is reported back so a CLI / API caller can tell pasting the same key twice apart from a genuine add. Keys already present in the pool are still a hard CONFLICT - that is operator-visible state, not an input typo. Apart from dedup the request stays all-or-nothing: a single bad prefix or an existing-pool collision fails the call and leaves the pool untouched.  The post-save digest is set on the response so clients can chain a follow-up mutation without a refetch round-trip.
	CreateKeys(ctx context.Context, params *CreateKeysParams) (*CreateKeysResponse, error)
	// DeleteKeys DELETE /subscriptions/keys/{key}
	// Remove a key from the pool.  If the key is currently assigned to a remote node, the caller must also have `PRIV_RESOURCE_MODIFY` on that remote, so an audit-only operator cannot release a key another admin had pinned. Refuses if the key is currently the live active key on its bound node, since dropping the pool entry would orphan that subscription on the remote: the operator must run Clear Key on the Node Subscription Status panel first.
	DeleteKeys(ctx context.Context, key string, params *DeleteKeysParams) error
	// GetKeys GET /subscriptions/keys/{key}
	// Get details for a single key.  Bound entries are hidden from operators who cannot audit the bound remote (mirrors the `list_keys` filter); the response is the same 404 either way so a probe cannot distinguish "key exists but you cannot see it" from "key not in pool".
	GetKeys(ctx context.Context, key string) (*GetKeysResponse, error)
	// DeleteKeysAssignment DELETE /subscriptions/keys/{key}/assignment
	// Drop the remote-node binding for a pool key.  Refuses when the binding is currently synced (the assigned key is the live active key on its remote): unassigning then would orphan that subscription, so the operator must run Clear Key on the Node Subscription Status panel first.
	DeleteKeysAssignment(ctx context.Context, key string, params *DeleteKeysAssignmentParams) error
	// CreateKeysAssignment POST /subscriptions/keys/{key}/assignment
	// Bind a pool key to a remote node.  `PRIV_SYS_MODIFY` lets the caller touch the pool config; per-remote `PRIV_RESOURCE_MODIFY` is enforced inside this handler so an operator cannot push a key to a remote they have no other authority on.
	CreateKeysAssignment(ctx context.Context, key string, params *CreateKeysAssignmentParams) error
	// ListNodeStatus GET /subscriptions/node-status
	// Get the subscription status of every remote node the caller can audit, combined with key pool assignment information.  Per-remote `PRIV_RESOURCE_AUDIT` is enforced inside the handler so users only see remotes they may audit.
	ListNodeStatus(ctx context.Context, params *ListNodeStatusParams) (*ListNodeStatusResponse, error)
	// CreateQueueClear POST /subscriptions/queue-clear
	// Queue a clear on a remote node, that is, mark its subscription for removal so the key can be reassigned elsewhere.  Sets `pending_clear` on the pool entry currently bound to (remote, node). Apply Pending later issues the DELETE on the remote and clears the binding on success; Discard Pending only resets the flag and leaves the binding intact so the operator can retry.  Refuses if no pool entry is bound to (remote, node): importing a foreign live subscription into the pool is the job of the explicit Adopt Key action, not a side effect of queueing a clear. The split keeps the audit trail honest; queueing a clear should only ever schedule a removal, never silently materialise new pool state the operator did not ask for.  Per-remote `PRIV_RESOURCE_MODIFY` is enforced inside the handler so an operator with global system access alone cannot tear down subscriptions on remotes they have no other authority on.
	CreateQueueClear(ctx context.Context, params *CreateQueueClearParams) error
	// CreateRevertPendingClear POST /subscriptions/revert-pending-clear
	// Drop a queued Clear Key on `remote`/`node` while keeping the binding intact.  Backs out a Queue Clear on a single node without going through the global Discard Pending path (which scrubs every pending change in the pool). The binding stays so the operator can retry the queueing or leave the live subscription untouched.
	CreateRevertPendingClear(ctx context.Context, params *CreateRevertPendingClearParams) error
}

// New constructs a Service backed by the given pkg/client.Client.
// The client owns authentication, TLS, retries, and logging; this
// service only translates between typed Go shapes and the raw client.
func New(c client.Client) Service {
	if c == nil {
		panic("subscriptions: New called with nil client")
	}
	return &service{c: c}
}

type service struct {
	c client.Client
}

// ListSubscriptions implements Service.ListSubscriptions. GET /subscriptions.
func (s *service) ListSubscriptions(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("subscriptions.ListSubscriptions: ctx must not be nil")
	}
	path := "/subscriptions"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("subscriptions.ListSubscriptions: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("subscriptions.ListSubscriptions: nil response from client")
	}
	_ = resp
	return nil
}

// CreateAdoptAllParams is the request payload for CreateAdoptAll.
type CreateAdoptAllParams struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
}

// CreateAdoptAllResponse mirrors the shape returned by POST /subscriptions/adopt-all.
type CreateAdoptAllResponse []json.RawMessage

// CreateAdoptAll implements Service.CreateAdoptAll. POST /subscriptions/adopt-all.
func (s *service) CreateAdoptAll(ctx context.Context, params *CreateAdoptAllParams) (*CreateAdoptAllResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("subscriptions.CreateAdoptAll: ctx must not be nil")
	}
	path := "/subscriptions/adopt-all"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("subscriptions.CreateAdoptAll: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("subscriptions.CreateAdoptAll: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateAdoptAll: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("subscriptions.CreateAdoptAll: nil response from client")
	}
	if resp.Data == nil {
		out := CreateAdoptAllResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateAdoptAll: re-marshal data: %w", err)
	}
	out := &CreateAdoptAllResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateAdoptAll: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateAdoptKeyParams is the request payload for CreateAdoptKey.
type CreateAdoptKeyParams struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Node Node name (or 'localhost')
	Node string `json:"node"`
	// Remote Remote ID.
	Remote string `json:"remote"`
}

// CreateAdoptKey implements Service.CreateAdoptKey. POST /subscriptions/adopt-key.
func (s *service) CreateAdoptKey(ctx context.Context, params *CreateAdoptKeyParams) error {
	if ctx == nil {
		return fmt.Errorf("subscriptions.CreateAdoptKey: ctx must not be nil")
	}
	path := "/subscriptions/adopt-key"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("subscriptions.CreateAdoptKey: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("subscriptions.CreateAdoptKey: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("subscriptions.CreateAdoptKey: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("subscriptions.CreateAdoptKey: nil response from client")
	}
	_ = resp
	return nil
}

// CreateApplyPendingParams is the request payload for CreateApplyPending.
type CreateApplyPendingParams struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
}

// CreateApplyPendingResponse is the raw JSON returned by POST /subscriptions/apply-pending.
type CreateApplyPendingResponse = json.RawMessage

// CreateApplyPending implements Service.CreateApplyPending. POST /subscriptions/apply-pending.
func (s *service) CreateApplyPending(ctx context.Context, params *CreateApplyPendingParams) (*CreateApplyPendingResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("subscriptions.CreateApplyPending: ctx must not be nil")
	}
	path := "/subscriptions/apply-pending"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("subscriptions.CreateApplyPending: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("subscriptions.CreateApplyPending: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateApplyPending: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("subscriptions.CreateApplyPending: nil response from client")
	}
	if resp.Data == nil {
		out := CreateApplyPendingResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateApplyPending: re-marshal data: %w", err)
	}
	out := &CreateApplyPendingResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateApplyPending: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateAutoAssignResponse mirrors the shape returned by POST /subscriptions/auto-assign.
type CreateAutoAssignResponse struct {
	// Assignments Proposed assignments. Empty when nothing matches.
	Assignments []json.RawMessage `json:"assignments"`
	// KeysDigest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	KeysDigest string `json:"keys-digest"`
	// NodeStatusDigest SHA-256 over the relevant slice of node status (sorted JSON) at proposal time.
	NodeStatusDigest string `json:"node-status-digest"`
}

// CreateAutoAssign implements Service.CreateAutoAssign. POST /subscriptions/auto-assign.
func (s *service) CreateAutoAssign(ctx context.Context) (*CreateAutoAssignResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("subscriptions.CreateAutoAssign: ctx must not be nil")
	}
	path := "/subscriptions/auto-assign"
	var body map[string]interface{}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateAutoAssign: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("subscriptions.CreateAutoAssign: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("subscriptions.CreateAutoAssign: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateAutoAssign: re-marshal data: %w", err)
	}
	out := &CreateAutoAssignResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateAutoAssign: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateBulkAssignParams is the request payload for CreateBulkAssign.
type CreateBulkAssignParams struct {
	// Proposal The full plan returned by auto-assign and accepted by bulk-assign.  `keys_digest` and `node_status_digest` are snapshots taken when the plan was computed. `bulk_assign` rejects the plan with 409 if either has changed in the meantime, so the operator never silently commits a plan that no longer matches the live state.
	Proposal json.RawMessage `json:"proposal"`
}

// CreateBulkAssignResponse mirrors the shape returned by POST /subscriptions/bulk-assign.
type CreateBulkAssignResponse []json.RawMessage

// CreateBulkAssign implements Service.CreateBulkAssign. POST /subscriptions/bulk-assign.
func (s *service) CreateBulkAssign(ctx context.Context, params *CreateBulkAssignParams) (*CreateBulkAssignResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("subscriptions.CreateBulkAssign: ctx must not be nil")
	}
	path := "/subscriptions/bulk-assign"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("subscriptions.CreateBulkAssign: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("subscriptions.CreateBulkAssign: decode params: %w", err)
		}
		if params.Proposal != nil {
			encoded, err := json.Marshal(params.Proposal)
			if err != nil {
				return nil, fmt.Errorf("subscriptions.CreateBulkAssign: encode proposal: %w", err)
			}
			body["proposal"] = string(encoded)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateBulkAssign: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("subscriptions.CreateBulkAssign: nil response from client")
	}
	if resp.Data == nil {
		out := CreateBulkAssignResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateBulkAssign: re-marshal data: %w", err)
	}
	out := &CreateBulkAssignResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateBulkAssign: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateCheckParams is the request payload for CreateCheck.
type CreateCheckParams struct {
	// Node Node name (or 'localhost')
	Node string `json:"node"`
	// Remote Remote ID.
	Remote string `json:"remote"`
}

// CreateCheck implements Service.CreateCheck. POST /subscriptions/check.
func (s *service) CreateCheck(ctx context.Context, params *CreateCheckParams) error {
	if ctx == nil {
		return fmt.Errorf("subscriptions.CreateCheck: ctx must not be nil")
	}
	path := "/subscriptions/check"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("subscriptions.CreateCheck: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("subscriptions.CreateCheck: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("subscriptions.CreateCheck: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("subscriptions.CreateCheck: nil response from client")
	}
	_ = resp
	return nil
}

// CreateClearPendingParams is the request payload for CreateClearPending.
type CreateClearPendingParams struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
}

// CreateClearPendingResponse mirrors the shape returned by POST /subscriptions/clear-pending.
type CreateClearPendingResponse struct {
	// Cleared Number of pool entries whose pending push or clear was cleared.
	Cleared client.PVEInt `json:"cleared"`
}

// CreateClearPending implements Service.CreateClearPending. POST /subscriptions/clear-pending.
func (s *service) CreateClearPending(ctx context.Context, params *CreateClearPendingParams) (*CreateClearPendingResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("subscriptions.CreateClearPending: ctx must not be nil")
	}
	path := "/subscriptions/clear-pending"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("subscriptions.CreateClearPending: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("subscriptions.CreateClearPending: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateClearPending: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("subscriptions.CreateClearPending: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("subscriptions.CreateClearPending: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateClearPending: re-marshal data: %w", err)
	}
	out := &CreateClearPendingResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateClearPending: unmarshal data: %w", err)
	}
	return out, nil
}

// ListKeysResponse mirrors the shape returned by GET /subscriptions/keys.
type ListKeysResponse []json.RawMessage

// ListKeys implements Service.ListKeys. GET /subscriptions/keys.
func (s *service) ListKeys(ctx context.Context) (*ListKeysResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("subscriptions.ListKeys: ctx must not be nil")
	}
	path := "/subscriptions/keys"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.ListKeys: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("subscriptions.ListKeys: nil response from client")
	}
	if resp.Data == nil {
		out := ListKeysResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.ListKeys: re-marshal data: %w", err)
	}
	out := &ListKeysResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.ListKeys: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateKeysParams is the request payload for CreateKeys.
type CreateKeysParams struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Keys Subscription keys to add to the pool.
	Keys []string `json:"keys"`
}

// CreateKeysResponse mirrors the shape returned by POST /subscriptions/keys.
type CreateKeysResponse struct {
	// Added Number of keys actually added to the pool.
	Added client.PVEInt `json:"added"`
	// Deduplicated Number of duplicate keys silently dropped from the input before adding.
	Deduplicated client.PVEInt `json:"deduplicated"`
}

// CreateKeys implements Service.CreateKeys. POST /subscriptions/keys.
func (s *service) CreateKeys(ctx context.Context, params *CreateKeysParams) (*CreateKeysResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("subscriptions.CreateKeys: ctx must not be nil")
	}
	path := "/subscriptions/keys"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("subscriptions.CreateKeys: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("subscriptions.CreateKeys: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateKeys: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("subscriptions.CreateKeys: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("subscriptions.CreateKeys: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateKeys: re-marshal data: %w", err)
	}
	out := &CreateKeysResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.CreateKeys: unmarshal data: %w", err)
	}
	return out, nil
}

// DeleteKeysParams is the request payload for DeleteKeys.
type DeleteKeysParams struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
}

// DeleteKeys implements Service.DeleteKeys. DELETE /subscriptions/keys/{key}.
func (s *service) DeleteKeys(ctx context.Context, key string, params *DeleteKeysParams) error {
	if ctx == nil {
		return fmt.Errorf("subscriptions.DeleteKeys: ctx must not be nil")
	}
	path := fmt.Sprintf("/subscriptions/keys/%s", url.PathEscape(key))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("subscriptions.DeleteKeys: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("subscriptions.DeleteKeys: decode params: %w", err)
		}
	}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("subscriptions.DeleteKeys: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("subscriptions.DeleteKeys: nil response from client")
	}
	_ = resp
	return nil
}

// GetKeysResponse mirrors the shape returned by GET /subscriptions/keys/{key}.
type GetKeysResponse struct {
	// CheckTime Epoch of last import or refresh of this key's data.  Accepts the upstream `checktime` spelling on deserialisation; canonical form is `check-time`.
	CheckTime *client.PVEInt `json:"check-time,omitempty"`
	// Key Subscription key.
	Key string `json:"key"`
	// Level Describes the level of subscription
	Level *string `json:"level,omitempty"`
	// NextDueDate Next due date.  Accepts the upstream `nextduedate` spelling on deserialisation so a future shop-bundle import path can hand a raw `SubscriptionInfo` blob through without a field-name translation step; canonical (and on-disk) form is `next-due-date` per the struct's kebab-case rename.
	NextDueDate *string `json:"next-due-date,omitempty"`
	// Node Node within the remote this key is assigned to (if any).
	Node *string `json:"node,omitempty"`
	// PendingClear True when the operator queued a clear for this entry's bound node, that is, a request to free the key from `remote`/`node` so it can be reassigned to a different node.  Apply Pending issues a DELETE on the remote and then clears `remote`/`node` on success. Discard Pending only resets this flag and leaves the binding untouched so the operator can retry. A bare flag is enough since the (remote, node) binding lives next to it.  Omitted from the serialised representation when false so the on-disk section and the API response do not carry `pending-clear false` lines for every entry.
	PendingClear *client.PVEBool `json:"pending-clear,omitempty"`
	// ProductName Product name.  Accepts the upstream `productname` spelling on deserialisation; canonical form is `product-name` to stay self-consistent with the sibling `product-type` field.
	ProductName *string `json:"product-name,omitempty"`
	// ProductType Proxmox product line a subscription key belongs to.
	ProductType string `json:"product-type"`
	// Remote Remote this key is assigned to (if any).
	Remote *string `json:"remote,omitempty"`
	// Serverid Server ID this key is bound to (from signed info, if available).
	Serverid *string `json:"serverid,omitempty"`
	// Source Origin of a subscription key entry.
	Source *string `json:"source,omitempty"`
	// Status Subscription status
	Status *string `json:"status,omitempty"`
}

// GetKeys implements Service.GetKeys. GET /subscriptions/keys/{key}.
func (s *service) GetKeys(ctx context.Context, key string) (*GetKeysResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("subscriptions.GetKeys: ctx must not be nil")
	}
	path := fmt.Sprintf("/subscriptions/keys/%s", url.PathEscape(key))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.GetKeys: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("subscriptions.GetKeys: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("subscriptions.GetKeys: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.GetKeys: re-marshal data: %w", err)
	}
	out := &GetKeysResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.GetKeys: unmarshal data: %w", err)
	}
	return out, nil
}

// DeleteKeysAssignmentParams is the request payload for DeleteKeysAssignment.
type DeleteKeysAssignmentParams struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
}

// DeleteKeysAssignment implements Service.DeleteKeysAssignment. DELETE /subscriptions/keys/{key}/assignment.
func (s *service) DeleteKeysAssignment(ctx context.Context, key string, params *DeleteKeysAssignmentParams) error {
	if ctx == nil {
		return fmt.Errorf("subscriptions.DeleteKeysAssignment: ctx must not be nil")
	}
	path := fmt.Sprintf("/subscriptions/keys/%s/assignment", url.PathEscape(key))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("subscriptions.DeleteKeysAssignment: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("subscriptions.DeleteKeysAssignment: decode params: %w", err)
		}
	}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("subscriptions.DeleteKeysAssignment: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("subscriptions.DeleteKeysAssignment: nil response from client")
	}
	_ = resp
	return nil
}

// CreateKeysAssignmentParams is the request payload for CreateKeysAssignment.
type CreateKeysAssignmentParams struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Node Node name (or 'localhost')
	Node string `json:"node"`
	// Remote Remote ID.
	Remote string `json:"remote"`
}

// CreateKeysAssignment implements Service.CreateKeysAssignment. POST /subscriptions/keys/{key}/assignment.
func (s *service) CreateKeysAssignment(ctx context.Context, key string, params *CreateKeysAssignmentParams) error {
	if ctx == nil {
		return fmt.Errorf("subscriptions.CreateKeysAssignment: ctx must not be nil")
	}
	path := fmt.Sprintf("/subscriptions/keys/%s/assignment", url.PathEscape(key))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("subscriptions.CreateKeysAssignment: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("subscriptions.CreateKeysAssignment: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("subscriptions.CreateKeysAssignment: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("subscriptions.CreateKeysAssignment: nil response from client")
	}
	_ = resp
	return nil
}

// ListNodeStatusParams is the request payload for ListNodeStatus.
type ListNodeStatusParams struct {
	// MaxAge Override the cache freshness window in seconds. Default 300 for panel views; pass 0 to force a fresh query.
	MaxAge *int64 `json:"max-age,omitempty"`
}

// ListNodeStatusResponse mirrors the shape returned by GET /subscriptions/node-status.
type ListNodeStatusResponse []json.RawMessage

// ListNodeStatus implements Service.ListNodeStatus. GET /subscriptions/node-status.
func (s *service) ListNodeStatus(ctx context.Context, params *ListNodeStatusParams) (*ListNodeStatusResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("subscriptions.ListNodeStatus: ctx must not be nil")
	}
	path := "/subscriptions/node-status"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("subscriptions.ListNodeStatus: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("subscriptions.ListNodeStatus: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.ListNodeStatus: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("subscriptions.ListNodeStatus: nil response from client")
	}
	if resp.Data == nil {
		out := ListNodeStatusResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.ListNodeStatus: re-marshal data: %w", err)
	}
	out := &ListNodeStatusResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("subscriptions.ListNodeStatus: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateQueueClearParams is the request payload for CreateQueueClear.
type CreateQueueClearParams struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Node Node name (or 'localhost')
	Node string `json:"node"`
	// Remote Remote ID.
	Remote string `json:"remote"`
}

// CreateQueueClear implements Service.CreateQueueClear. POST /subscriptions/queue-clear.
func (s *service) CreateQueueClear(ctx context.Context, params *CreateQueueClearParams) error {
	if ctx == nil {
		return fmt.Errorf("subscriptions.CreateQueueClear: ctx must not be nil")
	}
	path := "/subscriptions/queue-clear"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("subscriptions.CreateQueueClear: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("subscriptions.CreateQueueClear: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("subscriptions.CreateQueueClear: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("subscriptions.CreateQueueClear: nil response from client")
	}
	_ = resp
	return nil
}

// CreateRevertPendingClearParams is the request payload for CreateRevertPendingClear.
type CreateRevertPendingClearParams struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Node Node name (or 'localhost')
	Node string `json:"node"`
	// Remote Remote ID.
	Remote string `json:"remote"`
}

// CreateRevertPendingClear implements Service.CreateRevertPendingClear. POST /subscriptions/revert-pending-clear.
func (s *service) CreateRevertPendingClear(ctx context.Context, params *CreateRevertPendingClearParams) error {
	if ctx == nil {
		return fmt.Errorf("subscriptions.CreateRevertPendingClear: ctx must not be nil")
	}
	path := "/subscriptions/revert-pending-clear"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("subscriptions.CreateRevertPendingClear: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("subscriptions.CreateRevertPendingClear: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("subscriptions.CreateRevertPendingClear: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("subscriptions.CreateRevertPendingClear: nil response from client")
	}
	_ = resp
	return nil
}
