// Code generated by cmd/pvegen. DO NOT EDIT.

// Package version exposes typed bindings for the PVE /version endpoint family.
package version

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/fivetwenty-io/pve-apiclient-go/v3/pkg/client"
)

var _ = strings.TrimPrefix
var _ = json.RawMessage(nil)
var _ = url.PathEscape
var _ = sort.Ints
var _ = strconv.Itoa

// Service exposes typed operations on the /version endpoint family.
type Service interface {
	// Get GET /version
	// API version details, including some parts of the global datacenter config.
	Get(ctx context.Context) (*GetResponse, error)
}

// New constructs a Service backed by the given pkg/client.Client.
// The client owns authentication, TLS, retries, and logging; this
// service only translates between typed Go shapes and the raw client.
func New(c client.Client) Service {
	if c == nil {
		panic("version: New called with nil client")
	}
	return &service{c: c}
}

type service struct {
	c client.Client
}

// GetResponse mirrors the shape returned by GET /version.
type GetResponse struct {
	// Console The default console viewer to use.
	Console *string `json:"console,omitempty"`
	// Release The current Proxmox VE point release in `x.y` format.
	Release string `json:"release"`
	// Repoid The short git revision from which this version was build.
	Repoid string `json:"repoid"`
	// Version The full pve-manager package version of this node.
	Version string `json:"version"`
}

// Get implements Service.Get. GET /version.
func (s *service) Get(ctx context.Context) (*GetResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("version.Get: ctx must not be nil")
	}
	path := "/version"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("version.Get: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("version.Get: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("version.Get: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("version.Get: re-marshal data: %w", err)
	}
	out := &GetResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("version.Get: unmarshal data: %w", err)
	}
	return out, nil
}
