// Code generated by cmd/pvegen. DO NOT EDIT.

package pve_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"sync"
	"testing"

	pveclient "github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/pdm/pve"
)

var _ = json.RawMessage(nil)

func smokeOptsFromServerURL(u string) pveclient.Options {
	parsed, err := url.Parse(u)
	if err != nil {
		panic("test setup: invalid server URL: " + err.Error())
	}

	host := parsed.Hostname()

	port := 0
	if p := parsed.Port(); p != "" {
		port, _ = strconv.Atoi(p)
	}

	return pveclient.Options{
		Host:     host,
		Port:     port,
		Protocol: "http",
		APIToken: "user@pam!tok=sec",
	}
}

// recordedRequest captures what the mock server observed for the most
// recently dispatched request.
type recordedRequest struct {
	method string
	path   string
	query  url.Values
	form   url.Values
}

// testHarness runs a single httptest.Server shared by every subtest in this
// file. Subtests are never run in parallel (each sets the desired response
// immediately before invoking the method under test, then reads back the
// recorded request), so the mutex below only guards against the harness
// goroutine and the test goroutine overlapping on a single in-flight
// request, never against concurrent subtests.
type testHarness struct {
	mu       sync.Mutex
	last     recordedRequest
	nextCode int
	nextBody string
}

// newTestHarness starts the mock server and returns it alongside the harness
// used to configure responses and inspect recorded requests.
func newTestHarness() (*httptest.Server, *testHarness) {
	h := &testHarness{nextCode: http.StatusOK}

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		h.mu.Lock()
		defer h.mu.Unlock()

		_ = r.ParseForm()
		h.last = recordedRequest{
			method: r.Method,
			path:   r.URL.Path,
			query:  r.URL.Query(),
			form:   r.PostForm,
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(h.nextCode)
		_, _ = w.Write([]byte(h.nextBody))
	}))

	return srv, h
}

// set configures the status code and body the next request will receive.
func (h *testHarness) set(code int, body string) {
	h.mu.Lock()
	defer h.mu.Unlock()

	h.nextCode = code
	h.nextBody = body
}

// snapshot returns a copy of the most recently recorded request.
func (h *testHarness) snapshot() recordedRequest {
	h.mu.Lock()
	defer h.mu.Unlock()

	return h.last
}

// assertRequestLine fails the test when the recorded method or resolved
// path does not exactly match what the endpoint's spec entry declares.
func assertRequestLine(t *testing.T, got recordedRequest, wantMethod, wantPath string) {
	t.Helper()

	if got.method != wantMethod {
		t.Errorf("method = %q, want %q", got.method, wantMethod)
	}

	if got.path != wantPath {
		t.Errorf("path = %q, want %q", got.path, wantPath)
	}
}

// assertParamValue fails the test when the wire-encoded value of key does
// not exactly equal want.
func assertParamValue(t *testing.T, values url.Values, key, want string) {
	t.Helper()

	if got := values.Get(key); got != want {
		t.Errorf("param %q = %q, want %q", key, got, want)
	}
}

// assertParamPresent fails the test when key is absent from values. Used for
// required parameters whose wire encoding is not a simple comparable string
// (e.g. json.RawMessage-typed fields).
func assertParamPresent(t *testing.T, values url.Values, key string) {
	t.Helper()

	if _, ok := values[key]; !ok {
		t.Errorf("param %q missing from request", key)
	}
}

func TestGenerated_Pve_Methods(t *testing.T) {
	srv, harness := newTestHarness()
	defer srv.Close()

	c, err := pveclient.NewClient(smokeOptsFromServerURL(srv.URL))
	if err != nil {
		t.Fatalf("NewClient: %v", err)
	}

	svc := pve.New(c)
	ctx := context.Background()

	t.Run("ListPve", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListPve(ctx)
		if err != nil {
			t.Fatalf("ListPve: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve")

		var nilCtx context.Context
		if err := svc.ListPve(nilCtx); err == nil {
			t.Errorf("ListPve: expected error for nil context, got nil")
		}
	})
	t.Run("ListFirewall", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListFirewall(ctx)
		if err != nil {
			t.Fatalf("ListFirewall: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/firewall")

		var nilCtx context.Context
		if err := svc.ListFirewall(nilCtx); err == nil {
			t.Errorf("ListFirewall: expected error for nil context, got nil")
		}
	})
	t.Run("ListFirewallStatus", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListFirewallStatus(ctx)
		if err != nil {
			t.Fatalf("ListFirewallStatus: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListFirewallStatus: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/firewall/status")

		var nilCtx context.Context
		if _, err := svc.ListFirewallStatus(nilCtx); err == nil {
			t.Errorf("ListFirewallStatus: expected error for nil context, got nil")
		}
	})
	t.Run("CreateProbeTls", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateProbeTls(ctx, &pve.CreateProbeTlsParams{Hostname: "sample-hostname"})
		if err != nil {
			t.Fatalf("CreateProbeTls: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/probe-tls")
		assertParamValue(t, got.form, "hostname", "sample-hostname")

		var nilCtx context.Context
		if err := svc.CreateProbeTls(nilCtx, &pve.CreateProbeTlsParams{Hostname: "sample-hostname"}); err == nil {
			t.Errorf("CreateProbeTls: expected error for nil context, got nil")
		}
	})
	t.Run("ListRealms", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRealms(ctx, &pve.ListRealmsParams{Hostname: "sample-hostname"})
		if err != nil {
			t.Fatalf("ListRealms: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRealms: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/realms")
		assertParamValue(t, got.query, "hostname", "sample-hostname")

		var nilCtx context.Context
		if _, err := svc.ListRealms(nilCtx, &pve.ListRealmsParams{Hostname: "sample-hostname"}); err == nil {
			t.Errorf("ListRealms: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotes", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotes(ctx)
		if err != nil {
			t.Fatalf("ListRemotes: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotes: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes")

		var nilCtx context.Context
		if _, err := svc.ListRemotes(nilCtx); err == nil {
			t.Errorf("ListRemotes: expected error for nil context, got nil")
		}
	})
	t.Run("GetRemotes", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.GetRemotes(ctx, "sample-remote")
		if err != nil {
			t.Fatalf("GetRemotes: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote")

		var nilCtx context.Context
		if err := svc.GetRemotes(nilCtx, "sample-remote"); err == nil {
			t.Errorf("GetRemotes: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesClusterNextid", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesClusterNextid(ctx, "sample-remote", &pve.ListRemotesClusterNextidParams{})
		if err != nil {
			t.Fatalf("ListRemotesClusterNextid: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesClusterNextid: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/cluster-nextid")

		var nilCtx context.Context
		if _, err := svc.ListRemotesClusterNextid(nilCtx, "sample-remote", &pve.ListRemotesClusterNextidParams{}); err == nil {
			t.Errorf("ListRemotesClusterNextid: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesClusterStatus", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesClusterStatus(ctx, "sample-remote", &pve.ListRemotesClusterStatusParams{})
		if err != nil {
			t.Fatalf("ListRemotesClusterStatus: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesClusterStatus: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/cluster-status")

		var nilCtx context.Context
		if _, err := svc.ListRemotesClusterStatus(nilCtx, "sample-remote", &pve.ListRemotesClusterStatusParams{}); err == nil {
			t.Errorf("ListRemotesClusterStatus: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesFirewall", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListRemotesFirewall(ctx, "sample-remote")
		if err != nil {
			t.Fatalf("ListRemotesFirewall: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/firewall")

		var nilCtx context.Context
		if err := svc.ListRemotesFirewall(nilCtx, "sample-remote"); err == nil {
			t.Errorf("ListRemotesFirewall: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesFirewallOptions", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesFirewallOptions(ctx, "sample-remote")
		if err != nil {
			t.Fatalf("ListRemotesFirewallOptions: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesFirewallOptions: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/firewall/options")

		var nilCtx context.Context
		if _, err := svc.ListRemotesFirewallOptions(nilCtx, "sample-remote"); err == nil {
			t.Errorf("ListRemotesFirewallOptions: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateRemotesFirewallOptions", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateRemotesFirewallOptions(ctx, "sample-remote", &pve.UpdateRemotesFirewallOptionsParams{})
		if err != nil {
			t.Fatalf("UpdateRemotesFirewallOptions: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/pve/remotes/sample-remote/firewall/options")

		var nilCtx context.Context
		if err := svc.UpdateRemotesFirewallOptions(nilCtx, "sample-remote", &pve.UpdateRemotesFirewallOptionsParams{}); err == nil {
			t.Errorf("UpdateRemotesFirewallOptions: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesFirewallRules", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesFirewallRules(ctx, "sample-remote")
		if err != nil {
			t.Fatalf("ListRemotesFirewallRules: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesFirewallRules: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/firewall/rules")

		var nilCtx context.Context
		if _, err := svc.ListRemotesFirewallRules(nilCtx, "sample-remote"); err == nil {
			t.Errorf("ListRemotesFirewallRules: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesFirewallStatus", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesFirewallStatus(ctx, "sample-remote")
		if err != nil {
			t.Fatalf("ListRemotesFirewallStatus: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesFirewallStatus: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/firewall/status")

		var nilCtx context.Context
		if _, err := svc.ListRemotesFirewallStatus(nilCtx, "sample-remote"); err == nil {
			t.Errorf("ListRemotesFirewallStatus: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesLxc", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesLxc(ctx, "sample-remote", &pve.ListRemotesLxcParams{})
		if err != nil {
			t.Fatalf("ListRemotesLxc: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesLxc: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/lxc")

		var nilCtx context.Context
		if _, err := svc.ListRemotesLxc(nilCtx, "sample-remote", &pve.ListRemotesLxcParams{}); err == nil {
			t.Errorf("ListRemotesLxc: expected error for nil context, got nil")
		}
	})
	t.Run("GetRemotesLxc", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.GetRemotesLxc(ctx, "sample-remote", "sample-vmid")
		if err != nil {
			t.Fatalf("GetRemotesLxc: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid")

		var nilCtx context.Context
		if err := svc.GetRemotesLxc(nilCtx, "sample-remote", "sample-vmid"); err == nil {
			t.Errorf("GetRemotesLxc: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesLxcConfig", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesLxcConfig(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcConfigParams{State: "sample-state"})
		if err != nil {
			t.Fatalf("ListRemotesLxcConfig: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesLxcConfig: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/config")
		assertParamValue(t, got.query, "state", "sample-state")

		var nilCtx context.Context
		if _, err := svc.ListRemotesLxcConfig(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcConfigParams{State: "sample-state"}); err == nil {
			t.Errorf("ListRemotesLxcConfig: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesLxcFirewall", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListRemotesLxcFirewall(ctx, "sample-remote", "sample-vmid")
		if err != nil {
			t.Fatalf("ListRemotesLxcFirewall: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/firewall")

		var nilCtx context.Context
		if err := svc.ListRemotesLxcFirewall(nilCtx, "sample-remote", "sample-vmid"); err == nil {
			t.Errorf("ListRemotesLxcFirewall: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesLxcFirewallOptions", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesLxcFirewallOptions(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcFirewallOptionsParams{})
		if err != nil {
			t.Fatalf("ListRemotesLxcFirewallOptions: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesLxcFirewallOptions: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/firewall/options")

		var nilCtx context.Context
		if _, err := svc.ListRemotesLxcFirewallOptions(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcFirewallOptionsParams{}); err == nil {
			t.Errorf("ListRemotesLxcFirewallOptions: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateRemotesLxcFirewallOptions", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateRemotesLxcFirewallOptions(ctx, "sample-remote", "sample-vmid", &pve.UpdateRemotesLxcFirewallOptionsParams{})
		if err != nil {
			t.Fatalf("UpdateRemotesLxcFirewallOptions: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/firewall/options")

		var nilCtx context.Context
		if err := svc.UpdateRemotesLxcFirewallOptions(nilCtx, "sample-remote", "sample-vmid", &pve.UpdateRemotesLxcFirewallOptionsParams{}); err == nil {
			t.Errorf("UpdateRemotesLxcFirewallOptions: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesLxcFirewallRules", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesLxcFirewallRules(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcFirewallRulesParams{})
		if err != nil {
			t.Fatalf("ListRemotesLxcFirewallRules: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesLxcFirewallRules: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/firewall/rules")

		var nilCtx context.Context
		if _, err := svc.ListRemotesLxcFirewallRules(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcFirewallRulesParams{}); err == nil {
			t.Errorf("ListRemotesLxcFirewallRules: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesLxcMigrate", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesLxcMigrate(ctx, "sample-remote", "sample-vmid", &pve.CreateRemotesLxcMigrateParams{Target: "sample-target"})
		if err != nil {
			t.Fatalf("CreateRemotesLxcMigrate: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesLxcMigrate: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/migrate")
		assertParamValue(t, got.form, "target", "sample-target")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesLxcMigrate(nilCtx, "sample-remote", "sample-vmid", &pve.CreateRemotesLxcMigrateParams{Target: "sample-target"}); err == nil {
			t.Errorf("CreateRemotesLxcMigrate: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesLxcPending", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesLxcPending(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcPendingParams{})
		if err != nil {
			t.Fatalf("ListRemotesLxcPending: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesLxcPending: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/pending")

		var nilCtx context.Context
		if _, err := svc.ListRemotesLxcPending(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcPendingParams{}); err == nil {
			t.Errorf("ListRemotesLxcPending: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesLxcRemoteMigrate", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesLxcRemoteMigrate(ctx, "sample-remote", "sample-vmid", &pve.CreateRemotesLxcRemoteMigrateParams{Target: "sample-target", TargetBridge: []string{"sample-target-bridge"}, TargetStorage: []string{"sample-target-storage"}})
		if err != nil {
			t.Fatalf("CreateRemotesLxcRemoteMigrate: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesLxcRemoteMigrate: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/remote-migrate")
		assertParamValue(t, got.form, "target", "sample-target")
		assertParamValue(t, got.form, "target-bridge", "sample-target-bridge")
		assertParamValue(t, got.form, "target-storage", "sample-target-storage")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesLxcRemoteMigrate(nilCtx, "sample-remote", "sample-vmid", &pve.CreateRemotesLxcRemoteMigrateParams{Target: "sample-target", TargetBridge: []string{"sample-target-bridge"}, TargetStorage: []string{"sample-target-storage"}}); err == nil {
			t.Errorf("CreateRemotesLxcRemoteMigrate: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesLxcRrddata", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesLxcRrddata(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcRrddataParams{Cf: "sample-cf", Timeframe: "sample-timeframe"})
		if err != nil {
			t.Fatalf("ListRemotesLxcRrddata: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesLxcRrddata: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/rrddata")
		assertParamValue(t, got.query, "cf", "sample-cf")
		assertParamValue(t, got.query, "timeframe", "sample-timeframe")

		var nilCtx context.Context
		if _, err := svc.ListRemotesLxcRrddata(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcRrddataParams{Cf: "sample-cf", Timeframe: "sample-timeframe"}); err == nil {
			t.Errorf("ListRemotesLxcRrddata: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesLxcShutdown", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesLxcShutdown(ctx, "sample-remote", "sample-vmid", &pve.CreateRemotesLxcShutdownParams{})
		if err != nil {
			t.Fatalf("CreateRemotesLxcShutdown: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesLxcShutdown: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/shutdown")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesLxcShutdown(nilCtx, "sample-remote", "sample-vmid", &pve.CreateRemotesLxcShutdownParams{}); err == nil {
			t.Errorf("CreateRemotesLxcShutdown: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesLxcSnapshot", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesLxcSnapshot(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcSnapshotParams{})
		if err != nil {
			t.Fatalf("ListRemotesLxcSnapshot: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesLxcSnapshot: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/snapshot")

		var nilCtx context.Context
		if _, err := svc.ListRemotesLxcSnapshot(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcSnapshotParams{}); err == nil {
			t.Errorf("ListRemotesLxcSnapshot: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesLxcSnapshot", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesLxcSnapshot(ctx, "sample-remote", "sample-vmid", &pve.CreateRemotesLxcSnapshotParams{Snapname: "sample-snapname"})
		if err != nil {
			t.Fatalf("CreateRemotesLxcSnapshot: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesLxcSnapshot: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/snapshot")
		assertParamValue(t, got.form, "snapname", "sample-snapname")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesLxcSnapshot(nilCtx, "sample-remote", "sample-vmid", &pve.CreateRemotesLxcSnapshotParams{Snapname: "sample-snapname"}); err == nil {
			t.Errorf("CreateRemotesLxcSnapshot: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteRemotesLxcSnapshot", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.DeleteRemotesLxcSnapshot(ctx, "sample-remote", "sample-vmid", "sample-snapname", &pve.DeleteRemotesLxcSnapshotParams{})
		if err != nil {
			t.Fatalf("DeleteRemotesLxcSnapshot: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("DeleteRemotesLxcSnapshot: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/snapshot/sample-snapname")

		var nilCtx context.Context
		if _, err := svc.DeleteRemotesLxcSnapshot(nilCtx, "sample-remote", "sample-vmid", "sample-snapname", &pve.DeleteRemotesLxcSnapshotParams{}); err == nil {
			t.Errorf("DeleteRemotesLxcSnapshot: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateRemotesLxcSnapshotConfig", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateRemotesLxcSnapshotConfig(ctx, "sample-remote", "sample-vmid", "sample-snapname", &pve.UpdateRemotesLxcSnapshotConfigParams{})
		if err != nil {
			t.Fatalf("UpdateRemotesLxcSnapshotConfig: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/snapshot/sample-snapname/config")

		var nilCtx context.Context
		if err := svc.UpdateRemotesLxcSnapshotConfig(nilCtx, "sample-remote", "sample-vmid", "sample-snapname", &pve.UpdateRemotesLxcSnapshotConfigParams{}); err == nil {
			t.Errorf("UpdateRemotesLxcSnapshotConfig: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesLxcSnapshotRollback", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesLxcSnapshotRollback(ctx, "sample-remote", "sample-vmid", "sample-snapname", &pve.CreateRemotesLxcSnapshotRollbackParams{})
		if err != nil {
			t.Fatalf("CreateRemotesLxcSnapshotRollback: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesLxcSnapshotRollback: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/snapshot/sample-snapname/rollback")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesLxcSnapshotRollback(nilCtx, "sample-remote", "sample-vmid", "sample-snapname", &pve.CreateRemotesLxcSnapshotRollbackParams{}); err == nil {
			t.Errorf("CreateRemotesLxcSnapshotRollback: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesLxcStart", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesLxcStart(ctx, "sample-remote", "sample-vmid", &pve.CreateRemotesLxcStartParams{})
		if err != nil {
			t.Fatalf("CreateRemotesLxcStart: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesLxcStart: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/start")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesLxcStart(nilCtx, "sample-remote", "sample-vmid", &pve.CreateRemotesLxcStartParams{}); err == nil {
			t.Errorf("CreateRemotesLxcStart: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesLxcStatus", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesLxcStatus(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcStatusParams{})
		if err != nil {
			t.Fatalf("ListRemotesLxcStatus: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesLxcStatus: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/status")

		var nilCtx context.Context
		if _, err := svc.ListRemotesLxcStatus(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcStatusParams{}); err == nil {
			t.Errorf("ListRemotesLxcStatus: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesLxcStop", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesLxcStop(ctx, "sample-remote", "sample-vmid", &pve.CreateRemotesLxcStopParams{})
		if err != nil {
			t.Fatalf("CreateRemotesLxcStop: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesLxcStop: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/stop")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesLxcStop(nilCtx, "sample-remote", "sample-vmid", &pve.CreateRemotesLxcStopParams{}); err == nil {
			t.Errorf("CreateRemotesLxcStop: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesLxcTermproxy", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesLxcTermproxy(ctx, "sample-remote", "sample-vmid")
		if err != nil {
			t.Fatalf("CreateRemotesLxcTermproxy: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesLxcTermproxy: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/termproxy")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesLxcTermproxy(nilCtx, "sample-remote", "sample-vmid"); err == nil {
			t.Errorf("CreateRemotesLxcTermproxy: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesLxcVncwebsocket", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListRemotesLxcVncwebsocket(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcVncwebsocketParams{Port: 42, Vncticket: "sample-vncticket"})
		if err != nil {
			t.Fatalf("ListRemotesLxcVncwebsocket: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/lxc/sample-vmid/vncwebsocket")
		assertParamValue(t, got.query, "port", "42")
		assertParamValue(t, got.query, "vncticket", "sample-vncticket")

		var nilCtx context.Context
		if err := svc.ListRemotesLxcVncwebsocket(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesLxcVncwebsocketParams{Port: 42, Vncticket: "sample-vncticket"}); err == nil {
			t.Errorf("ListRemotesLxcVncwebsocket: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodes", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesNodes(ctx, "sample-remote")
		if err != nil {
			t.Fatalf("ListRemotesNodes: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodes: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodes(nilCtx, "sample-remote"); err == nil {
			t.Errorf("ListRemotesNodes: expected error for nil context, got nil")
		}
	})
	t.Run("GetRemotesNodes", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.GetRemotesNodes(ctx, "sample-remote", "sample-node")
		if err != nil {
			t.Fatalf("GetRemotesNodes: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node")

		var nilCtx context.Context
		if err := svc.GetRemotesNodes(nilCtx, "sample-remote", "sample-node"); err == nil {
			t.Errorf("GetRemotesNodes: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesApt", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListRemotesNodesApt(ctx, "sample-remote", "sample-node")
		if err != nil {
			t.Fatalf("ListRemotesNodesApt: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/apt")

		var nilCtx context.Context
		if err := svc.ListRemotesNodesApt(nilCtx, "sample-remote", "sample-node"); err == nil {
			t.Errorf("ListRemotesNodesApt: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesAptChangelog", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesNodesAptChangelog(ctx, "sample-remote", "sample-node", &pve.ListRemotesNodesAptChangelogParams{Name: "sample-name"})
		if err != nil {
			t.Fatalf("ListRemotesNodesAptChangelog: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesAptChangelog: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/apt/changelog")
		assertParamValue(t, got.query, "name", "sample-name")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesAptChangelog(nilCtx, "sample-remote", "sample-node", &pve.ListRemotesNodesAptChangelogParams{Name: "sample-name"}); err == nil {
			t.Errorf("ListRemotesNodesAptChangelog: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesAptRepositories", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesNodesAptRepositories(ctx, "sample-remote", "sample-node")
		if err != nil {
			t.Fatalf("ListRemotesNodesAptRepositories: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesAptRepositories: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/apt/repositories")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesAptRepositories(nilCtx, "sample-remote", "sample-node"); err == nil {
			t.Errorf("ListRemotesNodesAptRepositories: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesAptUpdate", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesNodesAptUpdate(ctx, "sample-remote", "sample-node")
		if err != nil {
			t.Fatalf("ListRemotesNodesAptUpdate: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesAptUpdate: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/apt/update")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesAptUpdate(nilCtx, "sample-remote", "sample-node"); err == nil {
			t.Errorf("ListRemotesNodesAptUpdate: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesNodesAptUpdate", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesNodesAptUpdate(ctx, "sample-remote", "sample-node")
		if err != nil {
			t.Fatalf("CreateRemotesNodesAptUpdate: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesNodesAptUpdate: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/apt/update")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesNodesAptUpdate(nilCtx, "sample-remote", "sample-node"); err == nil {
			t.Errorf("CreateRemotesNodesAptUpdate: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesConfig", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesNodesConfig(ctx, "sample-remote", "sample-node")
		if err != nil {
			t.Fatalf("ListRemotesNodesConfig: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesConfig: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/config")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesConfig(nilCtx, "sample-remote", "sample-node"); err == nil {
			t.Errorf("ListRemotesNodesConfig: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesFirewall", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListRemotesNodesFirewall(ctx, "sample-remote", "sample-node")
		if err != nil {
			t.Fatalf("ListRemotesNodesFirewall: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/firewall")

		var nilCtx context.Context
		if err := svc.ListRemotesNodesFirewall(nilCtx, "sample-remote", "sample-node"); err == nil {
			t.Errorf("ListRemotesNodesFirewall: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesFirewallOptions", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesNodesFirewallOptions(ctx, "sample-remote", "sample-node")
		if err != nil {
			t.Fatalf("ListRemotesNodesFirewallOptions: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesFirewallOptions: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/firewall/options")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesFirewallOptions(nilCtx, "sample-remote", "sample-node"); err == nil {
			t.Errorf("ListRemotesNodesFirewallOptions: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateRemotesNodesFirewallOptions", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateRemotesNodesFirewallOptions(ctx, "sample-remote", "sample-node", &pve.UpdateRemotesNodesFirewallOptionsParams{})
		if err != nil {
			t.Fatalf("UpdateRemotesNodesFirewallOptions: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/firewall/options")

		var nilCtx context.Context
		if err := svc.UpdateRemotesNodesFirewallOptions(nilCtx, "sample-remote", "sample-node", &pve.UpdateRemotesNodesFirewallOptionsParams{}); err == nil {
			t.Errorf("UpdateRemotesNodesFirewallOptions: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesFirewallRules", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesNodesFirewallRules(ctx, "sample-remote", "sample-node")
		if err != nil {
			t.Fatalf("ListRemotesNodesFirewallRules: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesFirewallRules: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/firewall/rules")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesFirewallRules(nilCtx, "sample-remote", "sample-node"); err == nil {
			t.Errorf("ListRemotesNodesFirewallRules: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesFirewallStatus", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesNodesFirewallStatus(ctx, "sample-remote", "sample-node")
		if err != nil {
			t.Fatalf("ListRemotesNodesFirewallStatus: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesFirewallStatus: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/firewall/status")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesFirewallStatus(nilCtx, "sample-remote", "sample-node"); err == nil {
			t.Errorf("ListRemotesNodesFirewallStatus: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesNetwork", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesNodesNetwork(ctx, "sample-remote", "sample-node", &pve.ListRemotesNodesNetworkParams{})
		if err != nil {
			t.Fatalf("ListRemotesNodesNetwork: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesNetwork: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/network")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesNetwork(nilCtx, "sample-remote", "sample-node", &pve.ListRemotesNodesNetworkParams{}); err == nil {
			t.Errorf("ListRemotesNodesNetwork: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesRrddata", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesNodesRrddata(ctx, "sample-remote", "sample-node", &pve.ListRemotesNodesRrddataParams{Cf: "sample-cf", Timeframe: "sample-timeframe"})
		if err != nil {
			t.Fatalf("ListRemotesNodesRrddata: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesRrddata: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/rrddata")
		assertParamValue(t, got.query, "cf", "sample-cf")
		assertParamValue(t, got.query, "timeframe", "sample-timeframe")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesRrddata(nilCtx, "sample-remote", "sample-node", &pve.ListRemotesNodesRrddataParams{Cf: "sample-cf", Timeframe: "sample-timeframe"}); err == nil {
			t.Errorf("ListRemotesNodesRrddata: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesSdn", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListRemotesNodesSdn(ctx, "sample-remote", "sample-node")
		if err != nil {
			t.Fatalf("ListRemotesNodesSdn: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/sdn")

		var nilCtx context.Context
		if err := svc.ListRemotesNodesSdn(nilCtx, "sample-remote", "sample-node"); err == nil {
			t.Errorf("ListRemotesNodesSdn: expected error for nil context, got nil")
		}
	})
	t.Run("GetRemotesNodesSdnVnets", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.GetRemotesNodesSdnVnets(ctx, "sample-remote", "sample-node", "sample-vnet")
		if err != nil {
			t.Fatalf("GetRemotesNodesSdnVnets: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/sdn/vnets/sample-vnet")

		var nilCtx context.Context
		if err := svc.GetRemotesNodesSdnVnets(nilCtx, "sample-remote", "sample-node", "sample-vnet"); err == nil {
			t.Errorf("GetRemotesNodesSdnVnets: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesSdnVnetsMacVrf", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesNodesSdnVnetsMacVrf(ctx, "sample-remote", "sample-node", "sample-vnet")
		if err != nil {
			t.Fatalf("ListRemotesNodesSdnVnetsMacVrf: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesSdnVnetsMacVrf: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/sdn/vnets/sample-vnet/mac-vrf")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesSdnVnetsMacVrf(nilCtx, "sample-remote", "sample-node", "sample-vnet"); err == nil {
			t.Errorf("ListRemotesNodesSdnVnetsMacVrf: expected error for nil context, got nil")
		}
	})
	t.Run("GetRemotesNodesSdnZones", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.GetRemotesNodesSdnZones(ctx, "sample-remote", "sample-node", "sample-zone")
		if err != nil {
			t.Fatalf("GetRemotesNodesSdnZones: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/sdn/zones/sample-zone")

		var nilCtx context.Context
		if err := svc.GetRemotesNodesSdnZones(nilCtx, "sample-remote", "sample-node", "sample-zone"); err == nil {
			t.Errorf("GetRemotesNodesSdnZones: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesSdnZonesIpVrf", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesNodesSdnZonesIpVrf(ctx, "sample-remote", "sample-node", "sample-zone")
		if err != nil {
			t.Fatalf("ListRemotesNodesSdnZonesIpVrf: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesSdnZonesIpVrf: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/sdn/zones/sample-zone/ip-vrf")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesSdnZonesIpVrf(nilCtx, "sample-remote", "sample-node", "sample-zone"); err == nil {
			t.Errorf("ListRemotesNodesSdnZonesIpVrf: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesStatus", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesNodesStatus(ctx, "sample-remote", "sample-node")
		if err != nil {
			t.Fatalf("ListRemotesNodesStatus: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesStatus: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/status")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesStatus(nilCtx, "sample-remote", "sample-node"); err == nil {
			t.Errorf("ListRemotesNodesStatus: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesStorage", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesNodesStorage(ctx, "sample-remote", "sample-node", &pve.ListRemotesNodesStorageParams{})
		if err != nil {
			t.Fatalf("ListRemotesNodesStorage: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesStorage: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/storage")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesStorage(nilCtx, "sample-remote", "sample-node", &pve.ListRemotesNodesStorageParams{}); err == nil {
			t.Errorf("ListRemotesNodesStorage: expected error for nil context, got nil")
		}
	})
	t.Run("GetRemotesNodesStorage", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.GetRemotesNodesStorage(ctx, "sample-remote", "sample-node", "sample-storage")
		if err != nil {
			t.Fatalf("GetRemotesNodesStorage: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/storage/sample-storage")

		var nilCtx context.Context
		if err := svc.GetRemotesNodesStorage(nilCtx, "sample-remote", "sample-node", "sample-storage"); err == nil {
			t.Errorf("GetRemotesNodesStorage: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesStorageRrddata", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesNodesStorageRrddata(ctx, "sample-remote", "sample-node", "sample-storage", &pve.ListRemotesNodesStorageRrddataParams{Cf: "sample-cf", Timeframe: "sample-timeframe"})
		if err != nil {
			t.Fatalf("ListRemotesNodesStorageRrddata: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesStorageRrddata: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/storage/sample-storage/rrddata")
		assertParamValue(t, got.query, "cf", "sample-cf")
		assertParamValue(t, got.query, "timeframe", "sample-timeframe")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesStorageRrddata(nilCtx, "sample-remote", "sample-node", "sample-storage", &pve.ListRemotesNodesStorageRrddataParams{Cf: "sample-cf", Timeframe: "sample-timeframe"}); err == nil {
			t.Errorf("ListRemotesNodesStorageRrddata: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesStorageStatus", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesNodesStorageStatus(ctx, "sample-remote", "sample-node", "sample-storage")
		if err != nil {
			t.Fatalf("ListRemotesNodesStorageStatus: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesStorageStatus: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/storage/sample-storage/status")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesStorageStatus(nilCtx, "sample-remote", "sample-node", "sample-storage"); err == nil {
			t.Errorf("ListRemotesNodesStorageStatus: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesSubscription", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesNodesSubscription(ctx, "sample-remote", "sample-node")
		if err != nil {
			t.Fatalf("ListRemotesNodesSubscription: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesNodesSubscription: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/subscription")

		var nilCtx context.Context
		if _, err := svc.ListRemotesNodesSubscription(nilCtx, "sample-remote", "sample-node"); err == nil {
			t.Errorf("ListRemotesNodesSubscription: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesNodesTermproxy", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesNodesTermproxy(ctx, "sample-remote", "sample-node")
		if err != nil {
			t.Fatalf("CreateRemotesNodesTermproxy: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesNodesTermproxy: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/termproxy")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesNodesTermproxy(nilCtx, "sample-remote", "sample-node"); err == nil {
			t.Errorf("CreateRemotesNodesTermproxy: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesNodesVncwebsocket", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListRemotesNodesVncwebsocket(ctx, "sample-remote", "sample-node", &pve.ListRemotesNodesVncwebsocketParams{Port: 42, Vncticket: "sample-vncticket"})
		if err != nil {
			t.Fatalf("ListRemotesNodesVncwebsocket: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/nodes/sample-node/vncwebsocket")
		assertParamValue(t, got.query, "port", "42")
		assertParamValue(t, got.query, "vncticket", "sample-vncticket")

		var nilCtx context.Context
		if err := svc.ListRemotesNodesVncwebsocket(nilCtx, "sample-remote", "sample-node", &pve.ListRemotesNodesVncwebsocketParams{Port: 42, Vncticket: "sample-vncticket"}); err == nil {
			t.Errorf("ListRemotesNodesVncwebsocket: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesOptions", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesOptions(ctx, "sample-remote")
		if err != nil {
			t.Fatalf("ListRemotesOptions: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesOptions: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/options")

		var nilCtx context.Context
		if _, err := svc.ListRemotesOptions(nilCtx, "sample-remote"); err == nil {
			t.Errorf("ListRemotesOptions: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesQemu", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesQemu(ctx, "sample-remote", &pve.ListRemotesQemuParams{})
		if err != nil {
			t.Fatalf("ListRemotesQemu: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesQemu: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/qemu")

		var nilCtx context.Context
		if _, err := svc.ListRemotesQemu(nilCtx, "sample-remote", &pve.ListRemotesQemuParams{}); err == nil {
			t.Errorf("ListRemotesQemu: expected error for nil context, got nil")
		}
	})
	t.Run("GetRemotesQemu", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.GetRemotesQemu(ctx, "sample-remote", "sample-vmid")
		if err != nil {
			t.Fatalf("GetRemotesQemu: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid")

		var nilCtx context.Context
		if err := svc.GetRemotesQemu(nilCtx, "sample-remote", "sample-vmid"); err == nil {
			t.Errorf("GetRemotesQemu: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesQemuConfig", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesQemuConfig(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuConfigParams{State: "sample-state"})
		if err != nil {
			t.Fatalf("ListRemotesQemuConfig: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesQemuConfig: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/config")
		assertParamValue(t, got.query, "state", "sample-state")

		var nilCtx context.Context
		if _, err := svc.ListRemotesQemuConfig(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuConfigParams{State: "sample-state"}); err == nil {
			t.Errorf("ListRemotesQemuConfig: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesQemuFirewall", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListRemotesQemuFirewall(ctx, "sample-remote", "sample-vmid")
		if err != nil {
			t.Fatalf("ListRemotesQemuFirewall: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/firewall")

		var nilCtx context.Context
		if err := svc.ListRemotesQemuFirewall(nilCtx, "sample-remote", "sample-vmid"); err == nil {
			t.Errorf("ListRemotesQemuFirewall: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesQemuFirewallOptions", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesQemuFirewallOptions(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuFirewallOptionsParams{})
		if err != nil {
			t.Fatalf("ListRemotesQemuFirewallOptions: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesQemuFirewallOptions: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/firewall/options")

		var nilCtx context.Context
		if _, err := svc.ListRemotesQemuFirewallOptions(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuFirewallOptionsParams{}); err == nil {
			t.Errorf("ListRemotesQemuFirewallOptions: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateRemotesQemuFirewallOptions", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateRemotesQemuFirewallOptions(ctx, "sample-remote", "sample-vmid", &pve.UpdateRemotesQemuFirewallOptionsParams{})
		if err != nil {
			t.Fatalf("UpdateRemotesQemuFirewallOptions: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/firewall/options")

		var nilCtx context.Context
		if err := svc.UpdateRemotesQemuFirewallOptions(nilCtx, "sample-remote", "sample-vmid", &pve.UpdateRemotesQemuFirewallOptionsParams{}); err == nil {
			t.Errorf("UpdateRemotesQemuFirewallOptions: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesQemuFirewallRules", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesQemuFirewallRules(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuFirewallRulesParams{})
		if err != nil {
			t.Fatalf("ListRemotesQemuFirewallRules: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesQemuFirewallRules: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/firewall/rules")

		var nilCtx context.Context
		if _, err := svc.ListRemotesQemuFirewallRules(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuFirewallRulesParams{}); err == nil {
			t.Errorf("ListRemotesQemuFirewallRules: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesQemuMigrate", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesQemuMigrate(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuMigrateParams{})
		if err != nil {
			t.Fatalf("ListRemotesQemuMigrate: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesQemuMigrate: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/migrate")

		var nilCtx context.Context
		if _, err := svc.ListRemotesQemuMigrate(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuMigrateParams{}); err == nil {
			t.Errorf("ListRemotesQemuMigrate: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesQemuMigrate", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesQemuMigrate(ctx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuMigrateParams{Target: "sample-target"})
		if err != nil {
			t.Fatalf("CreateRemotesQemuMigrate: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesQemuMigrate: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/migrate")
		assertParamValue(t, got.form, "target", "sample-target")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesQemuMigrate(nilCtx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuMigrateParams{Target: "sample-target"}); err == nil {
			t.Errorf("CreateRemotesQemuMigrate: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesQemuPending", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesQemuPending(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuPendingParams{})
		if err != nil {
			t.Fatalf("ListRemotesQemuPending: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesQemuPending: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/pending")

		var nilCtx context.Context
		if _, err := svc.ListRemotesQemuPending(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuPendingParams{}); err == nil {
			t.Errorf("ListRemotesQemuPending: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesQemuRemoteMigrate", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesQemuRemoteMigrate(ctx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuRemoteMigrateParams{Target: "sample-target", TargetBridge: []string{"sample-target-bridge"}, TargetStorage: []string{"sample-target-storage"}})
		if err != nil {
			t.Fatalf("CreateRemotesQemuRemoteMigrate: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesQemuRemoteMigrate: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/remote-migrate")
		assertParamValue(t, got.form, "target", "sample-target")
		assertParamValue(t, got.form, "target-bridge", "sample-target-bridge")
		assertParamValue(t, got.form, "target-storage", "sample-target-storage")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesQemuRemoteMigrate(nilCtx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuRemoteMigrateParams{Target: "sample-target", TargetBridge: []string{"sample-target-bridge"}, TargetStorage: []string{"sample-target-storage"}}); err == nil {
			t.Errorf("CreateRemotesQemuRemoteMigrate: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesQemuResume", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesQemuResume(ctx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuResumeParams{})
		if err != nil {
			t.Fatalf("CreateRemotesQemuResume: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesQemuResume: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/resume")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesQemuResume(nilCtx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuResumeParams{}); err == nil {
			t.Errorf("CreateRemotesQemuResume: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesQemuRrddata", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesQemuRrddata(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuRrddataParams{Cf: "sample-cf", Timeframe: "sample-timeframe"})
		if err != nil {
			t.Fatalf("ListRemotesQemuRrddata: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesQemuRrddata: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/rrddata")
		assertParamValue(t, got.query, "cf", "sample-cf")
		assertParamValue(t, got.query, "timeframe", "sample-timeframe")

		var nilCtx context.Context
		if _, err := svc.ListRemotesQemuRrddata(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuRrddataParams{Cf: "sample-cf", Timeframe: "sample-timeframe"}); err == nil {
			t.Errorf("ListRemotesQemuRrddata: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesQemuShutdown", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesQemuShutdown(ctx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuShutdownParams{})
		if err != nil {
			t.Fatalf("CreateRemotesQemuShutdown: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesQemuShutdown: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/shutdown")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesQemuShutdown(nilCtx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuShutdownParams{}); err == nil {
			t.Errorf("CreateRemotesQemuShutdown: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesQemuSnapshot", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesQemuSnapshot(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuSnapshotParams{})
		if err != nil {
			t.Fatalf("ListRemotesQemuSnapshot: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesQemuSnapshot: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/snapshot")

		var nilCtx context.Context
		if _, err := svc.ListRemotesQemuSnapshot(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuSnapshotParams{}); err == nil {
			t.Errorf("ListRemotesQemuSnapshot: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesQemuSnapshot", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesQemuSnapshot(ctx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuSnapshotParams{Snapname: "sample-snapname"})
		if err != nil {
			t.Fatalf("CreateRemotesQemuSnapshot: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesQemuSnapshot: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/snapshot")
		assertParamValue(t, got.form, "snapname", "sample-snapname")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesQemuSnapshot(nilCtx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuSnapshotParams{Snapname: "sample-snapname"}); err == nil {
			t.Errorf("CreateRemotesQemuSnapshot: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteRemotesQemuSnapshot", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.DeleteRemotesQemuSnapshot(ctx, "sample-remote", "sample-vmid", "sample-snapname", &pve.DeleteRemotesQemuSnapshotParams{})
		if err != nil {
			t.Fatalf("DeleteRemotesQemuSnapshot: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("DeleteRemotesQemuSnapshot: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/snapshot/sample-snapname")

		var nilCtx context.Context
		if _, err := svc.DeleteRemotesQemuSnapshot(nilCtx, "sample-remote", "sample-vmid", "sample-snapname", &pve.DeleteRemotesQemuSnapshotParams{}); err == nil {
			t.Errorf("DeleteRemotesQemuSnapshot: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateRemotesQemuSnapshotConfig", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateRemotesQemuSnapshotConfig(ctx, "sample-remote", "sample-vmid", "sample-snapname", &pve.UpdateRemotesQemuSnapshotConfigParams{})
		if err != nil {
			t.Fatalf("UpdateRemotesQemuSnapshotConfig: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/snapshot/sample-snapname/config")

		var nilCtx context.Context
		if err := svc.UpdateRemotesQemuSnapshotConfig(nilCtx, "sample-remote", "sample-vmid", "sample-snapname", &pve.UpdateRemotesQemuSnapshotConfigParams{}); err == nil {
			t.Errorf("UpdateRemotesQemuSnapshotConfig: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesQemuSnapshotRollback", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesQemuSnapshotRollback(ctx, "sample-remote", "sample-vmid", "sample-snapname", &pve.CreateRemotesQemuSnapshotRollbackParams{})
		if err != nil {
			t.Fatalf("CreateRemotesQemuSnapshotRollback: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesQemuSnapshotRollback: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/snapshot/sample-snapname/rollback")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesQemuSnapshotRollback(nilCtx, "sample-remote", "sample-vmid", "sample-snapname", &pve.CreateRemotesQemuSnapshotRollbackParams{}); err == nil {
			t.Errorf("CreateRemotesQemuSnapshotRollback: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesQemuStart", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesQemuStart(ctx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuStartParams{})
		if err != nil {
			t.Fatalf("CreateRemotesQemuStart: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesQemuStart: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/start")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesQemuStart(nilCtx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuStartParams{}); err == nil {
			t.Errorf("CreateRemotesQemuStart: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesQemuStatus", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesQemuStatus(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuStatusParams{})
		if err != nil {
			t.Fatalf("ListRemotesQemuStatus: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesQemuStatus: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/status")

		var nilCtx context.Context
		if _, err := svc.ListRemotesQemuStatus(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuStatusParams{}); err == nil {
			t.Errorf("ListRemotesQemuStatus: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesQemuStop", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesQemuStop(ctx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuStopParams{})
		if err != nil {
			t.Fatalf("CreateRemotesQemuStop: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesQemuStop: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/stop")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesQemuStop(nilCtx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuStopParams{}); err == nil {
			t.Errorf("CreateRemotesQemuStop: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesQemuTermproxy", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesQemuTermproxy(ctx, "sample-remote", "sample-vmid")
		if err != nil {
			t.Fatalf("CreateRemotesQemuTermproxy: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesQemuTermproxy: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/termproxy")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesQemuTermproxy(nilCtx, "sample-remote", "sample-vmid"); err == nil {
			t.Errorf("CreateRemotesQemuTermproxy: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemotesQemuVncproxy", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateRemotesQemuVncproxy(ctx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuVncproxyParams{})
		if err != nil {
			t.Fatalf("CreateRemotesQemuVncproxy: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateRemotesQemuVncproxy: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/vncproxy")

		var nilCtx context.Context
		if _, err := svc.CreateRemotesQemuVncproxy(nilCtx, "sample-remote", "sample-vmid", &pve.CreateRemotesQemuVncproxyParams{}); err == nil {
			t.Errorf("CreateRemotesQemuVncproxy: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesQemuVncwebsocket", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListRemotesQemuVncwebsocket(ctx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuVncwebsocketParams{Port: 42, Vncticket: "sample-vncticket"})
		if err != nil {
			t.Fatalf("ListRemotesQemuVncwebsocket: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/qemu/sample-vmid/vncwebsocket")
		assertParamValue(t, got.query, "port", "42")
		assertParamValue(t, got.query, "vncticket", "sample-vncticket")

		var nilCtx context.Context
		if err := svc.ListRemotesQemuVncwebsocket(nilCtx, "sample-remote", "sample-vmid", &pve.ListRemotesQemuVncwebsocketParams{Port: 42, Vncticket: "sample-vncticket"}); err == nil {
			t.Errorf("ListRemotesQemuVncwebsocket: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesResources", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesResources(ctx, "sample-remote", &pve.ListRemotesResourcesParams{})
		if err != nil {
			t.Fatalf("ListRemotesResources: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesResources: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/resources")

		var nilCtx context.Context
		if _, err := svc.ListRemotesResources(nilCtx, "sample-remote", &pve.ListRemotesResourcesParams{}); err == nil {
			t.Errorf("ListRemotesResources: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesTasks", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesTasks(ctx, "sample-remote", &pve.ListRemotesTasksParams{})
		if err != nil {
			t.Fatalf("ListRemotesTasks: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesTasks: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/tasks")

		var nilCtx context.Context
		if _, err := svc.ListRemotesTasks(nilCtx, "sample-remote", &pve.ListRemotesTasksParams{}); err == nil {
			t.Errorf("ListRemotesTasks: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteRemotesTasks", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.DeleteRemotesTasks(ctx, "sample-remote", "sample-upid")
		if err != nil {
			t.Fatalf("DeleteRemotesTasks: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/pve/remotes/sample-remote/tasks/sample-upid")

		var nilCtx context.Context
		if err := svc.DeleteRemotesTasks(nilCtx, "sample-remote", "sample-upid"); err == nil {
			t.Errorf("DeleteRemotesTasks: expected error for nil context, got nil")
		}
	})
	t.Run("GetRemotesTasks", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.GetRemotesTasks(ctx, "sample-remote", "sample-upid")
		if err != nil {
			t.Fatalf("GetRemotesTasks: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/tasks/sample-upid")

		var nilCtx context.Context
		if err := svc.GetRemotesTasks(nilCtx, "sample-remote", "sample-upid"); err == nil {
			t.Errorf("GetRemotesTasks: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesTasksLog", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesTasksLog(ctx, "sample-remote", "sample-upid", &pve.ListRemotesTasksLogParams{})
		if err != nil {
			t.Fatalf("ListRemotesTasksLog: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesTasksLog: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/tasks/sample-upid/log")

		var nilCtx context.Context
		if _, err := svc.ListRemotesTasksLog(nilCtx, "sample-remote", "sample-upid", &pve.ListRemotesTasksLogParams{}); err == nil {
			t.Errorf("ListRemotesTasksLog: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesTasksStatus", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemotesTasksStatus(ctx, "sample-remote", "sample-upid", &pve.ListRemotesTasksStatusParams{})
		if err != nil {
			t.Fatalf("ListRemotesTasksStatus: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesTasksStatus: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/tasks/sample-upid/status")

		var nilCtx context.Context
		if _, err := svc.ListRemotesTasksStatus(nilCtx, "sample-remote", "sample-upid", &pve.ListRemotesTasksStatusParams{}); err == nil {
			t.Errorf("ListRemotesTasksStatus: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemotesUpdates", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemotesUpdates(ctx, "sample-remote")
		if err != nil {
			t.Fatalf("ListRemotesUpdates: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemotesUpdates: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/pve/remotes/sample-remote/updates")

		var nilCtx context.Context
		if _, err := svc.ListRemotesUpdates(nilCtx, "sample-remote"); err == nil {
			t.Errorf("ListRemotesUpdates: expected error for nil context, got nil")
		}
	})
	t.Run("CreateScan", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateScan(ctx, &pve.CreateScanParams{Authid: "sample-authid", Hostname: "sample-hostname", Token: "sample-token"})
		if err != nil {
			t.Fatalf("CreateScan: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateScan: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/pve/scan")
		assertParamValue(t, got.form, "authid", "sample-authid")
		assertParamValue(t, got.form, "hostname", "sample-hostname")
		assertParamValue(t, got.form, "token", "sample-token")

		var nilCtx context.Context
		if _, err := svc.CreateScan(nilCtx, &pve.CreateScanParams{Authid: "sample-authid", Hostname: "sample-hostname", Token: "sample-token"}); err == nil {
			t.Errorf("CreateScan: expected error for nil context, got nil")
		}
	})
	t.Run("ErrorPath_GET", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.ListPve(ctx)
		if err == nil {
			t.Fatalf("ListPve: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_POST", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.CreateProbeTls(ctx, &pve.CreateProbeTlsParams{Hostname: "sample-hostname"})
		if err == nil {
			t.Fatalf("CreateProbeTls: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_PUT", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.UpdateRemotesFirewallOptions(ctx, "sample-remote", &pve.UpdateRemotesFirewallOptionsParams{})
		if err == nil {
			t.Fatalf("UpdateRemotesFirewallOptions: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_DELETE", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		_, err := svc.DeleteRemotesLxcSnapshot(ctx, "sample-remote", "sample-vmid", "sample-snapname", &pve.DeleteRemotesLxcSnapshotParams{})
		if err == nil {
			t.Fatalf("DeleteRemotesLxcSnapshot: expected error on 500 response, got nil")
		}
	})
}
