// Code generated by cmd/pvegen. DO NOT EDIT.

package nodes_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"testing"

	"github.com/fivetwenty-io/pve-apiclient-go/v3/pkg/api/nodes"
	pveclient "github.com/fivetwenty-io/pve-apiclient-go/v3/pkg/client"
)

func smokeOptsFromServerURL(u string) pveclient.Options {
	parsed, err := url.Parse(u)
	if err != nil {
		panic("test setup: invalid server URL: " + err.Error())
	}

	host := parsed.Hostname()

	port := 0
	if p := parsed.Port(); p != "" {
		port, _ = strconv.Atoi(p)
	}

	return pveclient.Options{
		Host:     host,
		Port:     port,
		Protocol: "http",
		APIToken: "user@pam!tok=sec",
	}
}

func TestSmoke_Nodes_GeneratedMethods(t *testing.T) {
	t.Parallel()

	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		_ = json.NewEncoder(w).Encode(map[string]any{
			"data":    map[string]any{},
			"success": 1,
		})
	})

	srv := httptest.NewServer(mux)
	defer srv.Close()

	c, err := pveclient.NewClient(smokeOptsFromServerURL(srv.URL))
	if err != nil {
		t.Fatalf("NewClient: %v", err)
	}

	svc := nodes.New(c)
	ctx := context.Background()

	t.Run("ListNodes", func(t *testing.T) {
		_, err := svc.ListNodes(ctx)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetNodes", func(t *testing.T) {
		_, err := svc.GetNodes(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListAplinfo", func(t *testing.T) {
		_, err := svc.ListAplinfo(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListApt", func(t *testing.T) {
		_, err := svc.ListApt(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListAptChangelog", func(t *testing.T) {
		_, err := svc.ListAptChangelog(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListAptRepositories", func(t *testing.T) {
		_, err := svc.ListAptRepositories(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListAptUpdate", func(t *testing.T) {
		_, err := svc.ListAptUpdate(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListAptVersions", func(t *testing.T) {
		_, err := svc.ListAptVersions(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCapabilities", func(t *testing.T) {
		_, err := svc.ListCapabilities(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCapabilitiesQemu", func(t *testing.T) {
		_, err := svc.ListCapabilitiesQemu(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCapabilitiesQemuCpu", func(t *testing.T) {
		_, err := svc.ListCapabilitiesQemuCpu(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCapabilitiesQemuCpuFlags", func(t *testing.T) {
		_, err := svc.ListCapabilitiesQemuCpuFlags(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCapabilitiesQemuMachines", func(t *testing.T) {
		_, err := svc.ListCapabilitiesQemuMachines(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCapabilitiesQemuMigration", func(t *testing.T) {
		_, err := svc.ListCapabilitiesQemuMigration(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCeph", func(t *testing.T) {
		_, err := svc.ListCeph(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephCfg", func(t *testing.T) {
		_, err := svc.ListCephCfg(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephCfgDb", func(t *testing.T) {
		_, err := svc.ListCephCfgDb(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephCfgRaw", func(t *testing.T) {
		_, err := svc.ListCephCfgRaw(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephCfgValue", func(t *testing.T) {
		_, err := svc.ListCephCfgValue(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephCmdSafety", func(t *testing.T) {
		_, err := svc.ListCephCmdSafety(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephCrush", func(t *testing.T) {
		_, err := svc.ListCephCrush(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephFs", func(t *testing.T) {
		_, err := svc.ListCephFs(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephLog", func(t *testing.T) {
		_, err := svc.ListCephLog(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephMds", func(t *testing.T) {
		_, err := svc.ListCephMds(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephMgr", func(t *testing.T) {
		_, err := svc.ListCephMgr(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephMon", func(t *testing.T) {
		_, err := svc.ListCephMon(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephOsd", func(t *testing.T) {
		_, err := svc.ListCephOsd(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetCephOsd", func(t *testing.T) {
		_, err := svc.GetCephOsd(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephOsdLvInfo", func(t *testing.T) {
		_, err := svc.ListCephOsdLvInfo(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephOsdMetadata", func(t *testing.T) {
		_, err := svc.ListCephOsdMetadata(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephPool", func(t *testing.T) {
		_, err := svc.ListCephPool(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetCephPool", func(t *testing.T) {
		_, err := svc.GetCephPool(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephPoolStatus", func(t *testing.T) {
		_, err := svc.ListCephPoolStatus(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephRules", func(t *testing.T) {
		_, err := svc.ListCephRules(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCephStatus", func(t *testing.T) {
		_, err := svc.ListCephStatus(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCertificates", func(t *testing.T) {
		_, err := svc.ListCertificates(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCertificatesAcme", func(t *testing.T) {
		_, err := svc.ListCertificatesAcme(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListCertificatesInfo", func(t *testing.T) {
		_, err := svc.ListCertificatesInfo(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListConfig", func(t *testing.T) {
		_, err := svc.ListConfig(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListDisks", func(t *testing.T) {
		_, err := svc.ListDisks(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListDisksDirectory", func(t *testing.T) {
		_, err := svc.ListDisksDirectory(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListDisksList", func(t *testing.T) {
		_, err := svc.ListDisksList(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListDisksLvm", func(t *testing.T) {
		_, err := svc.ListDisksLvm(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListDisksLvmthin", func(t *testing.T) {
		_, err := svc.ListDisksLvmthin(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListDisksSmart", func(t *testing.T) {
		_, err := svc.ListDisksSmart(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListDisksZfs", func(t *testing.T) {
		_, err := svc.ListDisksZfs(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetDisksZfs", func(t *testing.T) {
		_, err := svc.GetDisksZfs(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListDns", func(t *testing.T) {
		_, err := svc.ListDns(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListFirewall", func(t *testing.T) {
		_, err := svc.ListFirewall(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListFirewallLog", func(t *testing.T) {
		_, err := svc.ListFirewallLog(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListFirewallOptions", func(t *testing.T) {
		_, err := svc.ListFirewallOptions(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListFirewallRules", func(t *testing.T) {
		_, err := svc.ListFirewallRules(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetFirewallRules", func(t *testing.T) {
		_, err := svc.GetFirewallRules(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListHardware", func(t *testing.T) {
		_, err := svc.ListHardware(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListHardwarePci", func(t *testing.T) {
		_, err := svc.ListHardwarePci(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetHardwarePci", func(t *testing.T) {
		_, err := svc.GetHardwarePci(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListHardwarePciMdev", func(t *testing.T) {
		_, err := svc.ListHardwarePciMdev(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListHardwareUsb", func(t *testing.T) {
		_, err := svc.ListHardwareUsb(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListHosts", func(t *testing.T) {
		_, err := svc.ListHosts(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListJournal", func(t *testing.T) {
		_, err := svc.ListJournal(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxc", func(t *testing.T) {
		_, err := svc.ListLxc(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetLxc", func(t *testing.T) {
		_, err := svc.GetLxc(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcConfig", func(t *testing.T) {
		_, err := svc.ListLxcConfig(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcFeature", func(t *testing.T) {
		_, err := svc.ListLxcFeature(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcFirewall", func(t *testing.T) {
		_, err := svc.ListLxcFirewall(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcFirewallAliases", func(t *testing.T) {
		_, err := svc.ListLxcFirewallAliases(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetLxcFirewallAliases", func(t *testing.T) {
		_, err := svc.GetLxcFirewallAliases(ctx, "stub", "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcFirewallIpset", func(t *testing.T) {
		_, err := svc.ListLxcFirewallIpset(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetLxcFirewallIpset", func(t *testing.T) {
		_, err := svc.GetLxcFirewallIpset(ctx, "stub", "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetLxcFirewallIpset2", func(t *testing.T) {
		_, err := svc.GetLxcFirewallIpset2(ctx, "stub", "stub", "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcFirewallLog", func(t *testing.T) {
		_, err := svc.ListLxcFirewallLog(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcFirewallOptions", func(t *testing.T) {
		_, err := svc.ListLxcFirewallOptions(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcFirewallRefs", func(t *testing.T) {
		_, err := svc.ListLxcFirewallRefs(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcFirewallRules", func(t *testing.T) {
		_, err := svc.ListLxcFirewallRules(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetLxcFirewallRules", func(t *testing.T) {
		_, err := svc.GetLxcFirewallRules(ctx, "stub", "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcInterfaces", func(t *testing.T) {
		_, err := svc.ListLxcInterfaces(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcMigrate", func(t *testing.T) {
		_, err := svc.ListLxcMigrate(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcMtunnelwebsocket", func(t *testing.T) {
		_, err := svc.ListLxcMtunnelwebsocket(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcPending", func(t *testing.T) {
		_, err := svc.ListLxcPending(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcRrd", func(t *testing.T) {
		_, err := svc.ListLxcRrd(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcRrddata", func(t *testing.T) {
		_, err := svc.ListLxcRrddata(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcSnapshot", func(t *testing.T) {
		_, err := svc.ListLxcSnapshot(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetLxcSnapshot", func(t *testing.T) {
		_, err := svc.GetLxcSnapshot(ctx, "stub", "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcSnapshotConfig", func(t *testing.T) {
		_, err := svc.ListLxcSnapshotConfig(ctx, "stub", "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcStatus", func(t *testing.T) {
		_, err := svc.ListLxcStatus(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcStatusCurrent", func(t *testing.T) {
		_, err := svc.ListLxcStatusCurrent(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListLxcVncwebsocket", func(t *testing.T) {
		_, err := svc.ListLxcVncwebsocket(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListNetstat", func(t *testing.T) {
		_, err := svc.ListNetstat(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListNetwork", func(t *testing.T) {
		_, err := svc.ListNetwork(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetNetwork", func(t *testing.T) {
		_, err := svc.GetNetwork(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemu", func(t *testing.T) {
		_, err := svc.ListQemu(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetQemu", func(t *testing.T) {
		_, err := svc.GetQemu(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuAgent", func(t *testing.T) {
		_, err := svc.ListQemuAgent(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuAgentExecStatus", func(t *testing.T) {
		_, err := svc.ListQemuAgentExecStatus(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuAgentFileRead", func(t *testing.T) {
		_, err := svc.ListQemuAgentFileRead(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuAgentGetFsinfo", func(t *testing.T) {
		_, err := svc.ListQemuAgentGetFsinfo(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuAgentGetHostName", func(t *testing.T) {
		_, err := svc.ListQemuAgentGetHostName(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuAgentGetMemoryBlockInfo", func(t *testing.T) {
		_, err := svc.ListQemuAgentGetMemoryBlockInfo(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuAgentGetMemoryBlocks", func(t *testing.T) {
		_, err := svc.ListQemuAgentGetMemoryBlocks(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuAgentGetOsinfo", func(t *testing.T) {
		_, err := svc.ListQemuAgentGetOsinfo(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuAgentGetTime", func(t *testing.T) {
		_, err := svc.ListQemuAgentGetTime(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuAgentGetTimezone", func(t *testing.T) {
		_, err := svc.ListQemuAgentGetTimezone(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuAgentGetUsers", func(t *testing.T) {
		_, err := svc.ListQemuAgentGetUsers(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuAgentGetVcpus", func(t *testing.T) {
		_, err := svc.ListQemuAgentGetVcpus(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuAgentInfo", func(t *testing.T) {
		_, err := svc.ListQemuAgentInfo(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuAgentNetworkGetInterfaces", func(t *testing.T) {
		_, err := svc.ListQemuAgentNetworkGetInterfaces(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuCloudinit", func(t *testing.T) {
		_, err := svc.ListQemuCloudinit(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuCloudinitDump", func(t *testing.T) {
		_, err := svc.ListQemuCloudinitDump(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuConfig", func(t *testing.T) {
		_, err := svc.ListQemuConfig(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuFeature", func(t *testing.T) {
		_, err := svc.ListQemuFeature(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuFirewall", func(t *testing.T) {
		_, err := svc.ListQemuFirewall(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuFirewallAliases", func(t *testing.T) {
		_, err := svc.ListQemuFirewallAliases(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetQemuFirewallAliases", func(t *testing.T) {
		_, err := svc.GetQemuFirewallAliases(ctx, "stub", "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuFirewallIpset", func(t *testing.T) {
		_, err := svc.ListQemuFirewallIpset(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetQemuFirewallIpset", func(t *testing.T) {
		_, err := svc.GetQemuFirewallIpset(ctx, "stub", "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetQemuFirewallIpset2", func(t *testing.T) {
		_, err := svc.GetQemuFirewallIpset2(ctx, "stub", "stub", "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuFirewallLog", func(t *testing.T) {
		_, err := svc.ListQemuFirewallLog(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuFirewallOptions", func(t *testing.T) {
		_, err := svc.ListQemuFirewallOptions(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuFirewallRefs", func(t *testing.T) {
		_, err := svc.ListQemuFirewallRefs(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuFirewallRules", func(t *testing.T) {
		_, err := svc.ListQemuFirewallRules(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetQemuFirewallRules", func(t *testing.T) {
		_, err := svc.GetQemuFirewallRules(ctx, "stub", "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuMigrate", func(t *testing.T) {
		_, err := svc.ListQemuMigrate(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuMtunnelwebsocket", func(t *testing.T) {
		_, err := svc.ListQemuMtunnelwebsocket(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuPending", func(t *testing.T) {
		_, err := svc.ListQemuPending(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuRrd", func(t *testing.T) {
		_, err := svc.ListQemuRrd(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuRrddata", func(t *testing.T) {
		_, err := svc.ListQemuRrddata(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuSnapshot", func(t *testing.T) {
		_, err := svc.ListQemuSnapshot(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetQemuSnapshot", func(t *testing.T) {
		_, err := svc.GetQemuSnapshot(ctx, "stub", "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuSnapshotConfig", func(t *testing.T) {
		_, err := svc.ListQemuSnapshotConfig(ctx, "stub", "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuStatus", func(t *testing.T) {
		_, err := svc.ListQemuStatus(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuStatusCurrent", func(t *testing.T) {
		_, err := svc.ListQemuStatusCurrent(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQemuVncwebsocket", func(t *testing.T) {
		_, err := svc.ListQemuVncwebsocket(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQueryOciRepoTags", func(t *testing.T) {
		_, err := svc.ListQueryOciRepoTags(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListQueryUrlMetadata", func(t *testing.T) {
		_, err := svc.ListQueryUrlMetadata(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListReplication", func(t *testing.T) {
		_, err := svc.ListReplication(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetReplication", func(t *testing.T) {
		_, err := svc.GetReplication(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListReplicationLog", func(t *testing.T) {
		_, err := svc.ListReplicationLog(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListReplicationStatus", func(t *testing.T) {
		_, err := svc.ListReplicationStatus(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListReport", func(t *testing.T) {
		_, err := svc.ListReport(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListRrd", func(t *testing.T) {
		_, err := svc.ListRrd(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListRrddata", func(t *testing.T) {
		_, err := svc.ListRrddata(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListScan", func(t *testing.T) {
		_, err := svc.ListScan(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListScanCifs", func(t *testing.T) {
		_, err := svc.ListScanCifs(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListScanIscsi", func(t *testing.T) {
		_, err := svc.ListScanIscsi(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListScanLvm", func(t *testing.T) {
		_, err := svc.ListScanLvm(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListScanLvmthin", func(t *testing.T) {
		_, err := svc.ListScanLvmthin(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListScanNfs", func(t *testing.T) {
		_, err := svc.ListScanNfs(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListScanPbs", func(t *testing.T) {
		_, err := svc.ListScanPbs(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListScanZfs", func(t *testing.T) {
		_, err := svc.ListScanZfs(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListSdn", func(t *testing.T) {
		_, err := svc.ListSdn(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetSdnFabrics", func(t *testing.T) {
		_, err := svc.GetSdnFabrics(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListSdnFabricsInterfaces", func(t *testing.T) {
		_, err := svc.ListSdnFabricsInterfaces(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListSdnFabricsNeighbors", func(t *testing.T) {
		_, err := svc.ListSdnFabricsNeighbors(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListSdnFabricsRoutes", func(t *testing.T) {
		_, err := svc.ListSdnFabricsRoutes(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetSdnVnets", func(t *testing.T) {
		_, err := svc.GetSdnVnets(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListSdnVnetsMacVrf", func(t *testing.T) {
		_, err := svc.ListSdnVnetsMacVrf(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListSdnZones", func(t *testing.T) {
		_, err := svc.ListSdnZones(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetSdnZones", func(t *testing.T) {
		_, err := svc.GetSdnZones(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListSdnZonesBridges", func(t *testing.T) {
		_, err := svc.ListSdnZonesBridges(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListSdnZonesContent", func(t *testing.T) {
		_, err := svc.ListSdnZonesContent(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListSdnZonesIpVrf", func(t *testing.T) {
		_, err := svc.ListSdnZonesIpVrf(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListServices", func(t *testing.T) {
		_, err := svc.ListServices(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetServices", func(t *testing.T) {
		_, err := svc.GetServices(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListServicesState", func(t *testing.T) {
		_, err := svc.ListServicesState(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListStatus", func(t *testing.T) {
		_, err := svc.ListStatus(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListStorage", func(t *testing.T) {
		_, err := svc.ListStorage(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetStorage", func(t *testing.T) {
		_, err := svc.GetStorage(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListStorageContent", func(t *testing.T) {
		_, err := svc.ListStorageContent(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetStorageContent", func(t *testing.T) {
		_, err := svc.GetStorageContent(ctx, "stub", "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListStorageFileRestoreDownload", func(t *testing.T) {
		_, err := svc.ListStorageFileRestoreDownload(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListStorageFileRestoreList", func(t *testing.T) {
		_, err := svc.ListStorageFileRestoreList(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListStorageIdentity", func(t *testing.T) {
		_, err := svc.ListStorageIdentity(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListStorageImportMetadata", func(t *testing.T) {
		_, err := svc.ListStorageImportMetadata(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListStoragePrunebackups", func(t *testing.T) {
		_, err := svc.ListStoragePrunebackups(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListStorageRrd", func(t *testing.T) {
		_, err := svc.ListStorageRrd(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListStorageRrddata", func(t *testing.T) {
		_, err := svc.ListStorageRrddata(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListStorageStatus", func(t *testing.T) {
		_, err := svc.ListStorageStatus(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListSubscription", func(t *testing.T) {
		_, err := svc.ListSubscription(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListSyslog", func(t *testing.T) {
		_, err := svc.ListSyslog(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListTasks", func(t *testing.T) {
		_, err := svc.ListTasks(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("GetTasks", func(t *testing.T) {
		_, err := svc.GetTasks(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListTasksLog", func(t *testing.T) {
		_, err := svc.ListTasksLog(ctx, "stub", "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListTasksStatus", func(t *testing.T) {
		_, err := svc.ListTasksStatus(ctx, "stub", "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListTime", func(t *testing.T) {
		_, err := svc.ListTime(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListVersion", func(t *testing.T) {
		_, err := svc.ListVersion(ctx, "stub")
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListVncwebsocket", func(t *testing.T) {
		_, err := svc.ListVncwebsocket(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListVzdumpDefaults", func(t *testing.T) {
		_, err := svc.ListVzdumpDefaults(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
	t.Run("ListVzdumpExtractconfig", func(t *testing.T) {
		_, err := svc.ListVzdumpExtractconfig(ctx, "stub", nil)
		_ = err // smoke: any outcome is acceptable; the stub server is permissive
	})
}
