// Code generated by cmd/pvegen. DO NOT EDIT.

// Package access exposes typed bindings for the PVE /access endpoint family.
package access

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
)

var _ = strings.TrimPrefix
var _ = json.RawMessage(nil)
var _ = url.PathEscape
var _ = sort.Ints
var _ = strconv.Itoa

// Service exposes typed operations on the /access endpoint family.
type Service interface {
	// ListAccess GET /access
	// Directory index.
	ListAccess(ctx context.Context) error
	// ListAcl GET /access/acl
	// Get ACL entries, can be filter by path.
	ListAcl(ctx context.Context, params *ListAclParams) (*ListAclResponse, error)
	// UpdateAcl PUT /access/acl
	// Update ACL
	UpdateAcl(ctx context.Context, params *UpdateAclParams) error
	// ListDomains GET /access/domains
	// Authentication domain/realm index.
	ListDomains(ctx context.Context) (*ListDomainsResponse, error)
	// CreateDomainsSync POST /access/domains/{realm}/sync
	// Synchronize users of a given realm
	CreateDomainsSync(ctx context.Context, realm string, params *CreateDomainsSyncParams) (*CreateDomainsSyncResponse, error)
	// ListOpenid GET /access/openid
	// Directory index.
	ListOpenid(ctx context.Context) error
	// CreateOpenidAuthUrl POST /access/openid/auth-url
	// Create OpenID Redirect Session
	CreateOpenidAuthUrl(ctx context.Context, params *CreateOpenidAuthUrlParams) (*CreateOpenidAuthUrlResponse, error)
	// CreateOpenidLogin POST /access/openid/login
	// Get a new ticket as an HttpOnly cookie. Supports tickets via cookies.
	CreateOpenidLogin(ctx context.Context, params *CreateOpenidLoginParams) (*CreateOpenidLoginResponse, error)
	// ListPermissions GET /access/permissions
	// List permissions of given or currently authenticated user / API token.  Optionally limited to specific path.
	ListPermissions(ctx context.Context, params *ListPermissionsParams) (*ListPermissionsResponse, error)
	// ListRoles GET /access/roles
	// A list of available roles
	ListRoles(ctx context.Context) (*ListRolesResponse, error)
	// ListTfa GET /access/tfa
	// List user TFA configuration.
	ListTfa(ctx context.Context) (*ListTfaResponse, error)
	// GetTfa GET /access/tfa/{userid}
	// Add a TOTP secret to the user.
	GetTfa(ctx context.Context, userid string) (*GetTfaResponse, error)
	// CreateTfa POST /access/tfa/{userid}
	// Add a TFA entry to the user.
	CreateTfa(ctx context.Context, userid string, params *CreateTfaParams) (*CreateTfaResponse, error)
	// DeleteTfa DELETE /access/tfa/{userid}/{id}
	// Delete a single TFA entry.
	DeleteTfa(ctx context.Context, userid string, id string, params *DeleteTfaParams) error
	// GetTfa2 GET /access/tfa/{userid}/{id}
	// Get a single TFA entry.
	GetTfa2(ctx context.Context, userid string, id string) (*GetTfa2Response, error)
	// UpdateTfa PUT /access/tfa/{userid}/{id}
	// Update user's TFA entry description.
	UpdateTfa(ctx context.Context, userid string, id string, params *UpdateTfaParams) error
	// DeleteTicket DELETE /access/ticket
	DeleteTicket(ctx context.Context) error
	// CreateTicket POST /access/ticket
	// Get a new ticket as an HttpOnly cookie. Supports tickets via cookies.
	CreateTicket(ctx context.Context, params *CreateTicketParams) (*CreateTicketResponse, error)
	// ListUsers GET /access/users
	// List users
	ListUsers(ctx context.Context, params *ListUsersParams) (*ListUsersResponse, error)
	// CreateUsers POST /access/users
	// Create new user.
	CreateUsers(ctx context.Context, params *CreateUsersParams) error
	// DeleteUsers DELETE /access/users/{userid}
	// Remove a user from the configuration file.
	DeleteUsers(ctx context.Context, userid string, params *DeleteUsersParams) error
	// GetUsers GET /access/users/{userid}
	// Read user configuration data.
	GetUsers(ctx context.Context, userid string) (*GetUsersResponse, error)
	// UpdateUsers PUT /access/users/{userid}
	// Update user configuration.
	UpdateUsers(ctx context.Context, userid string, params *UpdateUsersParams) error
	// ListUsersToken GET /access/users/{userid}/token
	// List user's API tokens
	ListUsersToken(ctx context.Context, userid string) (*ListUsersTokenResponse, error)
	// DeleteUsersToken DELETE /access/users/{userid}/token/{token-name}
	// Delete a user's API token
	DeleteUsersToken(ctx context.Context, userid string, tokenName string, params *DeleteUsersTokenParams) error
	// GetUsersToken GET /access/users/{userid}/token/{token-name}
	// Read user's API token metadata
	GetUsersToken(ctx context.Context, userid string, tokenName string) (*GetUsersTokenResponse, error)
	// CreateUsersToken POST /access/users/{userid}/token/{token-name}
	// Generate a new API token with given metadata
	CreateUsersToken(ctx context.Context, userid string, tokenName string, params *CreateUsersTokenParams) (*CreateUsersTokenResponse, error)
	// UpdateUsersToken PUT /access/users/{userid}/token/{token-name}
	// Update user's API token metadata. If regenerate is set to true, the token and it's new secret will be returned.
	UpdateUsersToken(ctx context.Context, userid string, tokenName string, params *UpdateUsersTokenParams) (*UpdateUsersTokenResponse, error)
}

// New constructs a Service backed by the given pkg/client.Client.
// The client owns authentication, TLS, retries, and logging; this
// service only translates between typed Go shapes and the raw client.
func New(c client.Client) Service {
	if c == nil {
		panic("access: New called with nil client")
	}
	return &service{c: c}
}

type service struct {
	c client.Client
}

// ListAccess implements Service.ListAccess. GET /access.
func (s *service) ListAccess(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("access.ListAccess: ctx must not be nil")
	}
	path := "/access"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.ListAccess: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.ListAccess: nil response from client")
	}
	_ = resp
	return nil
}

// ListAclParams is the request payload for ListAcl.
type ListAclParams struct {
	// AllForAuthid Whether to return all ACL entries for the exact current authid only. All ACL entries will appear as `AclUgidType::User` ACLs, regardles of whether they are stored as user or group entries. Hence, when using this parameter this endpoint cannot be used to retrieve information for updating the ACL tree directly.
	AllForAuthid *bool `json:"all-for-authid,omitempty"`
	// Exact If set, returns only ACL for the exact path.
	Exact *bool `json:"exact,omitempty"`
	// Path Access control path.
	Path *string `json:"path,omitempty"`
}

// ListAclResponse mirrors the shape returned by GET /access/acl.
type ListAclResponse []json.RawMessage

// ListAcl implements Service.ListAcl. GET /access/acl.
func (s *service) ListAcl(ctx context.Context, params *ListAclParams) (*ListAclResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListAcl: ctx must not be nil")
	}
	path := "/access/acl"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.ListAcl: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("access.ListAcl: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListAcl: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListAcl: nil response from client")
	}
	if resp.Data == nil {
		out := ListAclResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListAcl: re-marshal data: %w", err)
	}
	out := &ListAclResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListAcl: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateAclParams is the request payload for UpdateAcl.
type UpdateAclParams struct {
	// AuthId Authentication ID
	AuthId *string `json:"auth-id,omitempty"`
	// Delete Remove permissions (instead of adding it).
	Delete *bool `json:"delete,omitempty"`
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Group Group ID
	Group *string `json:"group,omitempty"`
	// Path Access control path.
	Path string `json:"path"`
	// Propagate Allow to propagate (inherit) permissions.
	Propagate *bool `json:"propagate,omitempty"`
	// Role Name of a role that the auth id will be granted.
	Role string `json:"role"`
}

// UpdateAcl implements Service.UpdateAcl. PUT /access/acl.
func (s *service) UpdateAcl(ctx context.Context, params *UpdateAclParams) error {
	if ctx == nil {
		return fmt.Errorf("access.UpdateAcl: ctx must not be nil")
	}
	path := "/access/acl"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.UpdateAcl: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("access.UpdateAcl: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.UpdateAcl: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.UpdateAcl: nil response from client")
	}
	_ = resp
	return nil
}

// ListDomainsResponse mirrors the shape returned by GET /access/domains.
type ListDomainsResponse []json.RawMessage

// ListDomains implements Service.ListDomains. GET /access/domains.
func (s *service) ListDomains(ctx context.Context) (*ListDomainsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListDomains: ctx must not be nil")
	}
	path := "/access/domains"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListDomains: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListDomains: nil response from client")
	}
	if resp.Data == nil {
		out := ListDomainsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListDomains: re-marshal data: %w", err)
	}
	out := &ListDomainsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListDomains: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDomainsSyncParams is the request payload for CreateDomainsSync.
type CreateDomainsSyncParams struct {
	// DryRun If set, do not create/delete anything
	DryRun *bool `json:"dry-run,omitempty"`
	// EnableNew Enable newly synced users immediately
	EnableNew *bool `json:"enable-new,omitempty"`
	// RemoveVanished A semicolon-separated list of things to remove when they or the user vanishes during user synchronization. The following values are possible: ``entry`` removes the user when not returned from the sync; ``properties`` removes any  properties on existing user that do not appear in the source. ``acl`` removes ACLs when the user is not returned from the sync.
	RemoveVanished *string `json:"remove-vanished,omitempty"`
}

// CreateDomainsSyncResponse is the raw JSON returned by POST /access/domains/{realm}/sync.
type CreateDomainsSyncResponse = json.RawMessage

// CreateDomainsSync implements Service.CreateDomainsSync. POST /access/domains/{realm}/sync.
func (s *service) CreateDomainsSync(ctx context.Context, realm string, params *CreateDomainsSyncParams) (*CreateDomainsSyncResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.CreateDomainsSync: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/domains/%s/sync", url.PathEscape(realm))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.CreateDomainsSync: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("access.CreateDomainsSync: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.CreateDomainsSync: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.CreateDomainsSync: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDomainsSyncResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.CreateDomainsSync: re-marshal data: %w", err)
	}
	out := &CreateDomainsSyncResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.CreateDomainsSync: unmarshal data: %w", err)
	}
	return out, nil
}

// ListOpenid implements Service.ListOpenid. GET /access/openid.
func (s *service) ListOpenid(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("access.ListOpenid: ctx must not be nil")
	}
	path := "/access/openid"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.ListOpenid: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.ListOpenid: nil response from client")
	}
	_ = resp
	return nil
}

// CreateOpenidAuthUrlParams is the request payload for CreateOpenidAuthUrl.
type CreateOpenidAuthUrlParams struct {
	// Realm Realm name.
	Realm string `json:"realm"`
	// RedirectUrl HTTP(s) url with optional port.
	RedirectUrl string `json:"redirect-url"`
}

// CreateOpenidAuthUrlResponse is the raw JSON returned by POST /access/openid/auth-url.
type CreateOpenidAuthUrlResponse = json.RawMessage

// CreateOpenidAuthUrl implements Service.CreateOpenidAuthUrl. POST /access/openid/auth-url.
func (s *service) CreateOpenidAuthUrl(ctx context.Context, params *CreateOpenidAuthUrlParams) (*CreateOpenidAuthUrlResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.CreateOpenidAuthUrl: ctx must not be nil")
	}
	path := "/access/openid/auth-url"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.CreateOpenidAuthUrl: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("access.CreateOpenidAuthUrl: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.CreateOpenidAuthUrl: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.CreateOpenidAuthUrl: nil response from client")
	}
	if resp.Data == nil {
		out := CreateOpenidAuthUrlResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.CreateOpenidAuthUrl: re-marshal data: %w", err)
	}
	out := &CreateOpenidAuthUrlResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.CreateOpenidAuthUrl: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateOpenidLoginParams is the request payload for CreateOpenidLogin.
type CreateOpenidLoginParams struct {
	// Code OpenId authorization code.
	Code string `json:"code"`
	// RedirectUrl Redirection Url. The client should set this to used server url.
	RedirectUrl string `json:"redirect-url"`
	// State OpenId state.
	State string `json:"state"`
}

// CreateOpenidLoginResponse mirrors the shape returned by POST /access/openid/login.
type CreateOpenidLoginResponse struct {
	// CSRFPreventionToken The CSRF prevention token.
	CSRFPreventionToken *string `json:"CSRFPreventionToken,omitempty"`
	// Ticket The ticket as is supposed to be used in the authentication header. Not provided here if the endpoint uses HttpOnly cookies to supply the actual ticket.
	Ticket *string `json:"ticket,omitempty"`
	// TicketInfo Like a full ticket, except the signature is missing. Useful in HttpOnly-contexts (browsers).
	TicketInfo *string `json:"ticket-info,omitempty"`
	// Username User ID
	Username string `json:"username"`
}

// CreateOpenidLogin implements Service.CreateOpenidLogin. POST /access/openid/login.
func (s *service) CreateOpenidLogin(ctx context.Context, params *CreateOpenidLoginParams) (*CreateOpenidLoginResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.CreateOpenidLogin: ctx must not be nil")
	}
	path := "/access/openid/login"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.CreateOpenidLogin: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("access.CreateOpenidLogin: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.CreateOpenidLogin: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.CreateOpenidLogin: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.CreateOpenidLogin: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.CreateOpenidLogin: re-marshal data: %w", err)
	}
	out := &CreateOpenidLoginResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.CreateOpenidLogin: unmarshal data: %w", err)
	}
	return out, nil
}

// ListPermissionsParams is the request payload for ListPermissions.
type ListPermissionsParams struct {
	// AuthId Authentication ID
	AuthId *string `json:"auth-id,omitempty"`
	// Path Access control path.
	Path *string `json:"path,omitempty"`
}

// ListPermissionsResponse is the raw JSON returned by GET /access/permissions.
type ListPermissionsResponse = json.RawMessage

// ListPermissions implements Service.ListPermissions. GET /access/permissions.
func (s *service) ListPermissions(ctx context.Context, params *ListPermissionsParams) (*ListPermissionsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListPermissions: ctx must not be nil")
	}
	path := "/access/permissions"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.ListPermissions: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("access.ListPermissions: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListPermissions: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListPermissions: nil response from client")
	}
	if resp.Data == nil {
		out := ListPermissionsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListPermissions: re-marshal data: %w", err)
	}
	out := &ListPermissionsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListPermissions: unmarshal data: %w", err)
	}
	return out, nil
}

// ListRolesResponse mirrors the shape returned by GET /access/roles.
type ListRolesResponse []json.RawMessage

// ListRoles implements Service.ListRoles. GET /access/roles.
func (s *service) ListRoles(ctx context.Context) (*ListRolesResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListRoles: ctx must not be nil")
	}
	path := "/access/roles"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListRoles: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListRoles: nil response from client")
	}
	if resp.Data == nil {
		out := ListRolesResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListRoles: re-marshal data: %w", err)
	}
	out := &ListRolesResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListRoles: unmarshal data: %w", err)
	}
	return out, nil
}

// ListTfaResponse mirrors the shape returned by GET /access/tfa.
type ListTfaResponse []json.RawMessage

// ListTfa implements Service.ListTfa. GET /access/tfa.
func (s *service) ListTfa(ctx context.Context) (*ListTfaResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListTfa: ctx must not be nil")
	}
	path := "/access/tfa"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListTfa: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListTfa: nil response from client")
	}
	if resp.Data == nil {
		out := ListTfaResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListTfa: re-marshal data: %w", err)
	}
	out := &ListTfaResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListTfa: unmarshal data: %w", err)
	}
	return out, nil
}

// GetTfaResponse mirrors the shape returned by GET /access/tfa/{userid}.
type GetTfaResponse []json.RawMessage

// GetTfa implements Service.GetTfa. GET /access/tfa/{userid}.
func (s *service) GetTfa(ctx context.Context, userid string) (*GetTfaResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.GetTfa: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/tfa/%s", url.PathEscape(userid))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.GetTfa: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.GetTfa: nil response from client")
	}
	if resp.Data == nil {
		out := GetTfaResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.GetTfa: re-marshal data: %w", err)
	}
	out := &GetTfaResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.GetTfa: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateTfaParams is the request payload for CreateTfa.
type CreateTfaParams struct {
	// Challenge When responding to a u2f challenge: the original challenge string
	Challenge *string `json:"challenge,omitempty"`
	// Description A description to distinguish multiple entries from one another
	Description *string `json:"description,omitempty"`
	// Password Password.
	Password *string `json:"password,omitempty"`
	// Totp A totp URI.
	Totp *string `json:"totp,omitempty"`
	// Type A TFA entry type.
	Type string `json:"type"`
	// Value The current value for the provided totp URI, or a Webauthn/U2F challenge response
	Value *string `json:"value,omitempty"`
}

// CreateTfaResponse mirrors the shape returned by POST /access/tfa/{userid}.
type CreateTfaResponse struct {
	// Challenge When adding u2f entries, this contains a challenge the user must respond to in order to finish the registration.
	Challenge *string `json:"challenge,omitempty"`
	// Id The id if a newly added TFA entry.
	Id *string `json:"id,omitempty"`
	// Recovery A list of recovery codes as integers.
	Recovery []client.PVEInt `json:"recovery"`
}

// CreateTfa implements Service.CreateTfa. POST /access/tfa/{userid}.
func (s *service) CreateTfa(ctx context.Context, userid string, params *CreateTfaParams) (*CreateTfaResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.CreateTfa: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/tfa/%s", url.PathEscape(userid))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.CreateTfa: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("access.CreateTfa: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.CreateTfa: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.CreateTfa: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.CreateTfa: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.CreateTfa: re-marshal data: %w", err)
	}
	out := &CreateTfaResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.CreateTfa: unmarshal data: %w", err)
	}
	return out, nil
}

// DeleteTfaParams is the request payload for DeleteTfa.
type DeleteTfaParams struct {
	// Password Password.
	Password *string `json:"password,omitempty"`
}

// DeleteTfa implements Service.DeleteTfa. DELETE /access/tfa/{userid}/{id}.
func (s *service) DeleteTfa(ctx context.Context, userid string, id string, params *DeleteTfaParams) error {
	if ctx == nil {
		return fmt.Errorf("access.DeleteTfa: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/tfa/%s/%s", url.PathEscape(userid), url.PathEscape(id))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.DeleteTfa: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("access.DeleteTfa: decode params: %w", err)
		}
	}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.DeleteTfa: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.DeleteTfa: nil response from client")
	}
	_ = resp
	return nil
}

// GetTfa2Response mirrors the shape returned by GET /access/tfa/{userid}/{id}.
type GetTfa2Response struct {
	// Created Creation time of this entry as unix epoch.
	Created client.PVEInt `json:"created"`
	// Description User chosen description for this entry.
	Description string `json:"description"`
	// Enable Whether this TFA entry is currently enabled.
	Enable client.PVEBool `json:"enable"`
	// Id The id used to reference this entry.
	Id string `json:"id"`
	// Type A TFA entry type.
	Type string `json:"type"`
}

// GetTfa2 implements Service.GetTfa2. GET /access/tfa/{userid}/{id}.
func (s *service) GetTfa2(ctx context.Context, userid string, id string) (*GetTfa2Response, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.GetTfa2: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/tfa/%s/%s", url.PathEscape(userid), url.PathEscape(id))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.GetTfa2: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.GetTfa2: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.GetTfa2: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.GetTfa2: re-marshal data: %w", err)
	}
	out := &GetTfa2Response{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.GetTfa2: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateTfaParams is the request payload for UpdateTfa.
type UpdateTfaParams struct {
	// Description A description to distinguish multiple entries from one another
	Description *string `json:"description,omitempty"`
	// Enable Whether this entry should currently be enabled or disabled
	Enable *bool `json:"enable,omitempty"`
	// Password Password.
	Password *string `json:"password,omitempty"`
}

// UpdateTfa implements Service.UpdateTfa. PUT /access/tfa/{userid}/{id}.
func (s *service) UpdateTfa(ctx context.Context, userid string, id string, params *UpdateTfaParams) error {
	if ctx == nil {
		return fmt.Errorf("access.UpdateTfa: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/tfa/%s/%s", url.PathEscape(userid), url.PathEscape(id))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.UpdateTfa: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("access.UpdateTfa: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.UpdateTfa: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.UpdateTfa: nil response from client")
	}
	_ = resp
	return nil
}

// DeleteTicket implements Service.DeleteTicket. DELETE /access/ticket.
func (s *service) DeleteTicket(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("access.DeleteTicket: ctx must not be nil")
	}
	path := "/access/ticket"
	var body map[string]interface{}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.DeleteTicket: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.DeleteTicket: nil response from client")
	}
	_ = resp
	return nil
}

// CreateTicketParams is the request payload for CreateTicket.
type CreateTicketParams struct {
	// Password The secret password. This can also be a valid ticket. Only optional if the ticket is provided in a cookie header and only if the endpoint supports this.
	Password *string `json:"password,omitempty"`
	// Path Verify ticket, and check if user have access 'privs' on 'path'.
	Path *string `json:"path,omitempty"`
	// Port Port for verifying terminal tickets.
	Port *int64 `json:"port,omitempty"`
	// Privs Verify ticket, and check if user have access 'privs' on 'path'.
	Privs *string `json:"privs,omitempty"`
	// TfaChallenge The signed TFA challenge string the user wants to respond to.
	TfaChallenge *string `json:"tfa-challenge,omitempty"`
	// Username User ID
	Username string `json:"username"`
}

// CreateTicketResponse mirrors the shape returned by POST /access/ticket.
type CreateTicketResponse struct {
	// CSRFPreventionToken The CSRF prevention token.
	CSRFPreventionToken *string `json:"CSRFPreventionToken,omitempty"`
	// Ticket The ticket as is supposed to be used in the authentication header. Not provided here if the endpoint uses HttpOnly cookies to supply the actual ticket.
	Ticket *string `json:"ticket,omitempty"`
	// TicketInfo Like a full ticket, except the signature is missing. Useful in HttpOnly-contexts (browsers).
	TicketInfo *string `json:"ticket-info,omitempty"`
	// Username User ID
	Username string `json:"username"`
}

// CreateTicket implements Service.CreateTicket. POST /access/ticket.
func (s *service) CreateTicket(ctx context.Context, params *CreateTicketParams) (*CreateTicketResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.CreateTicket: ctx must not be nil")
	}
	path := "/access/ticket"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.CreateTicket: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("access.CreateTicket: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.CreateTicket: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.CreateTicket: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.CreateTicket: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.CreateTicket: re-marshal data: %w", err)
	}
	out := &CreateTicketResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.CreateTicket: unmarshal data: %w", err)
	}
	return out, nil
}

// ListUsersParams is the request payload for ListUsers.
type ListUsersParams struct {
	// IncludeTokens Include user's API tokens in returned list.
	IncludeTokens *bool `json:"include_tokens,omitempty"`
}

// ListUsersResponse mirrors the shape returned by GET /access/users.
type ListUsersResponse []json.RawMessage

// ListUsers implements Service.ListUsers. GET /access/users.
func (s *service) ListUsers(ctx context.Context, params *ListUsersParams) (*ListUsersResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListUsers: ctx must not be nil")
	}
	path := "/access/users"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.ListUsers: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("access.ListUsers: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListUsers: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListUsers: nil response from client")
	}
	if resp.Data == nil {
		out := ListUsersResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListUsers: re-marshal data: %w", err)
	}
	out := &ListUsersResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListUsers: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateUsersParams is the request payload for CreateUsers.
type CreateUsersParams struct {
	// Comment Comment.
	Comment *string `json:"comment,omitempty"`
	// Email E-Mail Address.
	Email *string `json:"email,omitempty"`
	// Enable Enable the account (default). You can set this to '0' to disable the account.
	Enable *bool `json:"enable,omitempty"`
	// Expire Account expiration date (seconds since epoch). '0' means no expiration date.
	Expire *int64 `json:"expire,omitempty"`
	// Firstname First name.
	Firstname *string `json:"firstname,omitempty"`
	// Lastname Last name.
	Lastname *string `json:"lastname,omitempty"`
	// Password User Password.
	Password *string `json:"password,omitempty"`
	// Userid User ID
	Userid string `json:"userid"`
}

// CreateUsers implements Service.CreateUsers. POST /access/users.
func (s *service) CreateUsers(ctx context.Context, params *CreateUsersParams) error {
	if ctx == nil {
		return fmt.Errorf("access.CreateUsers: ctx must not be nil")
	}
	path := "/access/users"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.CreateUsers: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("access.CreateUsers: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.CreateUsers: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.CreateUsers: nil response from client")
	}
	_ = resp
	return nil
}

// DeleteUsersParams is the request payload for DeleteUsers.
type DeleteUsersParams struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
}

// DeleteUsers implements Service.DeleteUsers. DELETE /access/users/{userid}.
func (s *service) DeleteUsers(ctx context.Context, userid string, params *DeleteUsersParams) error {
	if ctx == nil {
		return fmt.Errorf("access.DeleteUsers: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s", url.PathEscape(userid))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.DeleteUsers: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("access.DeleteUsers: decode params: %w", err)
		}
	}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.DeleteUsers: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.DeleteUsers: nil response from client")
	}
	_ = resp
	return nil
}

// GetUsersResponse mirrors the shape returned by GET /access/users/{userid}.
type GetUsersResponse struct {
	// Comment Comment.
	Comment *string `json:"comment,omitempty"`
	// Email E-Mail Address.
	Email *string `json:"email,omitempty"`
	// Enable Enable the account (default). You can set this to '0' to disable the account.
	Enable *client.PVEBool `json:"enable,omitempty"`
	// Expire Account expiration date (seconds since epoch). '0' means no expiration date.
	Expire *client.PVEInt `json:"expire,omitempty"`
	// Firstname First name.
	Firstname *string `json:"firstname,omitempty"`
	// Lastname Last name.
	Lastname *string `json:"lastname,omitempty"`
	// Userid User ID
	Userid string `json:"userid"`
}

// GetUsers implements Service.GetUsers. GET /access/users/{userid}.
func (s *service) GetUsers(ctx context.Context, userid string) (*GetUsersResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.GetUsers: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s", url.PathEscape(userid))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.GetUsers: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.GetUsers: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.GetUsers: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.GetUsers: re-marshal data: %w", err)
	}
	out := &GetUsersResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.GetUsers: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateUsersParams is the request payload for UpdateUsers.
type UpdateUsersParams struct {
	// Comment Comment.
	Comment *string `json:"comment,omitempty"`
	// Delete List of properties to delete.
	Delete []string `json:"delete,omitempty"`
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Email E-Mail Address.
	Email *string `json:"email,omitempty"`
	// Enable Enable the account (default). You can set this to '0' to disable the account.
	Enable *bool `json:"enable,omitempty"`
	// Expire Account expiration date (seconds since epoch). '0' means no expiration date.
	Expire *int64 `json:"expire,omitempty"`
	// Firstname First name.
	Firstname *string `json:"firstname,omitempty"`
	// Lastname Last name.
	Lastname *string `json:"lastname,omitempty"`
	// Password User Password.
	Password *string `json:"password,omitempty"`
}

// UpdateUsers implements Service.UpdateUsers. PUT /access/users/{userid}.
func (s *service) UpdateUsers(ctx context.Context, userid string, params *UpdateUsersParams) error {
	if ctx == nil {
		return fmt.Errorf("access.UpdateUsers: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s", url.PathEscape(userid))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.UpdateUsers: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("access.UpdateUsers: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.UpdateUsers: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.UpdateUsers: nil response from client")
	}
	_ = resp
	return nil
}

// ListUsersTokenResponse mirrors the shape returned by GET /access/users/{userid}/token.
type ListUsersTokenResponse []json.RawMessage

// ListUsersToken implements Service.ListUsersToken. GET /access/users/{userid}/token.
func (s *service) ListUsersToken(ctx context.Context, userid string) (*ListUsersTokenResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.ListUsersToken: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s/token", url.PathEscape(userid))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.ListUsersToken: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.ListUsersToken: nil response from client")
	}
	if resp.Data == nil {
		out := ListUsersTokenResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.ListUsersToken: re-marshal data: %w", err)
	}
	out := &ListUsersTokenResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.ListUsersToken: unmarshal data: %w", err)
	}
	return out, nil
}

// DeleteUsersTokenParams is the request payload for DeleteUsersToken.
type DeleteUsersTokenParams struct {
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
}

// DeleteUsersToken implements Service.DeleteUsersToken. DELETE /access/users/{userid}/token/{token-name}.
func (s *service) DeleteUsersToken(ctx context.Context, userid string, tokenName string, params *DeleteUsersTokenParams) error {
	if ctx == nil {
		return fmt.Errorf("access.DeleteUsersToken: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s/token/%s", url.PathEscape(userid), url.PathEscape(tokenName))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("access.DeleteUsersToken: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("access.DeleteUsersToken: decode params: %w", err)
		}
	}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("access.DeleteUsersToken: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("access.DeleteUsersToken: nil response from client")
	}
	_ = resp
	return nil
}

// GetUsersTokenResponse mirrors the shape returned by GET /access/users/{userid}/token/{token-name}.
type GetUsersTokenResponse struct {
	// Comment Comment.
	Comment *string `json:"comment,omitempty"`
	// Enable Enable the account (default). You can set this to '0' to disable the account.
	Enable *client.PVEBool `json:"enable,omitempty"`
	// Expire Account expiration date (seconds since epoch). '0' means no expiration date.
	Expire *client.PVEInt `json:"expire,omitempty"`
	// Tokenid API Token ID
	Tokenid string `json:"tokenid"`
}

// GetUsersToken implements Service.GetUsersToken. GET /access/users/{userid}/token/{token-name}.
func (s *service) GetUsersToken(ctx context.Context, userid string, tokenName string) (*GetUsersTokenResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.GetUsersToken: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s/token/%s", url.PathEscape(userid), url.PathEscape(tokenName))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.GetUsersToken: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.GetUsersToken: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.GetUsersToken: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.GetUsersToken: re-marshal data: %w", err)
	}
	out := &GetUsersTokenResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.GetUsersToken: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateUsersTokenParams is the request payload for CreateUsersToken.
type CreateUsersTokenParams struct {
	// Comment Comment.
	Comment *string `json:"comment,omitempty"`
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Enable Enable the account (default). You can set this to '0' to disable the account.
	Enable *bool `json:"enable,omitempty"`
	// Expire Account expiration date (seconds since epoch). '0' means no expiration date.
	Expire *int64 `json:"expire,omitempty"`
}

// CreateUsersTokenResponse mirrors the shape returned by POST /access/users/{userid}/token/{token-name}.
type CreateUsersTokenResponse struct {
	// Tokenid Authentication ID
	Tokenid string `json:"tokenid"`
	// Value The secret associated with the token.
	Value string `json:"value"`
}

// CreateUsersToken implements Service.CreateUsersToken. POST /access/users/{userid}/token/{token-name}.
func (s *service) CreateUsersToken(ctx context.Context, userid string, tokenName string, params *CreateUsersTokenParams) (*CreateUsersTokenResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.CreateUsersToken: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s/token/%s", url.PathEscape(userid), url.PathEscape(tokenName))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.CreateUsersToken: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("access.CreateUsersToken: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.CreateUsersToken: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.CreateUsersToken: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("access.CreateUsersToken: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.CreateUsersToken: re-marshal data: %w", err)
	}
	out := &CreateUsersTokenResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.CreateUsersToken: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateUsersTokenParams is the request payload for UpdateUsersToken.
type UpdateUsersTokenParams struct {
	// Comment Comment.
	Comment *string `json:"comment,omitempty"`
	// Delete List of properties to delete.
	Delete []string `json:"delete,omitempty"`
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Enable Enable the account (default). You can set this to '0' to disable the account.
	Enable *bool `json:"enable,omitempty"`
	// Expire Account expiration date (seconds since epoch). '0' means no expiration date.
	Expire *int64 `json:"expire,omitempty"`
	// Regenerate Regenerate token secret while keeping permissions.
	Regenerate *bool `json:"regenerate,omitempty"`
}

// UpdateUsersTokenResponse mirrors the shape returned by PUT /access/users/{userid}/token/{token-name}.
type UpdateUsersTokenResponse struct {
	Tokenid string  `json:"tokenid"`
	Value   *string `json:"value,omitempty"`
}

// UpdateUsersToken implements Service.UpdateUsersToken. PUT /access/users/{userid}/token/{token-name}.
func (s *service) UpdateUsersToken(ctx context.Context, userid string, tokenName string, params *UpdateUsersTokenParams) (*UpdateUsersTokenResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("access.UpdateUsersToken: ctx must not be nil")
	}
	path := fmt.Sprintf("/access/users/%s/token/%s", url.PathEscape(userid), url.PathEscape(tokenName))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("access.UpdateUsersToken: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("access.UpdateUsersToken: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("access.UpdateUsersToken: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("access.UpdateUsersToken: nil response from client")
	}
	if resp.Data == nil {
		out := UpdateUsersTokenResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("access.UpdateUsersToken: re-marshal data: %w", err)
	}
	out := &UpdateUsersTokenResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("access.UpdateUsersToken: unmarshal data: %w", err)
	}
	return out, nil
}
